-- 数据确权申请单表
-- 智能确权辅助工具:上传材料 / 解析要素 / 与表单比对
CREATE TABLE IF NOT EXISTS IM_AIT_MATERIAL (
    CEC_MATERIAL_ID   VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_BATCH_NO      VARCHAR(64),
    CEC_APPLY_ID      VARCHAR(64),
    CEC_ASSET_ID      VARCHAR(64),
    CEC_FILE_NAME     VARCHAR(500),
    CEC_FILE_TYPE     VARCHAR(20),
    CEC_FILE_HASH     VARCHAR(64),
    CEC_SIZE_KB       BIGINT,
    CEC_PARSE_STATUS  VARCHAR(20),
    CEC_FAIL_REASON   VARCHAR(1000),
    CEC_PROGRESS      INT DEFAULT 0,
    CEC_STORAGE_PATH  VARCHAR(500),
    CEC_CONTENT       CLOB,
    CEC_CATEGORY      VARCHAR(50),
    CEC_DATA_TABLE_REF VARCHAR(255),
    CEC_LAYOUT_JSON   CLOB,
    CEC_DUPLICATE_OF  VARCHAR(64),
    CEC_PAGE_COUNT    INT,
    CEC_OCR_USED      INT DEFAULT 0,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:多粒度解析片段(按页/段/表格单元;统一文档对象的标准化切片)
CREATE TABLE IF NOT EXISTS IM_AIT_DOC_SEGMENT (
    CEC_SEGMENT_ID    VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_MATERIAL_ID   VARCHAR(64),
    CEC_GRANULARITY   VARCHAR(20),
    CEC_PAGE_NO       INT,
    CEC_SEG_INDEX     INT,
    CEC_SHEET_NAME    VARCHAR(100),
    CEC_ROW_NUM       INT,
    CEC_COL_NUM       INT,
    CEC_CONTENT       CLOB,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:清洗日志(#6 追溯 原始值/清洗规则/转换结果/清洗方式)
CREATE TABLE IF NOT EXISTS IM_AIT_CLEAN_LOG (
    CEC_LOG_ID        VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_MATERIAL_ID   VARCHAR(64),
    CEC_BATCH_NO      VARCHAR(64),
    CEC_ROW_NO        INT,
    CEC_FIELD         VARCHAR(64),
    CEC_RAW_KEY       VARCHAR(128),
    CEC_ORIGINAL_VALUE VARCHAR(2000),
    CEC_RULE          VARCHAR(255),
    CEC_CLEANED_VALUE VARCHAR(2000),
    CEC_METHOD        VARCHAR(20),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:统一审核底表(#4 抽取↔模板映射 / #5 缺失·冲突·异常 + 待补正)
CREATE TABLE IF NOT EXISTS IM_AIT_AUDIT_BASE (
    CEC_AUDIT_ID      VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_MATERIAL_ID   VARCHAR(64),
    CEC_BATCH_NO      VARCHAR(64),
    CEC_ROW_NO        INT,
    CEC_TEMPLATE_FIELD VARCHAR(64),
    CEC_FIELD_LABEL   VARCHAR(64),
    CEC_RAW_VALUE     VARCHAR(2000),
    CEC_CLEAN_VALUE   VARCHAR(2000),
    CEC_STATUS        VARCHAR(20),
    CEC_ISSUE         VARCHAR(500),
    CEC_SUGGESTION    VARCHAR(500),
    CEC_DATA_TABLE_REF VARCHAR(255),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:结构化确权画像(#6 表级/附件级特征视图)
CREATE TABLE IF NOT EXISTS IM_AIT_PROFILE (
    CEC_PROFILE_ID    VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_MATERIAL_ID   VARCHAR(64),
    CEC_DATA_TABLE_REF VARCHAR(255),
    CEC_LEVEL         VARCHAR(20),
    CEC_SOURCE_METHOD VARCHAR(50),
    CEC_SOURCE_METHOD_BY VARCHAR(20),
    CEC_DATA_FEATURES VARCHAR(500),
    CEC_ELEMENTS_JSON CLOB,
    CEC_CONFIDENCE    DOUBLE,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:关键主体(#2 来源/授权/使用/加工/共享 主体)
CREATE TABLE IF NOT EXISTS IM_AIT_PROFILE_SUBJECT (
    CEC_SUBJECT_ID    VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_PROFILE_ID    VARCHAR(64),
    CEC_MATERIAL_ID   VARCHAR(64),
    CEC_SUBJECT_ROLE  VARCHAR(40),
    CEC_SUBJECT_NAME  VARCHAR(500),
    CEC_METHOD        VARCHAR(20),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:约束信息(#5 授权范围/使用边界/共享限制/保留期限/脱敏要求)
CREATE TABLE IF NOT EXISTS IM_AIT_CONSTRAINT (
    CEC_CONSTRAINT_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_PROFILE_ID    VARCHAR(64),
    CEC_MATERIAL_ID   VARCHAR(64),
    CEC_CONSTRAINT_TYPE VARCHAR(40),
    CEC_CONSTRAINT_VALUE VARCHAR(1000),
    CEC_METHOD        VARCHAR(20),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:解析记录档(1.4#1 解析时间/文档名/字段/值/置信度/操作人,可查询导出)
CREATE TABLE IF NOT EXISTS IM_AIT_PARSE_RECORD (
    CEC_RECORD_ID     VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_MATERIAL_ID   VARCHAR(64),
    CEC_FILE_NAME     VARCHAR(500),
    CEC_BATCH_NO      VARCHAR(64),
    CEC_FIELD         VARCHAR(64),
    CEC_FIELD_VALUE   VARCHAR(2000),
    CEC_CONFIDENCE    DOUBLE,
    CEC_OPERATOR_ID   VARCHAR(64),
    CEC_OPERATOR_NAME VARCHAR(64),
    CEC_PARSE_TIME    TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:资料模板库(1.4#3 确权书/授权函/权属证明,在线编辑/版本/下载)
CREATE TABLE IF NOT EXISTS IM_AIT_DOC_TEMPLATE (
    CEC_TEMPLATE_ID   VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_TEMPLATE_TYPE VARCHAR(50),
    CEC_TEMPLATE_NAME VARCHAR(255),
    CEC_VERSION       VARCHAR(20),
    CEC_CONTENT       CLOB,
    CEC_FILE_NAME     VARCHAR(300),
    CEC_FILE_DATA     CLOB,
    CEC_IS_LATEST     BOOLEAN DEFAULT TRUE,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:解析元数据配置(1.4#4 字段映射/提取逻辑/置信度阈值,管理员可配)
CREATE TABLE IF NOT EXISTS IM_AIT_PARSE_CONFIG (
    CEC_CONFIG_ID     VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_SCENE         VARCHAR(50),
    CEC_FIELD_MAPPING_JSON CLOB,
    CEC_EXTRACT_LOGIC_JSON CLOB,
    CEC_CONFIDENCE_THRESHOLD DOUBLE,
    CEC_ENABLED       INT DEFAULT 1,
    CEC_REMARK        VARCHAR(500),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:产权知识库-文档(2.1#1/#6 法规/标准/制度/审核规则/案例 + 知识域 + 版本治理)
CREATE TABLE IF NOT EXISTS IM_AIT_KB_DOC (
    CEC_DOC_ID        VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_DOC_TYPE      VARCHAR(40),
    CEC_DOMAIN        VARCHAR(40),
    CEC_TITLE         VARCHAR(300),
    CEC_SOURCE        VARCHAR(300),
    CEC_EFFECTIVE_DATE VARCHAR(20),
    CEC_SCOPE         VARCHAR(500),
    CEC_VERSION       VARCHAR(20),
    CEC_IS_LATEST     BOOLEAN DEFAULT TRUE,
    CEC_STATUS        VARCHAR(20),
    CEC_CONTENT       CLOB,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:产权知识库-切片(2.1#2/#3 分段/标签/向量/索引 + 条款元数据)
CREATE TABLE IF NOT EXISTS IM_AIT_KB_CHUNK (
    CEC_CHUNK_ID      VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_DOC_ID        VARCHAR(64),
    CEC_DOC_TYPE      VARCHAR(40),
    CEC_DOMAIN        VARCHAR(40),
    CEC_TITLE         VARCHAR(300),
    CEC_CLAUSE_NO     VARCHAR(50),
    CEC_TAGS          VARCHAR(500),
    CEC_CONTENT       CLOB,
    CEC_VECTOR_JSON   CLOB,
    CEC_VECTOR_DIM    INT,
    CEC_EFFECTIVE_DATE VARCHAR(20),
    CEC_SCOPE         VARCHAR(500),
    CEC_STATUS        VARCHAR(20),
    CEC_SEQ           INT,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS IM_AIT_PARSE_RESULT (
    CEC_PARSE_ID      VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_MATERIAL_ID   VARCHAR(64),
    CEC_RIGHT_SUBJECT VARCHAR(500),
    CEC_RIGHT_OBJECT  VARCHAR(500),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_RIGHT_TERM    VARCHAR(100),
    CEC_AUTH_SCOPE    VARCHAR(500),
    CEC_DATA_SOURCE   VARCHAR(100),
    CEC_SENSITIVE_TYPE VARCHAR(100),
    CEC_SEAL_VALID    VARCHAR(20),
    CEC_SEAL_DESC     VARCHAR(500),
    CEC_CONFIDENCE    DOUBLE,
    CEC_REVIEW_STATUS VARCHAR(50),
    CEC_TRUST_SCORE   INT,
    CEC_TRUST_LEVEL   VARCHAR(50),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS IM_AIT_COMPARE (
    CEC_COMPARE_ID    VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_PARSE_ID      VARCHAR(64),
    CEC_APPLY_ID      VARCHAR(64),
    CEC_FIELD         VARCHAR(100),
    CEC_MATERIAL_VALUE VARCHAR(1000),
    CEC_FORM_VALUE    VARCHAR(1000),
    CEC_DIFF_TYPE     VARCHAR(20),
    CEC_SOURCE_OFFSET INT,
    CEC_SOURCE_SNIPPET VARCHAR(500),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:权属主张(知识图谱)/ 权属冲突
CREATE TABLE IF NOT EXISTS IM_AIT_KG_CLAIM (
    CEC_CLAIM_ID      VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_ASSET_ID      VARCHAR(64),
    CEC_SUBJECT       VARCHAR(255),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_AUTH_SCOPE    VARCHAR(500),
    CEC_VALID_DATE    TIMESTAMP,
    CEC_EXCLUSIVE     BOOLEAN,
    CEC_SOURCE_TYPE   VARCHAR(50),
    CEC_REMARK        VARCHAR(1000),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS IM_AIT_CONFLICT (
    CEC_CONFLICT_ID   VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_ASSET_ID      VARCHAR(64),
    CEC_CONFLICT_TYPE VARCHAR(50),
    CEC_CONFLICT_SOURCE VARCHAR(255),
    CEC_CONFLICT_DESC VARCHAR(2000),
    CEC_IMPACT_SCOPE  VARCHAR(1000),
    CEC_RISK_LEVEL    VARCHAR(20),
    CEC_SUGGESTION    VARCHAR(2000),
    CEC_STATUS        VARCHAR(20),
    CEC_RELATED_RECORD_NO VARCHAR(255),
    CEC_CONFLICT_FIELDS VARCHAR(255),
    CEC_CLAUSE_REF    VARCHAR(500),
    CEC_LEGAL_RISK    VARCHAR(40),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:冲突识别规则配置(主体/权限重叠/期限交叉等,启停/优先级/阈值)
CREATE TABLE IF NOT EXISTS IM_AIT_CONFLICT_RULE (
    CEC_RULE_ID       VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_RULE_TYPE     VARCHAR(40),
    CEC_RULE_NAME     VARCHAR(100),
    CEC_ENABLED       INT DEFAULT 1,
    CEC_PRIORITY      INT DEFAULT 100,
    CEC_THRESHOLD     DOUBLE,
    CEC_REMARK        VARCHAR(500),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:智能确权 Agent 审核结果(3.1 多阶段链路/双通道/多级机制/结构化结论)
CREATE TABLE IF NOT EXISTS IM_AIT_AUDIT_RESULT (
    CEC_AUDIT_ID      VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_APPLY_ID      VARCHAR(64),
    CEC_ASSET_ID      VARCHAR(64),
    CEC_CHANNEL       VARCHAR(20),
    CEC_DATA_CLASS    VARCHAR(100),
    CEC_DATA_GRADE    VARCHAR(40),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_AUTH_ADVICE   VARCHAR(40),
    CEC_AUTH_LEVEL    VARCHAR(40),
    CEC_RESTRICTIONS  VARCHAR(1000),
    CEC_RISK_LEVEL    VARCHAR(20),
    CEC_SUPPLEMENT    VARCHAR(1000),
    CEC_REASON        VARCHAR(2000),
    CEC_CITATIONS     VARCHAR(1000),
    CEC_ACTION        VARCHAR(255),
    CEC_SCORE         DOUBLE,
    CEC_STAGE_TRACE_JSON CLOB,
    CEC_TOOL_TRACE_JSON  CLOB,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:批量任务(3.3#5 并发/断点续跑/失败重试/留痕 + #4 任务监控)
CREATE TABLE IF NOT EXISTS IM_AIT_TASK (
    CEC_TASK_ID       VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_TASK_TYPE     VARCHAR(40),
    CEC_TASK_NAME     VARCHAR(200),
    CEC_ITEMS_JSON    CLOB,
    CEC_ITEM_STATE_JSON CLOB,
    CEC_TOTAL         INT DEFAULT 0,
    CEC_DONE          INT DEFAULT 0,
    CEC_FAILED        INT DEFAULT 0,
    CEC_STATUS        VARCHAR(20),
    CEC_CONCURRENCY   INT DEFAULT 4,
    CEC_RETRY_MAX     INT DEFAULT 2,
    CEC_CURSOR        INT DEFAULT 0,
    CEC_LAST_ERROR    VARCHAR(1000),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:统一运行日志(3.3#6 审计/操作/模型调用/规则命中/告警 统一管理)
CREATE TABLE IF NOT EXISTS IM_AIT_RUN_LOG (
    CEC_LOG_ID        VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_LOG_TYPE      VARCHAR(20),
    CEC_SOURCE        VARCHAR(100),
    CEC_ACTION        VARCHAR(100),
    CEC_DETAIL        VARCHAR(2000),
    CEC_MODEL         VARCHAR(64),
    CEC_DURATION_MS   BIGINT,
    CEC_RESULT        VARCHAR(20),
    CEC_TASK_ID       VARCHAR(64),
    CEC_LOG_TIME      TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:审核证据链档案(3.2#4 关联 材料片段/KB命中片段/规则命中项/模型理由/结论 + 留痕)
CREATE TABLE IF NOT EXISTS IM_AIT_EVIDENCE (
    CEC_EVIDENCE_ID   VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_APPLY_ID      VARCHAR(64),
    CEC_ASSET_ID      VARCHAR(64),
    CEC_MATERIAL_SNIPPETS_JSON CLOB,
    CEC_KB_HITS_JSON  CLOB,
    CEC_RULE_HITS_JSON CLOB,
    CEC_MODEL_REASON  CLOB,
    CEC_CONCLUSION    VARCHAR(500),
    CEC_SM3_HASH      VARCHAR(80),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 智能确权辅助工具:确权决策建议
CREATE TABLE IF NOT EXISTS IM_AIT_DECISION (
    CEC_DECISION_ID   VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_APPLY_ID      VARCHAR(64),
    CEC_ASSET_ID      VARCHAR(64),
    CEC_PREDICTION    VARCHAR(50),
    CEC_SCORE         DOUBLE,
    CEC_FACTORS_JSON  CLOB,
    CEC_STRENGTH      VARCHAR(500),
    CEC_WEAKNESS      VARCHAR(500),
    CEC_SPLIT_PLAN    VARCHAR(2000),
    CEC_SPLIT_PLANS_JSON CLOB,
    CEC_REASON        VARCHAR(2000),
    CEC_SUPPLEMENT    VARCHAR(1000),
    CEC_PENDING_CONFLICTS VARCHAR(1000),
    CEC_RAG_ADVICE    CLOB,
    CEC_AI_PREDICTION VARCHAR(50),
    CEC_RAG_CITATIONS VARCHAR(1000),
    CEC_EVIDENCE_CHAIN VARCHAR(80),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 权益卡片变更历史(生成/冻结/解冻/注销/变更,权益可追溯)
CREATE TABLE IF NOT EXISTS IM_EQUITY_CARD_LOG (
    CEC_LOG_ID        VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_CARD_ID       VARCHAR(64),
    CEC_ACTION        VARCHAR(50),
    CEC_FROM_STATUS   VARCHAR(50),
    CEC_TO_STATUS     VARCHAR(50),
    CEC_REASON        VARCHAR(500),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 区块链存证记录(国密SM3指纹 + 上链回执,全节点留痕,prm-common 共享)
CREATE TABLE IF NOT EXISTS IM_DPR_EVIDENCE (
    CEC_EVIDENCE_ID   VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_BIZ_TYPE      VARCHAR(50),
    CEC_BIZ_ID        VARCHAR(64),
    CEC_SUMMARY       VARCHAR(500),
    CEC_SM3_HASH      VARCHAR(64),
    CEC_CHAIN_TX_HASH VARCHAR(80),
    CEC_BLOCK_HEIGHT  BIGINT,
    CEC_ANCHOR_STATUS VARCHAR(20),
    CEC_EVIDENCE_TIME TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS IM_CONFIRM_APPLY (
    CEC_APPLY_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_APPLY_NO      VARCHAR(64),
    CEC_ASSET_ID      VARCHAR(64)  NOT NULL,
    CEC_ASSET_NAME    VARCHAR(255) NOT NULL,
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_PURPOSE       VARCHAR(1000),
    CEC_RIGHT_HOLDER  VARCHAR(255),
    CEC_RESP_DEPT     VARCHAR(255),
    CEC_VALID_DATE    TIMESTAMP,
    CEC_STATUS        VARCHAR(50),
    CEC_REJECT_REASON VARCHAR(1000),
    CEC_CURRENT_NODE  INT,
    CEC_INVOLVES_THIRD_PARTY BOOLEAN,
    CEC_THIRD_PARTY_INFO VARCHAR(2000),
    CEC_PRIVACY_INFO         VARCHAR(2000),
    CEC_RECOGNITION_OPINION VARCHAR(2000),
    CEC_RE_CONFIRM    BOOLEAN,
    CEC_SOURCE_REF    VARCHAR(255),
    CEC_SOURCE_IDENT  VARCHAR(100),
    CEC_RELATION_IDENT VARCHAR(100),
    CEC_SYSTEM_OWNER  VARCHAR(100),
    CEC_CONTACT       VARCHAR(100),
    CEC_REGISTER_TYPE VARCHAR(20),
    CEC_APPLY_MODE    VARCHAR(20),
    CEC_REGULATED     VARCHAR(20),
    CEC_SOURCE_SUBJECT VARCHAR(255),
    CEC_SOURCE_LIMIT  VARCHAR(1000),
    CEC_RELATION_SUBJECT VARCHAR(1000),
    CEC_EQUITY_RISK   VARCHAR(1000),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 确权汇总表(表3 数据确权信息汇总表 / 表4 数据权益内部管理汇总表)
CREATE TABLE IF NOT EXISTS IM_CONFIRM_SUMMARY (
    CEC_SUMMARY_ID    VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_APPLY_ID      VARCHAR(64),
    CEC_SUMMARY_TYPE  VARCHAR(100),
    CEC_CONTENT       VARCHAR(2000),
    CEC_GENERATOR_ID  VARCHAR(64),
    CEC_GENERATE_TIME TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 权益卡片表
CREATE TABLE IF NOT EXISTS IM_EQUITY_CARD_INFO (
    CEC_CARD_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_CARD_NO       VARCHAR(64),
    CEC_APPLY_ID      VARCHAR(64),
    CEC_ASSET_ID      VARCHAR(64),
    CEC_ASSET_NAME    VARCHAR(255),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_RIGHT_OWNER   VARCHAR(255),
    CEC_RIGHT_SOURCE  VARCHAR(255),
    CEC_SCOPE         VARCHAR(100),
    CEC_VALID_DATE    TIMESTAMP,
    CEC_CARD_STATUS   VARCHAR(50),
    CEC_CONSOLIDATED_UNIT    VARCHAR(255),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 确权指引材料表
CREATE TABLE IF NOT EXISTS IM_CONFIRM_GUIDANCE (
    CEC_GUIDANCE_ID   VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_TITLE         VARCHAR(255) NOT NULL,
    CEC_GUIDANCE_TYPE VARCHAR(100),
    CEC_VERSION       VARCHAR(20),
    CEC_PUBLISHER     VARCHAR(100),
    CEC_PUBLISH_DATE  TIMESTAMP,
    CEC_FILE_URL      VARCHAR(500),
    CEC_FILE_NAME     VARCHAR(300),
    CEC_FILE_DATA     CLOB,
    CEC_IS_LATEST     BOOLEAN DEFAULT TRUE,
    CEC_CONTENT       CLOB,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 确权应交材料清单规则(可配置,单一真源:场景×触发条件 → 应交材料)
CREATE TABLE IF NOT EXISTS IM_CONFIRM_MATERIAL_RULE (
    CEC_RULE_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_SCENE         VARCHAR(50)  NOT NULL,
    CEC_TRIGGER_TYPE  VARCHAR(20)  NOT NULL,
    CEC_TRIGGER_CODE  VARCHAR(8),
    CEC_TRIGGER_LABEL VARCHAR(100),
    CEC_MATERIAL_NAME VARCHAR(300) NOT NULL,
    CEC_REQUIRED      VARCHAR(20),
    CEC_EVIDENCE_TYPE VARCHAR(20),
    CEC_DETAIL        VARCHAR(1000),
    CEC_TEMPLATE_REF  VARCHAR(64),
    CEC_SORT_NO       INT,
    CEC_ENABLED       BOOLEAN DEFAULT TRUE,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 确权申请材料表(含校验结果)
CREATE TABLE IF NOT EXISTS IM_CONFIRM_MATERIAL (
    CEC_MATERIAL_ID   VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_APPLY_ID      VARCHAR(64)  NOT NULL,
    CEC_MATERIAL_NAME VARCHAR(255) NOT NULL,
    CEC_MATERIAL_TYPE VARCHAR(100),
    CEC_FILE_URL      VARCHAR(500),
    CEC_OWNER         VARCHAR(100),
    CEC_UPLOAD_TIME   TIMESTAMP,
    CEC_CHECK_RESULT  VARCHAR(50),
    CEC_ABNORMAL_DESC VARCHAR(1000),
    CEC_FILE_NAME     VARCHAR(300),
    CEC_FILE_DATA     CLOB,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 确权权益证书表
CREATE TABLE IF NOT EXISTS IM_EQUITY_CERT (
    CEC_CERT_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_CERT_NO       VARCHAR(64),
    CEC_CARD_ID       VARCHAR(64),
    CEC_ISSUE_UNIT    VARCHAR(255),
    CEC_ISSUE_TIME    TIMESTAMP,
    CEC_CERT_STATUS   VARCHAR(50),
    CEC_TEMPLATE_ID   VARCHAR(64),
    CEC_TEMPLATE_NAME VARCHAR(255),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 确权权益证书模板表
CREATE TABLE IF NOT EXISTS IM_EQUITY_CERT_TEMPLATE (
    CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL,
    CEC_TEMPLATE_VERSION VARCHAR(20),
    CEC_RIGHT_TYPE       VARCHAR(100),
    CEC_TEMPLATE_CONTENT CLOB,
    CEC_TEMPLATE_STATUS  VARCHAR(50),
    CEC_FILE_NAME        VARCHAR(255),
    CEC_FILE_DATA        CLOB,
    CEC_PROVINCE_CODE    VARCHAR(32),
    CEC_BUREAU_CODE      VARCHAR(32),
    CEC_CREATOR_ID       VARCHAR(64),
    CEC_CREATE_TIME      TIMESTAMP,
    CEC_UPDATER_ID       VARCHAR(64),
    CEC_UPDATE_TIME      TIMESTAMP,
    CEC_DEL_FLAG         INT DEFAULT 0
);

-- 确权申请流转历史/进度通知(可研 -006 进度跟踪)
CREATE TABLE IF NOT EXISTS IM_CONFIRM_FLOW_LOG (
    CEC_LOG_ID         VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_APPLY_ID       VARCHAR(64),
    CEC_APPLY_NO       VARCHAR(64),
    CEC_FROM_STATUS    VARCHAR(50),
    CEC_TO_STATUS      VARCHAR(50),
    CEC_NODE           INT,
    CEC_NODE_NAME      VARCHAR(100),
    CEC_RESPONDER      VARCHAR(100),
    CEC_OPINION        VARCHAR(2000),
    CEC_NOTIFY_CONTENT VARCHAR(1000),
    CEC_PUSH_CHANNEL   VARCHAR(50),
    CEC_PROVINCE_CODE  VARCHAR(32),
    CEC_BUREAU_CODE    VARCHAR(32),
    CEC_CREATOR_ID     VARCHAR(64),
    CEC_CREATE_TIME    TIMESTAMP,
    CEC_UPDATER_ID     VARCHAR(64),
    CEC_UPDATE_TIME    TIMESTAMP,
    CEC_DEL_FLAG       INT DEFAULT 0
);

-- 确权申请-表级数据清单(对齐《数据确权信息汇总表》/补录工单 M02)
CREATE TABLE IF NOT EXISTS IM_CONFIRM_TABLE_ITEM (
    CEC_ITEM_ID       VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_APPLY_ID      VARCHAR(64),
    CEC_INSTANCE_NAME VARCHAR(120),
    CEC_SCHEMA_NAME   VARCHAR(120),
    CEC_TABLE_CODE    VARCHAR(150),
    CEC_TABLE_NAME    VARCHAR(200),
    CEC_TABLE_COMMENT VARCHAR(500),
    CEC_SECRET_LEVEL  VARCHAR(20),
    CEC_SOURCE_TYPE   VARCHAR(50),
    CEC_SOURCE_SUBJECT VARCHAR(200),
    CEC_SOURCE_DESC   VARCHAR(500),
    CEC_G_FLAG        VARCHAR(4),
    CEC_G_SUBJECT     VARCHAR(300),
    CEC_H_FLAG        VARCHAR(4),
    CEC_H_SUBJECT     VARCHAR(300),
    CEC_I_FLAG        VARCHAR(4),
    CEC_I_SUBJECT     VARCHAR(300),
    CEC_J_FLAG        VARCHAR(4),
    CEC_J_SUBJECT     VARCHAR(300),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 系统用户(内建认证+RBAC):密码 SM3 哈希;生产由 4A 统一身份,此表用于本地/演示登录
CREATE TABLE IF NOT EXISTS IM_SYS_USER (
    CEC_USER_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_USERNAME      VARCHAR(64)  NOT NULL,
    CEC_PASSWORD_HASH VARCHAR(128),
    CEC_REAL_NAME     VARCHAR(64),
    CEC_ROLE          VARCHAR(32),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_STATUS        VARCHAR(16)  DEFAULT '启用',
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 系统操作日志(系统管理:登录 + 用户管理类操作留痕,谁/动作/对象/结果/时间/IP)
CREATE TABLE IF NOT EXISTS IM_SYS_OPLOG (
    CEC_LOG_ID        VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_USER_ID       VARCHAR(64),
    CEC_USER_NAME     VARCHAR(64),
    CEC_ACTION        VARCHAR(50),
    CEC_TARGET        VARCHAR(255),
    CEC_DETAIL        VARCHAR(1000),
    CEC_IP            VARCHAR(64),
    CEC_RESULT        VARCHAR(20),
    CEC_CREATE_TIME   TIMESTAMP
);

-- 1.1.1.1#4 结构化模板对比日志
CREATE TABLE IF NOT EXISTS IM_AIT_TPL_COMPARE (
  CEC_TPL_CMP_ID     VARCHAR(64) NOT NULL PRIMARY KEY,
  CEC_MATERIAL_ID    VARCHAR(64),
  CEC_BATCH_NO       VARCHAR(64),
  CEC_TEMPLATE_NAME  VARCHAR(255),
  CEC_ROW_NO         INT,
  CEC_TPL_FIELD      VARCHAR(128),
  CEC_TPL_VALUE      VARCHAR(2000),
  CEC_MATERIAL_VALUE VARCHAR(2000),
  CEC_CONSISTENCY    VARCHAR(20),
  CEC_SOURCE_LOCATION VARCHAR(1000),
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    TIMESTAMP,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    TIMESTAMP,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0
);
