-- =====================================================================
-- 数据产权管理模块 (IM-DAM-DPR) · 达梦 DM8 库表 DDL
-- 数据资产管理平台 V3.6 · 中国南方电网
-- 由 MySQL schema 转换: DATETIME→TIMESTAMP, TEXT/LONGTEXT→CLOB, TINYINT(1)→SMALLINT
-- 共 60 张表(含 IM_CONFIRM_TABLE_ITEM/M02、IM_SYS_USER、IM_SYS_OPLOG 及智能确权辅助工具九大组 18 张 IM_AIT_* 新表)
-- 字段前缀 CEC_ 沿用平台规范; CEC_DEL_FLAG 逻辑删除(0=正常,1=已删)
-- 执行前先跑 01_create_tablespace.sql 建表空间与用户
-- 执行:  disql PRM_DPR/PRM_DPR2024!@localhost:5236 @02_schema_dm.sql
-- =====================================================================

-- =====================================================================
-- 公共 / 共享
-- =====================================================================

-- 区块链存证记录(国密SM3指纹 + 上链回执,确权制卡/授权发证/协议/变更/熔断节点留痕)
CREATE TABLE IM_DPR_EVIDENCE (
  CEC_EVIDENCE_ID   VARCHAR(64) NOT NULL,
  CEC_BIZ_TYPE      VARCHAR(50),
  CEC_BIZ_ID        VARCHAR(64),
  CEC_SUMMARY       VARCHAR(500),
  CEC_SM3_HASH      VARCHAR(64),
  CEC_CHAIN_TX_HASH VARCHAR(80),
  CEC_BLOCK_HEIGHT  BIGINT,
  CEC_ANCHOR_STATUS VARCHAR(20),
  CEC_EVIDENCE_TIME TIMESTAMP,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_EVIDENCE_ID)
);
COMMENT ON TABLE IM_DPR_EVIDENCE IS '区块链存证记录';
COMMENT ON COLUMN IM_DPR_EVIDENCE.CEC_EVIDENCE_ID IS '存证ID';
COMMENT ON COLUMN IM_DPR_EVIDENCE.CEC_BIZ_TYPE IS '业务类型(确权制卡/授权发证/熔断处置...)';
COMMENT ON COLUMN IM_DPR_EVIDENCE.CEC_BIZ_ID IS '业务ID';
COMMENT ON COLUMN IM_DPR_EVIDENCE.CEC_SUMMARY IS '存证摘要';
COMMENT ON COLUMN IM_DPR_EVIDENCE.CEC_SM3_HASH IS 'SM3 指纹';
COMMENT ON COLUMN IM_DPR_EVIDENCE.CEC_CHAIN_TX_HASH IS '链上交易哈希';
COMMENT ON COLUMN IM_DPR_EVIDENCE.CEC_BLOCK_HEIGHT IS '区块高度';
COMMENT ON COLUMN IM_DPR_EVIDENCE.CEC_ANCHOR_STATUS IS '上链状态';
COMMENT ON COLUMN IM_DPR_EVIDENCE.CEC_EVIDENCE_TIME IS '存证时间';
CREATE INDEX IDX_EVID_BIZ ON IM_DPR_EVIDENCE (CEC_BIZ_TYPE, CEC_BIZ_ID);

-- =====================================================================
-- F-01 产权信息管理 (dpr-ledger-service, 9101)
-- =====================================================================

-- 数据资产信息表(由数据资产管理平台目录同步,确权/树/概览的底座)
CREATE TABLE IM_DPM_DATA_ASSET_INFO (
  CEC_ASSET_ID         VARCHAR(64)  NOT NULL,
  CEC_ASSET_NAME       VARCHAR(255) NOT NULL,
  CEC_ASSET_TYPE       VARCHAR(100),
  CEC_SOURCE_OF_ASSETS VARCHAR(255),
  CEC_ASSET_STATUS     VARCHAR(50),
  CEC_ASSET_OWNER      VARCHAR(100),
  CEC_SUBSIDIARY_NAME  VARCHAR(255),
  CEC_SYSTEM_NAME      VARCHAR(255),
  CEC_SCHEMA_NAME      VARCHAR(255),
  CEC_SECURITY_LEVEL   VARCHAR(50),
  CEC_RESP_DEPT        VARCHAR(255),
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      TIMESTAMP,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      TIMESTAMP,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ASSET_ID)
);
COMMENT ON TABLE IM_DPM_DATA_ASSET_INFO IS '数据资产信息';
COMMENT ON COLUMN IM_DPM_DATA_ASSET_INFO.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_DPM_DATA_ASSET_INFO.CEC_ASSET_NAME IS '资产名称';
COMMENT ON COLUMN IM_DPM_DATA_ASSET_INFO.CEC_ASSET_TYPE IS '资产类型';
COMMENT ON COLUMN IM_DPM_DATA_ASSET_INFO.CEC_SOURCE_OF_ASSETS IS '资产来源';
COMMENT ON COLUMN IM_DPM_DATA_ASSET_INFO.CEC_ASSET_STATUS IS '资产状态';
COMMENT ON COLUMN IM_DPM_DATA_ASSET_INFO.CEC_ASSET_OWNER IS '资产归属';
COMMENT ON COLUMN IM_DPM_DATA_ASSET_INFO.CEC_SUBSIDIARY_NAME IS '子公司';
COMMENT ON COLUMN IM_DPM_DATA_ASSET_INFO.CEC_SYSTEM_NAME IS '系统名称';
COMMENT ON COLUMN IM_DPM_DATA_ASSET_INFO.CEC_SCHEMA_NAME IS '模式名称';
COMMENT ON COLUMN IM_DPM_DATA_ASSET_INFO.CEC_SECURITY_LEVEL IS '安全等级';
COMMENT ON COLUMN IM_DPM_DATA_ASSET_INFO.CEC_RESP_DEPT IS '责任部门';
CREATE INDEX IDX_ASSET_SUB ON IM_DPM_DATA_ASSET_INFO (CEC_SUBSIDIARY_NAME);

-- 产权档案表(一数一档)
CREATE TABLE IM_PROPERTY_ARCHIVE (
  CEC_ARCHIVE_ID     VARCHAR(64)  NOT NULL,
  CEC_ASSET_ID       VARCHAR(64)  NOT NULL,
  CEC_ASSET_NAME     VARCHAR(255) NOT NULL,
  CEC_RIGHT_TYPE     VARCHAR(255),
  CEC_RIGHT_SUBJECT  VARCHAR(255),
  CEC_RIGHT_OBJECT   VARCHAR(255),
  CEC_ACQUIRE_MODE   VARCHAR(100),
  CEC_USE_SCOPE      VARCHAR(1000),
  CEC_RESP_DEPT      VARCHAR(255),
  CEC_VALID_DATE     TIMESTAMP,
  CEC_CONFIRM_STATUS VARCHAR(50),
  CEC_CONFIRM_DETAIL VARCHAR(255),
  CEC_AUTH_STATUS    VARCHAR(50),
  CEC_EQUITY_CARD_ID VARCHAR(64),
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    TIMESTAMP,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    TIMESTAMP,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ARCHIVE_ID)
);
COMMENT ON TABLE IM_PROPERTY_ARCHIVE IS '产权档案(一数一档)';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_ARCHIVE_ID IS '档案ID';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_ASSET_NAME IS '资产名称';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_RIGHT_TYPE IS '产权类型(三权分置,可多值顿号拼接:持有权/加工使用权/产品经营权)';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_RIGHT_SUBJECT IS '权利主体';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_RIGHT_OBJECT IS '权利客体';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_ACQUIRE_MODE IS '取得方式';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_USE_SCOPE IS '使用范围';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_RESP_DEPT IS '责任部门';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_VALID_DATE IS '有效期';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_CONFIRM_STATUS IS '确权状态(聚合:未确权/部分确权/已确权)';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_CONFIRM_DETAIL IS '按权确权明细(持有权:已确权;使用权:未确权;...)';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_AUTH_STATUS IS '授权状态';
COMMENT ON COLUMN IM_PROPERTY_ARCHIVE.CEC_EQUITY_CARD_ID IS '权益卡片ID';
CREATE INDEX IDX_ARC_ASSET ON IM_PROPERTY_ARCHIVE (CEC_ASSET_ID);

-- 产权变更记录表(由确权/授权审批流事件自动生成,防篡改证据链)
CREATE TABLE IM_PROPERTY_CHANGE_RECORD (
  CEC_CHANGE_ID     VARCHAR(64)  NOT NULL,
  CEC_ASSET_ID      VARCHAR(64)  NOT NULL,
  CEC_CHANGE_TYPE   VARCHAR(100) NOT NULL,
  CEC_FIELD_NAME    VARCHAR(100),
  CEC_BEFORE_VALUE  VARCHAR(2000),
  CEC_AFTER_VALUE   VARCHAR(2000),
  CEC_CHANGE_REASON VARCHAR(1000),
  CEC_SOURCE_FLOW   VARCHAR(100),
  CEC_SOURCE_TICKET VARCHAR(64),
  CEC_OPERATOR_ID   VARCHAR(64),
  CEC_CHANGE_TIME   TIMESTAMP,
  CEC_CHAIN_HASH    VARCHAR(128),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CHANGE_ID)
);
COMMENT ON TABLE IM_PROPERTY_CHANGE_RECORD IS '产权变更记录(防篡改留痕)';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_CHANGE_ID IS '变更ID';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_CHANGE_TYPE IS '变更类型';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_FIELD_NAME IS '变更字段';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_BEFORE_VALUE IS '变更前';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_AFTER_VALUE IS '变更后';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_CHANGE_REASON IS '变更原因';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_SOURCE_FLOW IS '来源流程';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_SOURCE_TICKET IS '来源单号';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_OPERATOR_ID IS '操作人';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_CHANGE_TIME IS '变更时间';
COMMENT ON COLUMN IM_PROPERTY_CHANGE_RECORD.CEC_CHAIN_HASH IS '上链哈希';
CREATE INDEX IDX_CHG_ASSET ON IM_PROPERTY_CHANGE_RECORD (CEC_ASSET_ID);

-- 监测规则配置表
CREATE TABLE IM_MONITOR_RULE (
  CEC_RULE_ID        VARCHAR(64)  NOT NULL,
  CEC_RULE_NAME      VARCHAR(255) NOT NULL,
  CEC_RULE_CATEGORY  VARCHAR(100),
  CEC_MONITOR_TARGET VARCHAR(255),
  CEC_TRIGGER_COND   CLOB,
  CEC_THRESHOLD      VARCHAR(500),
  CEC_PRIORITY       VARCHAR(20),
  CEC_NOTIFY_TARGET  VARCHAR(500),
  CEC_NOTIFY_CHANNEL VARCHAR(200),
  CEC_RULE_VERSION   VARCHAR(20),
  CEC_EFFECT_STATUS  VARCHAR(20),
  CEC_CIRCUIT_BREAK  INT DEFAULT 0,
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    TIMESTAMP,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    TIMESTAMP,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RULE_ID)
);
COMMENT ON TABLE IM_MONITOR_RULE IS '监测规则配置';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_RULE_ID IS '规则ID';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_RULE_NAME IS '规则名称';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_RULE_CATEGORY IS '规则类别';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_MONITOR_TARGET IS '监测对象';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_TRIGGER_COND IS '触发条件';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_THRESHOLD IS '阈值';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_PRIORITY IS '优先级';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_NOTIFY_TARGET IS '通知对象';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_NOTIFY_CHANNEL IS '通知方式(站内信/邮件/短信/eLink,逗号分隔)';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_RULE_VERSION IS '版本';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_EFFECT_STATUS IS '生效状态';
COMMENT ON COLUMN IM_MONITOR_RULE.CEC_CIRCUIT_BREAK IS '是否联动熔断';

-- 风险预警记录表
CREATE TABLE IM_ALERT_RECORD (
  CEC_ALERT_ID         VARCHAR(64)  NOT NULL,
  CEC_RULE_ID          VARCHAR(64),
  CEC_SOURCE           VARCHAR(50),
  CEC_ASSET_ID         VARCHAR(64),
  CEC_ALERT_LEVEL      VARCHAR(20)  NOT NULL,
  CEC_TRIGGER_COND     VARCHAR(1000),
  CEC_ABNORMAL_DESC    VARCHAR(2000),
  CEC_ALERT_TIME       TIMESTAMP,
  CEC_DISPOSE_STATUS   VARCHAR(50)  NOT NULL,
  CEC_DISPOSE_FEEDBACK VARCHAR(2000),
  CEC_RESPONDER_ID     VARCHAR(64),
  CEC_CLOSE_TIME       TIMESTAMP,
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      TIMESTAMP,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      TIMESTAMP,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ALERT_ID)
);
COMMENT ON TABLE IM_ALERT_RECORD IS '风险预警记录';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_ALERT_ID IS '预警ID';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_RULE_ID IS '规则ID';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_SOURCE IS '来源';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_ALERT_LEVEL IS '级别(紧急/重要/普通)';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_TRIGGER_COND IS '触发条件';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_ABNORMAL_DESC IS '异常描述';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_ALERT_TIME IS '预警时间';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_DISPOSE_STATUS IS '处置状态(待处理/处理中/已关闭)';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_DISPOSE_FEEDBACK IS '处置反馈';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_RESPONDER_ID IS '处置人';
COMMENT ON COLUMN IM_ALERT_RECORD.CEC_CLOSE_TIME IS '关闭时间';
CREATE INDEX IDX_ALERT_ASSET ON IM_ALERT_RECORD (CEC_ASSET_ID);
CREATE INDEX IDX_ALERT_STATUS ON IM_ALERT_RECORD (CEC_DISPOSE_STATUS);

-- 风险预警定向通知表(可研 -006 推送/通知责任人)
CREATE TABLE IM_ALERT_NOTIFICATION (
  CEC_NOTIFY_ID      VARCHAR(64)  NOT NULL,
  CEC_ALERT_ID       VARCHAR(64),
  CEC_ASSET_ID       VARCHAR(64),
  CEC_RECIPIENT      VARCHAR(200),
  CEC_CHANNEL        VARCHAR(200),
  CEC_TITLE          VARCHAR(500),
  CEC_CONTENT        VARCHAR(2000),
  CEC_ALERT_LEVEL    VARCHAR(20),
  CEC_READ_STATUS    VARCHAR(20),
  CEC_PUSH_TIME      TIMESTAMP,
  CEC_READ_TIME      TIMESTAMP,
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    TIMESTAMP,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    TIMESTAMP,
  CEC_DEL_FLAG       INT DEFAULT 0,
  PRIMARY KEY (CEC_NOTIFY_ID)
);
COMMENT ON TABLE IM_ALERT_NOTIFICATION IS '风险预警定向通知';
COMMENT ON COLUMN IM_ALERT_NOTIFICATION.CEC_NOTIFY_ID IS '通知ID';
COMMENT ON COLUMN IM_ALERT_NOTIFICATION.CEC_ALERT_ID IS '关联预警ID';
COMMENT ON COLUMN IM_ALERT_NOTIFICATION.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_ALERT_NOTIFICATION.CEC_RECIPIENT IS '接收方(责任人/部门)';
COMMENT ON COLUMN IM_ALERT_NOTIFICATION.CEC_CHANNEL IS '推送渠道(站内信/邮件/短信/eLink)';
COMMENT ON COLUMN IM_ALERT_NOTIFICATION.CEC_TITLE IS '标题';
COMMENT ON COLUMN IM_ALERT_NOTIFICATION.CEC_CONTENT IS '内容';
COMMENT ON COLUMN IM_ALERT_NOTIFICATION.CEC_ALERT_LEVEL IS '级别';
COMMENT ON COLUMN IM_ALERT_NOTIFICATION.CEC_READ_STATUS IS '已读状态(未读/已读)';
COMMENT ON COLUMN IM_ALERT_NOTIFICATION.CEC_PUSH_TIME IS '推送时间';
COMMENT ON COLUMN IM_ALERT_NOTIFICATION.CEC_READ_TIME IS '已读时间';
CREATE INDEX IDX_NOTIFY_RECIPIENT ON IM_ALERT_NOTIFICATION (CEC_RECIPIENT, CEC_READ_STATUS);

-- 合规检查结果表
CREATE TABLE IM_COMPLIANCE_RESULT (
  CEC_CHECK_ID       VARCHAR(64)  NOT NULL,
  CEC_ASSET_ID       VARCHAR(64),
  CEC_RULE_ID        VARCHAR(64),
  CEC_CHECK_RESULT   VARCHAR(50),
  CEC_PROBLEM_DESC   VARCHAR(2000),
  CEC_SUGGESTION     VARCHAR(2000),
  CEC_REPORT_URL     VARCHAR(500),
  CEC_CHECK_TIME     TIMESTAMP,
  CEC_DISPOSE_STATUS VARCHAR(50),
  CEC_CHECK_DIM      VARCHAR(50),
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    TIMESTAMP,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    TIMESTAMP,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CHECK_ID)
);
COMMENT ON TABLE IM_COMPLIANCE_RESULT IS '合规检查结果';
COMMENT ON COLUMN IM_COMPLIANCE_RESULT.CEC_CHECK_ID IS '检查ID';
COMMENT ON COLUMN IM_COMPLIANCE_RESULT.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_COMPLIANCE_RESULT.CEC_RULE_ID IS '规则ID';
COMMENT ON COLUMN IM_COMPLIANCE_RESULT.CEC_CHECK_RESULT IS '检查结果';
COMMENT ON COLUMN IM_COMPLIANCE_RESULT.CEC_PROBLEM_DESC IS '问题描述';
COMMENT ON COLUMN IM_COMPLIANCE_RESULT.CEC_SUGGESTION IS '整改建议';
COMMENT ON COLUMN IM_COMPLIANCE_RESULT.CEC_REPORT_URL IS '报告地址';
COMMENT ON COLUMN IM_COMPLIANCE_RESULT.CEC_CHECK_TIME IS '检查时间';
COMMENT ON COLUMN IM_COMPLIANCE_RESULT.CEC_DISPOSE_STATUS IS '处置状态';
COMMENT ON COLUMN IM_COMPLIANCE_RESULT.CEC_CHECK_DIM IS '检查维度(有效期/权限范围/申请材料/协议内容)';
CREATE INDEX IDX_CHK_ASSET ON IM_COMPLIANCE_RESULT (CEC_ASSET_ID);

-- =====================================================================
-- F-02 数据确权管理 (dpr-confirm-service, 9102)
-- =====================================================================

-- 数据确权申请单表
CREATE TABLE IM_CONFIRM_APPLY (
  CEC_APPLY_ID             VARCHAR(64)  NOT NULL,
  CEC_APPLY_NO             VARCHAR(64),
  CEC_ASSET_ID             VARCHAR(64)  NOT NULL,
  CEC_ASSET_NAME           VARCHAR(255) NOT NULL,
  CEC_RIGHT_TYPE           VARCHAR(100),
  CEC_PURPOSE              VARCHAR(1000),
  CEC_RIGHT_HOLDER         VARCHAR(255),
  CEC_RESP_DEPT            VARCHAR(255),
  CEC_VALID_DATE           TIMESTAMP,
  CEC_STATUS               VARCHAR(50),
  CEC_REJECT_REASON        VARCHAR(1000),
  CEC_CURRENT_NODE         INT,
  CEC_INVOLVES_THIRD_PARTY SMALLINT,
  CEC_THIRD_PARTY_INFO     VARCHAR(2000),
  CEC_RECOGNITION_OPINION  VARCHAR(2000),
  CEC_RE_CONFIRM           SMALLINT,
  CEC_SOURCE_REF           VARCHAR(255),
  CEC_SOURCE_IDENT         VARCHAR(100),
  CEC_RELATION_IDENT       VARCHAR(100),
  CEC_SYSTEM_OWNER         VARCHAR(100),
  CEC_CONTACT              VARCHAR(100),
  CEC_REGISTER_TYPE        VARCHAR(20),
  CEC_APPLY_MODE           VARCHAR(20),
  CEC_REGULATED            VARCHAR(20),
  CEC_SOURCE_SUBJECT       VARCHAR(255),
  CEC_SOURCE_LIMIT         VARCHAR(1000),
  CEC_RELATION_SUBJECT     VARCHAR(1000),
  CEC_EQUITY_RISK          VARCHAR(1000),
  CEC_PROVINCE_CODE        VARCHAR(32),
  CEC_BUREAU_CODE          VARCHAR(32),
  CEC_CREATOR_ID           VARCHAR(64),
  CEC_CREATE_TIME          TIMESTAMP,
  CEC_UPDATER_ID           VARCHAR(64),
  CEC_UPDATE_TIME          TIMESTAMP,
  CEC_DEL_FLAG             INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_APPLY_ID)
);
COMMENT ON TABLE IM_CONFIRM_APPLY IS '数据确权申请单';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_APPLY_NO IS '申请编号';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_ASSET_NAME IS '资产名称';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_RIGHT_TYPE IS '产权类型';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_PURPOSE IS '确权用途';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_RIGHT_HOLDER IS '权属主体';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_RESP_DEPT IS '责任部门';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_VALID_DATE IS '有效期';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_STATUS IS '状态机状态';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_REJECT_REASON IS '驳回原因';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_CURRENT_NODE IS '当前节点(进度%)';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_INVOLVES_THIRD_PARTY IS '是否涉第三方';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_THIRD_PARTY_INFO IS '第三方信息';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_RECOGNITION_OPINION IS '认定意见';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_RE_CONFIRM IS '是否重确权';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_SOURCE_REF IS '来源引用';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_SOURCE_IDENT IS '来源权益识别(A-F)';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_RELATION_IDENT IS '信息关联权益识别(G-J)';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_SYSTEM_OWNER IS '系统负责人姓名(附录F表1)';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_CONTACT IS '系统负责人联系方式(附录F表1)';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_REGISTER_TYPE IS '登记类型(初始确权/确权变更,附录F表1)';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_APPLY_MODE IS '申请模式(常规/一事一议)';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_REGULATED IS '管制属性(管制业务/非管制)';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_SOURCE_SUBJECT IS '表2:来源主体名称';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_SOURCE_LIMIT IS '表2:来源权益限制摘要';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_RELATION_SUBJECT IS '表2:信息识别关联主体说明';
COMMENT ON COLUMN IM_CONFIRM_APPLY.CEC_EQUITY_RISK IS '表2:权益风险说明';
CREATE INDEX IDX_CA_ASSET ON IM_CONFIRM_APPLY (CEC_ASSET_ID);
CREATE INDEX IDX_CA_STATUS ON IM_CONFIRM_APPLY (CEC_STATUS);

-- 确权指引材料表
CREATE TABLE IM_CONFIRM_GUIDANCE (
  CEC_GUIDANCE_ID   VARCHAR(64)  NOT NULL,
  CEC_TITLE         VARCHAR(255) NOT NULL,
  CEC_GUIDANCE_TYPE VARCHAR(100),
  CEC_VERSION       VARCHAR(20),
  CEC_PUBLISHER     VARCHAR(100),
  CEC_PUBLISH_DATE  TIMESTAMP,
  CEC_FILE_URL      VARCHAR(500),
  CEC_FILE_NAME     VARCHAR(300),
  CEC_FILE_DATA     CLOB,
  CEC_IS_LATEST     SMALLINT DEFAULT 1,
  CEC_CONTENT       CLOB,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_GUIDANCE_ID)
);
COMMENT ON TABLE IM_CONFIRM_GUIDANCE IS '确权指引材料';
COMMENT ON COLUMN IM_CONFIRM_GUIDANCE.CEC_GUIDANCE_ID IS '指引ID';
COMMENT ON COLUMN IM_CONFIRM_GUIDANCE.CEC_TITLE IS '标题';
COMMENT ON COLUMN IM_CONFIRM_GUIDANCE.CEC_GUIDANCE_TYPE IS '指引类型';
COMMENT ON COLUMN IM_CONFIRM_GUIDANCE.CEC_VERSION IS '版本';
COMMENT ON COLUMN IM_CONFIRM_GUIDANCE.CEC_PUBLISHER IS '发布单位';
COMMENT ON COLUMN IM_CONFIRM_GUIDANCE.CEC_PUBLISH_DATE IS '发布日期';
COMMENT ON COLUMN IM_CONFIRM_GUIDANCE.CEC_FILE_URL IS '附件地址';
COMMENT ON COLUMN IM_CONFIRM_GUIDANCE.CEC_FILE_NAME IS '原件文件名';
COMMENT ON COLUMN IM_CONFIRM_GUIDANCE.CEC_FILE_DATA IS '原件Base64';
COMMENT ON COLUMN IM_CONFIRM_GUIDANCE.CEC_IS_LATEST IS '是否最新版本';
COMMENT ON COLUMN IM_CONFIRM_GUIDANCE.CEC_CONTENT IS '正文';

-- 确权申请材料表(含校验结果)
CREATE TABLE IM_CONFIRM_MATERIAL (
  CEC_MATERIAL_ID   VARCHAR(64)  NOT NULL,
  CEC_APPLY_ID      VARCHAR(64)  NOT NULL,
  CEC_MATERIAL_NAME VARCHAR(255) NOT NULL,
  CEC_MATERIAL_TYPE VARCHAR(100),
  CEC_FILE_URL      VARCHAR(500),
  CEC_OWNER         VARCHAR(100),
  CEC_UPLOAD_TIME   TIMESTAMP,
  CEC_CHECK_RESULT  VARCHAR(50),
  CEC_ABNORMAL_DESC VARCHAR(1000),
  CEC_FILE_NAME     VARCHAR(300),
  CEC_FILE_DATA     CLOB,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_MATERIAL_ID)
);
COMMENT ON TABLE IM_CONFIRM_MATERIAL IS '确权申请材料';
COMMENT ON COLUMN IM_CONFIRM_MATERIAL.CEC_MATERIAL_ID IS '材料ID';
COMMENT ON COLUMN IM_CONFIRM_MATERIAL.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_CONFIRM_MATERIAL.CEC_MATERIAL_NAME IS '材料名称';
COMMENT ON COLUMN IM_CONFIRM_MATERIAL.CEC_MATERIAL_TYPE IS '材料类型';
COMMENT ON COLUMN IM_CONFIRM_MATERIAL.CEC_FILE_URL IS '文件地址';
COMMENT ON COLUMN IM_CONFIRM_MATERIAL.CEC_OWNER IS '归属';
COMMENT ON COLUMN IM_CONFIRM_MATERIAL.CEC_UPLOAD_TIME IS '上传时间';
COMMENT ON COLUMN IM_CONFIRM_MATERIAL.CEC_CHECK_RESULT IS '校验结果';
COMMENT ON COLUMN IM_CONFIRM_MATERIAL.CEC_ABNORMAL_DESC IS '异常描述';
COMMENT ON COLUMN IM_CONFIRM_MATERIAL.CEC_FILE_NAME IS '原件文件名';
COMMENT ON COLUMN IM_CONFIRM_MATERIAL.CEC_FILE_DATA IS '原件Base64';
CREATE INDEX IDX_CM_APPLY ON IM_CONFIRM_MATERIAL (CEC_APPLY_ID);

-- 确权申请流转历史/进度通知(可研 -006 进度跟踪)
CREATE TABLE IM_CONFIRM_FLOW_LOG (
  CEC_LOG_ID         VARCHAR(64)  NOT NULL,
  CEC_APPLY_ID       VARCHAR(64),
  CEC_APPLY_NO       VARCHAR(64),
  CEC_FROM_STATUS    VARCHAR(50),
  CEC_TO_STATUS      VARCHAR(50),
  CEC_NODE           INT,
  CEC_NODE_NAME      VARCHAR(100),
  CEC_RESPONDER      VARCHAR(100),
  CEC_OPINION        VARCHAR(2000),
  CEC_NOTIFY_CONTENT VARCHAR(1000),
  CEC_PUSH_CHANNEL   VARCHAR(50),
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    TIMESTAMP,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    TIMESTAMP,
  CEC_DEL_FLAG       INT DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
);
COMMENT ON TABLE IM_CONFIRM_FLOW_LOG IS '确权申请流转历史/进度通知';
COMMENT ON COLUMN IM_CONFIRM_FLOW_LOG.CEC_LOG_ID IS '日志ID';
COMMENT ON COLUMN IM_CONFIRM_FLOW_LOG.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_CONFIRM_FLOW_LOG.CEC_APPLY_NO IS '申请编号';
COMMENT ON COLUMN IM_CONFIRM_FLOW_LOG.CEC_FROM_STATUS IS '原状态';
COMMENT ON COLUMN IM_CONFIRM_FLOW_LOG.CEC_TO_STATUS IS '新状态';
COMMENT ON COLUMN IM_CONFIRM_FLOW_LOG.CEC_NODE IS '节点编号';
COMMENT ON COLUMN IM_CONFIRM_FLOW_LOG.CEC_NODE_NAME IS '节点名称';
COMMENT ON COLUMN IM_CONFIRM_FLOW_LOG.CEC_RESPONDER IS '责任人';
COMMENT ON COLUMN IM_CONFIRM_FLOW_LOG.CEC_OPINION IS '审批意见';
COMMENT ON COLUMN IM_CONFIRM_FLOW_LOG.CEC_NOTIFY_CONTENT IS '进度通知文案';
COMMENT ON COLUMN IM_CONFIRM_FLOW_LOG.CEC_PUSH_CHANNEL IS '推送渠道';
CREATE INDEX IDX_FLOW_APPLY ON IM_CONFIRM_FLOW_LOG (CEC_APPLY_ID);

-- 确权汇总表(表3 数据确权信息汇总表 / 表4 数据权益内部管理汇总表)
CREATE TABLE IM_CONFIRM_SUMMARY (
  CEC_SUMMARY_ID    VARCHAR(64)  NOT NULL,
  CEC_APPLY_ID      VARCHAR(64),
  CEC_SUMMARY_TYPE  VARCHAR(100),
  CEC_CONTENT       VARCHAR(2000),
  CEC_GENERATOR_ID  VARCHAR(64),
  CEC_GENERATE_TIME TIMESTAMP,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_SUMMARY_ID)
);
COMMENT ON TABLE IM_CONFIRM_SUMMARY IS '确权汇总表(表3/表4)';
COMMENT ON COLUMN IM_CONFIRM_SUMMARY.CEC_SUMMARY_ID IS '汇总ID';
COMMENT ON COLUMN IM_CONFIRM_SUMMARY.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_CONFIRM_SUMMARY.CEC_SUMMARY_TYPE IS '汇总类型(表3/表4)';
COMMENT ON COLUMN IM_CONFIRM_SUMMARY.CEC_CONTENT IS '汇总内容';
COMMENT ON COLUMN IM_CONFIRM_SUMMARY.CEC_GENERATOR_ID IS '生成人';
COMMENT ON COLUMN IM_CONFIRM_SUMMARY.CEC_GENERATE_TIME IS '生成时间';
CREATE INDEX IDX_SM_APPLY ON IM_CONFIRM_SUMMARY (CEC_APPLY_ID);

-- 权益卡片表
CREATE TABLE IM_EQUITY_CARD_INFO (
  CEC_CARD_ID       VARCHAR(64)  NOT NULL,
  CEC_CARD_NO       VARCHAR(64),
  CEC_APPLY_ID      VARCHAR(64),
  CEC_ASSET_ID      VARCHAR(64),
  CEC_ASSET_NAME    VARCHAR(255),
  CEC_RIGHT_TYPE    VARCHAR(100),
  CEC_RIGHT_OWNER   VARCHAR(255),
  CEC_RIGHT_SOURCE  VARCHAR(255),
  CEC_SCOPE         VARCHAR(100),
  CEC_VALID_DATE    TIMESTAMP,
  CEC_CARD_STATUS   VARCHAR(50),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CARD_ID)
);
COMMENT ON TABLE IM_EQUITY_CARD_INFO IS '权益卡片';
COMMENT ON COLUMN IM_EQUITY_CARD_INFO.CEC_CARD_ID IS '卡片ID';
COMMENT ON COLUMN IM_EQUITY_CARD_INFO.CEC_CARD_NO IS '卡片编号';
COMMENT ON COLUMN IM_EQUITY_CARD_INFO.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_EQUITY_CARD_INFO.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_EQUITY_CARD_INFO.CEC_ASSET_NAME IS '资产名称';
COMMENT ON COLUMN IM_EQUITY_CARD_INFO.CEC_RIGHT_TYPE IS '产权类型';
COMMENT ON COLUMN IM_EQUITY_CARD_INFO.CEC_RIGHT_OWNER IS '权属主体';
COMMENT ON COLUMN IM_EQUITY_CARD_INFO.CEC_RIGHT_SOURCE IS '权利来源';
COMMENT ON COLUMN IM_EQUITY_CARD_INFO.CEC_SCOPE IS '确权范围(全字段/约定字段),授权边界依据';
COMMENT ON COLUMN IM_EQUITY_CARD_INFO.CEC_VALID_DATE IS '有效期';
COMMENT ON COLUMN IM_EQUITY_CARD_INFO.CEC_CARD_STATUS IS '卡片状态(正常/冻结/失效)';
CREATE INDEX IDX_CARD_ASSET ON IM_EQUITY_CARD_INFO (CEC_ASSET_ID);

-- 权益卡片变更历史(生成/冻结/解冻/注销/变更)
CREATE TABLE IM_EQUITY_CARD_LOG (
  CEC_LOG_ID        VARCHAR(64) NOT NULL,
  CEC_CARD_ID       VARCHAR(64),
  CEC_ACTION        VARCHAR(50),
  CEC_FROM_STATUS   VARCHAR(50),
  CEC_TO_STATUS     VARCHAR(50),
  CEC_REASON        VARCHAR(500),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
);
COMMENT ON TABLE IM_EQUITY_CARD_LOG IS '权益卡片变更历史';
COMMENT ON COLUMN IM_EQUITY_CARD_LOG.CEC_LOG_ID IS '日志ID';
COMMENT ON COLUMN IM_EQUITY_CARD_LOG.CEC_CARD_ID IS '卡片ID';
COMMENT ON COLUMN IM_EQUITY_CARD_LOG.CEC_ACTION IS '动作';
COMMENT ON COLUMN IM_EQUITY_CARD_LOG.CEC_FROM_STATUS IS '原状态';
COMMENT ON COLUMN IM_EQUITY_CARD_LOG.CEC_TO_STATUS IS '新状态';
COMMENT ON COLUMN IM_EQUITY_CARD_LOG.CEC_REASON IS '原因';
CREATE INDEX IDX_CL_CARD ON IM_EQUITY_CARD_LOG (CEC_CARD_ID);

-- 确权权益证书表
CREATE TABLE IM_EQUITY_CERT (
  CEC_CERT_ID       VARCHAR(64)  NOT NULL,
  CEC_CERT_NO       VARCHAR(64),
  CEC_CARD_ID       VARCHAR(64),
  CEC_ISSUE_UNIT    VARCHAR(255),
  CEC_ISSUE_TIME    TIMESTAMP,
  CEC_CERT_STATUS   VARCHAR(50),
  CEC_TEMPLATE_ID   VARCHAR(64),
  CEC_TEMPLATE_NAME VARCHAR(255),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CERT_ID)
);
COMMENT ON TABLE IM_EQUITY_CERT IS '确权权益证书';
COMMENT ON COLUMN IM_EQUITY_CERT.CEC_CERT_ID IS '证书ID';
COMMENT ON COLUMN IM_EQUITY_CERT.CEC_CERT_NO IS '证书编号';
COMMENT ON COLUMN IM_EQUITY_CERT.CEC_CARD_ID IS '卡片ID';
COMMENT ON COLUMN IM_EQUITY_CERT.CEC_ISSUE_UNIT IS '发证单位';
COMMENT ON COLUMN IM_EQUITY_CERT.CEC_ISSUE_TIME IS '发证时间';
COMMENT ON COLUMN IM_EQUITY_CERT.CEC_CERT_STATUS IS '证书状态';
COMMENT ON COLUMN IM_EQUITY_CERT.CEC_TEMPLATE_ID IS '模板ID';
COMMENT ON COLUMN IM_EQUITY_CERT.CEC_TEMPLATE_NAME IS '模板名称';
CREATE INDEX IDX_QCERT_CARD ON IM_EQUITY_CERT (CEC_CARD_ID);

-- 确权权益证书模板表
CREATE TABLE IM_EQUITY_CERT_TEMPLATE (
  CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL,
  CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL,
  CEC_TEMPLATE_VERSION VARCHAR(20),
  CEC_RIGHT_TYPE       VARCHAR(100),
  CEC_TEMPLATE_CONTENT CLOB,
  CEC_TEMPLATE_STATUS  VARCHAR(50),
  CEC_FILE_NAME        VARCHAR(255),
  CEC_FILE_DATA        CLOB,
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      TIMESTAMP,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      TIMESTAMP,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TEMPLATE_ID)
);
COMMENT ON TABLE IM_EQUITY_CERT_TEMPLATE IS '确权权益证书模板';
COMMENT ON COLUMN IM_EQUITY_CERT_TEMPLATE.CEC_TEMPLATE_ID IS '模板ID';
COMMENT ON COLUMN IM_EQUITY_CERT_TEMPLATE.CEC_TEMPLATE_NAME IS '模板名称';
COMMENT ON COLUMN IM_EQUITY_CERT_TEMPLATE.CEC_TEMPLATE_VERSION IS '版本';
COMMENT ON COLUMN IM_EQUITY_CERT_TEMPLATE.CEC_RIGHT_TYPE IS '适用产权类型';
COMMENT ON COLUMN IM_EQUITY_CERT_TEMPLATE.CEC_TEMPLATE_CONTENT IS '模板内容';
COMMENT ON COLUMN IM_EQUITY_CERT_TEMPLATE.CEC_TEMPLATE_STATUS IS '状态';
COMMENT ON COLUMN IM_EQUITY_CERT_TEMPLATE.CEC_FILE_NAME IS '套版文件名';
COMMENT ON COLUMN IM_EQUITY_CERT_TEMPLATE.CEC_FILE_DATA IS '套版文件Base64';

-- ---------- 智能确权辅助工具(采购集成,confirm 域承载) ----------

-- 上传材料
CREATE TABLE IM_AIT_MATERIAL (
  CEC_MATERIAL_ID   VARCHAR(64) NOT NULL,
  CEC_BATCH_NO      VARCHAR(64),
  CEC_APPLY_ID      VARCHAR(64),
  CEC_FILE_NAME     VARCHAR(500),
  CEC_FILE_TYPE     VARCHAR(20),
  CEC_FILE_HASH     VARCHAR(64),
  CEC_SIZE_KB       BIGINT,
  CEC_PARSE_STATUS  VARCHAR(20),
  CEC_FAIL_REASON   VARCHAR(1000),
  CEC_PROGRESS      INT DEFAULT 0,
  CEC_STORAGE_PATH  VARCHAR(500),
  CEC_CONTENT       CLOB,
  CEC_CATEGORY      VARCHAR(50),
  CEC_DATA_TABLE_REF VARCHAR(255),
  CEC_LAYOUT_JSON   CLOB,
  CEC_DUPLICATE_OF  VARCHAR(64),
  CEC_PAGE_COUNT    INT,
  CEC_OCR_USED      INT DEFAULT 0,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_MATERIAL_ID)
);
COMMENT ON TABLE IM_AIT_MATERIAL IS '智能工具-上传材料';

-- 智能确权辅助工具:多粒度解析片段(按页/段/表格单元)
CREATE TABLE IM_AIT_DOC_SEGMENT (
  CEC_SEGMENT_ID    VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_GRANULARITY   VARCHAR(20),
  CEC_PAGE_NO       INT,
  CEC_SEG_INDEX     INT,
  CEC_SHEET_NAME    VARCHAR(100),
  CEC_ROW_NUM       INT,
  CEC_COL_NUM       INT,
  CEC_CONTENT       CLOB,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_SEGMENT_ID)
);
COMMENT ON TABLE IM_AIT_DOC_SEGMENT IS '智能工具-多粒度解析片段';

-- 智能确权辅助工具:清洗日志(#6)
CREATE TABLE IM_AIT_CLEAN_LOG (
  CEC_LOG_ID        VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_BATCH_NO      VARCHAR(64),
  CEC_ROW_NO        INT,
  CEC_FIELD         VARCHAR(64),
  CEC_RAW_KEY       VARCHAR(128),
  CEC_ORIGINAL_VALUE VARCHAR(2000),
  CEC_RULE          VARCHAR(255),
  CEC_CLEANED_VALUE VARCHAR(2000),
  CEC_METHOD        VARCHAR(20),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
);
COMMENT ON TABLE IM_AIT_CLEAN_LOG IS '智能工具-清洗日志';

-- 智能确权辅助工具:统一审核底表(#4/#5)
CREATE TABLE IM_AIT_AUDIT_BASE (
  CEC_AUDIT_ID      VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_BATCH_NO      VARCHAR(64),
  CEC_ROW_NO        INT,
  CEC_TEMPLATE_FIELD VARCHAR(64),
  CEC_FIELD_LABEL   VARCHAR(64),
  CEC_RAW_VALUE     VARCHAR(2000),
  CEC_CLEAN_VALUE   VARCHAR(2000),
  CEC_STATUS        VARCHAR(20),
  CEC_ISSUE         VARCHAR(500),
  CEC_SUGGESTION    VARCHAR(500),
  CEC_DATA_TABLE_REF VARCHAR(255),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_AUDIT_ID)
);
COMMENT ON TABLE IM_AIT_AUDIT_BASE IS '智能工具-统一审核底表';

-- 智能确权辅助工具:结构化确权画像(#6)
CREATE TABLE IM_AIT_PROFILE (
  CEC_PROFILE_ID    VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_DATA_TABLE_REF VARCHAR(255),
  CEC_LEVEL         VARCHAR(20),
  CEC_SOURCE_METHOD VARCHAR(50),
  CEC_SOURCE_METHOD_BY VARCHAR(20),
  CEC_DATA_FEATURES VARCHAR(500),
  CEC_ELEMENTS_JSON CLOB,
  CEC_CONFIDENCE    DOUBLE,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_PROFILE_ID)
);
COMMENT ON TABLE IM_AIT_PROFILE IS '智能工具-确权画像';

-- 智能确权辅助工具:关键主体(#2)
CREATE TABLE IM_AIT_PROFILE_SUBJECT (
  CEC_SUBJECT_ID    VARCHAR(64) NOT NULL,
  CEC_PROFILE_ID    VARCHAR(64),
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_SUBJECT_ROLE  VARCHAR(40),
  CEC_SUBJECT_NAME  VARCHAR(500),
  CEC_METHOD        VARCHAR(20),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_SUBJECT_ID)
);
COMMENT ON TABLE IM_AIT_PROFILE_SUBJECT IS '智能工具-关键主体';

-- 智能确权辅助工具:约束信息(#5)
CREATE TABLE IM_AIT_CONSTRAINT (
  CEC_CONSTRAINT_ID VARCHAR(64) NOT NULL,
  CEC_PROFILE_ID    VARCHAR(64),
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_CONSTRAINT_TYPE VARCHAR(40),
  CEC_CONSTRAINT_VALUE VARCHAR(1000),
  CEC_METHOD        VARCHAR(20),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONSTRAINT_ID)
);
COMMENT ON TABLE IM_AIT_CONSTRAINT IS '智能工具-约束信息';

-- 智能确权辅助工具:解析记录档(1.4#1)
CREATE TABLE IM_AIT_PARSE_RECORD (
  CEC_RECORD_ID     VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_FILE_NAME     VARCHAR(500),
  CEC_BATCH_NO      VARCHAR(64),
  CEC_FIELD         VARCHAR(64),
  CEC_FIELD_VALUE   VARCHAR(2000),
  CEC_CONFIDENCE    DOUBLE,
  CEC_OPERATOR_ID   VARCHAR(64),
  CEC_OPERATOR_NAME VARCHAR(64),
  CEC_PARSE_TIME    TIMESTAMP,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RECORD_ID)
);
COMMENT ON TABLE IM_AIT_PARSE_RECORD IS '智能工具-解析记录档';

-- 智能确权辅助工具:资料模板库(1.4#3)
CREATE TABLE IM_AIT_DOC_TEMPLATE (
  CEC_TEMPLATE_ID   VARCHAR(64) NOT NULL,
  CEC_TEMPLATE_TYPE VARCHAR(50),
  CEC_TEMPLATE_NAME VARCHAR(255),
  CEC_VERSION       VARCHAR(20),
  CEC_CONTENT       CLOB,
  CEC_FILE_NAME     VARCHAR(300),
  CEC_FILE_DATA     CLOB,
  CEC_IS_LATEST     INT DEFAULT 1,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TEMPLATE_ID)
);
COMMENT ON TABLE IM_AIT_DOC_TEMPLATE IS '智能工具-资料模板库';

-- 智能确权辅助工具:解析元数据配置(1.4#4)
CREATE TABLE IM_AIT_PARSE_CONFIG (
  CEC_CONFIG_ID     VARCHAR(64) NOT NULL,
  CEC_SCENE         VARCHAR(50),
  CEC_FIELD_MAPPING_JSON CLOB,
  CEC_EXTRACT_LOGIC_JSON CLOB,
  CEC_CONFIDENCE_THRESHOLD DOUBLE,
  CEC_ENABLED       INT DEFAULT 1,
  CEC_REMARK        VARCHAR(500),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONFIG_ID)
);
COMMENT ON TABLE IM_AIT_PARSE_CONFIG IS '智能工具-解析元数据配置';

-- 智能确权辅助工具:产权知识库-文档(2.1#1/#6)
CREATE TABLE IM_AIT_KB_DOC (
  CEC_DOC_ID        VARCHAR(64) NOT NULL,
  CEC_DOC_TYPE      VARCHAR(40),
  CEC_DOMAIN        VARCHAR(40),
  CEC_TITLE         VARCHAR(300),
  CEC_SOURCE        VARCHAR(300),
  CEC_EFFECTIVE_DATE VARCHAR(20),
  CEC_SCOPE         VARCHAR(500),
  CEC_VERSION       VARCHAR(20),
  CEC_IS_LATEST     INT DEFAULT 1,
  CEC_STATUS        VARCHAR(20),
  CEC_CONTENT       CLOB,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_DOC_ID)
);
COMMENT ON TABLE IM_AIT_KB_DOC IS '智能工具-知识库文档';

-- 智能确权辅助工具:产权知识库-切片(2.1#2/#3)
CREATE TABLE IM_AIT_KB_CHUNK (
  CEC_CHUNK_ID      VARCHAR(64) NOT NULL,
  CEC_DOC_ID        VARCHAR(64),
  CEC_DOC_TYPE      VARCHAR(40),
  CEC_DOMAIN        VARCHAR(40),
  CEC_TITLE         VARCHAR(300),
  CEC_CLAUSE_NO     VARCHAR(50),
  CEC_TAGS          VARCHAR(500),
  CEC_CONTENT       CLOB,
  CEC_VECTOR_JSON   CLOB,
  CEC_VECTOR_DIM    INT,
  CEC_EFFECTIVE_DATE VARCHAR(20),
  CEC_SCOPE         VARCHAR(500),
  CEC_STATUS        VARCHAR(20),
  CEC_SEQ           INT,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CHUNK_ID)
);
COMMENT ON TABLE IM_AIT_KB_CHUNK IS '智能工具-知识库切片';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_MATERIAL_ID IS '材料ID';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_BATCH_NO IS '批次号';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_APPLY_ID IS '关联申请';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_FILE_NAME IS '文件名';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_FILE_TYPE IS '文件类型';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_FILE_HASH IS '文件指纹';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_SIZE_KB IS '大小KB';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_PARSE_STATUS IS '解析状态';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_FAIL_REASON IS '失败原因';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_PROGRESS IS '进度';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_STORAGE_PATH IS '存储路径';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_CONTENT IS '抽取正文';

-- 材料解析要素
CREATE TABLE IM_AIT_PARSE_RESULT (
  CEC_PARSE_ID      VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_RIGHT_SUBJECT VARCHAR(500),
  CEC_RIGHT_OBJECT  VARCHAR(500),
  CEC_RIGHT_TYPE    VARCHAR(100),
  CEC_RIGHT_TERM    VARCHAR(100),
  CEC_AUTH_SCOPE    VARCHAR(500),
  CEC_DATA_SOURCE   VARCHAR(100),
  CEC_SENSITIVE_TYPE VARCHAR(100),
  CEC_SEAL_VALID    VARCHAR(20),
  CEC_SEAL_DESC     VARCHAR(500),
  CEC_CONFIDENCE    DOUBLE,
  CEC_REVIEW_STATUS VARCHAR(50),
  CEC_TRUST_SCORE   INT,
  CEC_TRUST_LEVEL   VARCHAR(50),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_PARSE_ID)
);
COMMENT ON TABLE IM_AIT_PARSE_RESULT IS '智能工具-解析要素';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_PARSE_ID IS '解析ID';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_MATERIAL_ID IS '材料ID';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_RIGHT_SUBJECT IS '权利主体';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_RIGHT_OBJECT IS '权利客体';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_RIGHT_TYPE IS '产权类型';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_RIGHT_TERM IS '权利期限';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_AUTH_SCOPE IS '授权范围';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_SENSITIVE_TYPE IS '敏感类型';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_SEAL_VALID IS '签章有效';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_SEAL_DESC IS '签章说明';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_CONFIDENCE IS '置信度';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_REVIEW_STATUS IS '复核标记(自动通过/需人工复核,阈值0.95)';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_TRUST_SCORE IS '材料可信度评分0-100(印章交叉校验+置信度+要素完整性)';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_TRUST_LEVEL IS '材料可信度评级(可信/存疑/不可信)';

-- 材料与表单比对
CREATE TABLE IM_AIT_COMPARE (
  CEC_COMPARE_ID     VARCHAR(64) NOT NULL,
  CEC_PARSE_ID       VARCHAR(64),
  CEC_APPLY_ID       VARCHAR(64),
  CEC_FIELD          VARCHAR(100),
  CEC_MATERIAL_VALUE VARCHAR(1000),
  CEC_FORM_VALUE     VARCHAR(1000),
  CEC_DIFF_TYPE      VARCHAR(20),
  CEC_SOURCE_OFFSET  INT,
  CEC_SOURCE_SNIPPET VARCHAR(500),
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    TIMESTAMP,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    TIMESTAMP,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_COMPARE_ID)
);
COMMENT ON TABLE IM_AIT_COMPARE IS '智能工具-材料表单比对';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_COMPARE_ID IS '比对ID';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_PARSE_ID IS '解析ID';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_FIELD IS '字段';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_MATERIAL_VALUE IS '材料值';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_FORM_VALUE IS '表单值';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_DIFF_TYPE IS '差异类型';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_SOURCE_OFFSET IS '材料值在原始正文的字符偏移(-1=未定位/图片)';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_SOURCE_SNIPPET IS '原始正文定位上下文片段';

-- 权属主张(知识图谱)
CREATE TABLE IM_AIT_KG_CLAIM (
  CEC_CLAIM_ID      VARCHAR(64) NOT NULL,
  CEC_ASSET_ID      VARCHAR(64),
  CEC_SUBJECT       VARCHAR(255),
  CEC_RIGHT_TYPE    VARCHAR(100),
  CEC_AUTH_SCOPE    VARCHAR(500),
  CEC_VALID_DATE    TIMESTAMP,
  CEC_EXCLUSIVE     SMALLINT,
  CEC_SOURCE_TYPE   VARCHAR(50),
  CEC_REMARK        VARCHAR(1000),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CLAIM_ID)
);
COMMENT ON TABLE IM_AIT_KG_CLAIM IS '智能工具-权属主张(KG)';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_CLAIM_ID IS '主张ID';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_SUBJECT IS '主体';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_RIGHT_TYPE IS '产权类型';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_AUTH_SCOPE IS '授权范围';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_VALID_DATE IS '有效期';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_EXCLUSIVE IS '是否独占';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_SOURCE_TYPE IS '来源类型';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_REMARK IS '备注';
CREATE INDEX IDX_KG_ASSET ON IM_AIT_KG_CLAIM (CEC_ASSET_ID);

-- 权属冲突
CREATE TABLE IM_AIT_CONFLICT (
  CEC_CONFLICT_ID    VARCHAR(64) NOT NULL,
  CEC_ASSET_ID       VARCHAR(64),
  CEC_CONFLICT_TYPE  VARCHAR(50),
  CEC_CONFLICT_SOURCE VARCHAR(255),
  CEC_CONFLICT_DESC  VARCHAR(2000),
  CEC_IMPACT_SCOPE   VARCHAR(1000),
  CEC_RISK_LEVEL     VARCHAR(20),
  CEC_SUGGESTION     VARCHAR(2000),
  CEC_STATUS         VARCHAR(20),
  CEC_RELATED_RECORD_NO VARCHAR(255),
  CEC_CONFLICT_FIELDS VARCHAR(255),
  CEC_CLAUSE_REF     VARCHAR(500),
  CEC_LEGAL_RISK     VARCHAR(40),
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    TIMESTAMP,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    TIMESTAMP,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONFLICT_ID)
);
COMMENT ON TABLE IM_AIT_CONFLICT IS '智能工具-权属冲突';

-- 智能确权辅助工具:冲突识别规则配置
CREATE TABLE IM_AIT_CONFLICT_RULE (
  CEC_RULE_ID       VARCHAR(64) NOT NULL,
  CEC_RULE_TYPE     VARCHAR(40),
  CEC_RULE_NAME     VARCHAR(100),
  CEC_ENABLED       INT DEFAULT 1,
  CEC_PRIORITY      INT DEFAULT 100,
  CEC_THRESHOLD     DOUBLE,
  CEC_REMARK        VARCHAR(500),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RULE_ID)
);
COMMENT ON TABLE IM_AIT_CONFLICT_RULE IS '智能工具-冲突识别规则';

-- 智能确权辅助工具:智能确权 Agent 审核结果(3.1)
CREATE TABLE IM_AIT_AUDIT_RESULT (
  CEC_AUDIT_ID      VARCHAR(64) NOT NULL,
  CEC_APPLY_ID      VARCHAR(64),
  CEC_ASSET_ID      VARCHAR(64),
  CEC_CHANNEL       VARCHAR(20),
  CEC_DATA_CLASS    VARCHAR(100),
  CEC_DATA_GRADE    VARCHAR(40),
  CEC_RIGHT_TYPE    VARCHAR(100),
  CEC_AUTH_ADVICE   VARCHAR(40),
  CEC_AUTH_LEVEL    VARCHAR(40),
  CEC_RESTRICTIONS  VARCHAR(1000),
  CEC_RISK_LEVEL    VARCHAR(20),
  CEC_SUPPLEMENT    VARCHAR(1000),
  CEC_REASON        VARCHAR(2000),
  CEC_CITATIONS     VARCHAR(1000),
  CEC_ACTION        VARCHAR(255),
  CEC_SCORE         DOUBLE,
  CEC_STAGE_TRACE_JSON CLOB,
  CEC_TOOL_TRACE_JSON  CLOB,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_AUDIT_ID)
);
COMMENT ON TABLE IM_AIT_AUDIT_RESULT IS '智能工具-Agent审核结果';

-- 智能确权辅助工具:批量任务(3.3#5/#4)
CREATE TABLE IM_AIT_TASK (
  CEC_TASK_ID       VARCHAR(64) NOT NULL,
  CEC_TASK_TYPE     VARCHAR(40),
  CEC_TASK_NAME     VARCHAR(200),
  CEC_ITEMS_JSON    CLOB,
  CEC_ITEM_STATE_JSON CLOB,
  CEC_TOTAL         INT DEFAULT 0,
  CEC_DONE          INT DEFAULT 0,
  CEC_FAILED        INT DEFAULT 0,
  CEC_STATUS        VARCHAR(20),
  CEC_CONCURRENCY   INT DEFAULT 4,
  CEC_RETRY_MAX     INT DEFAULT 2,
  CEC_CURSOR        INT DEFAULT 0,
  CEC_LAST_ERROR    VARCHAR(1000),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TASK_ID)
);
COMMENT ON TABLE IM_AIT_TASK IS '智能工具-批量任务';

-- 智能确权辅助工具:统一运行日志(3.3#6)
CREATE TABLE IM_AIT_RUN_LOG (
  CEC_LOG_ID        VARCHAR(64) NOT NULL,
  CEC_LOG_TYPE      VARCHAR(20),
  CEC_SOURCE        VARCHAR(100),
  CEC_ACTION        VARCHAR(100),
  CEC_DETAIL        VARCHAR(2000),
  CEC_MODEL         VARCHAR(64),
  CEC_DURATION_MS   BIGINT,
  CEC_RESULT        VARCHAR(20),
  CEC_TASK_ID       VARCHAR(64),
  CEC_LOG_TIME      TIMESTAMP,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
);
COMMENT ON TABLE IM_AIT_RUN_LOG IS '智能工具-统一运行日志';

-- 智能确权辅助工具:审核证据链档案(3.2#4)
CREATE TABLE IM_AIT_EVIDENCE (
  CEC_EVIDENCE_ID   VARCHAR(64) NOT NULL,
  CEC_APPLY_ID      VARCHAR(64),
  CEC_ASSET_ID      VARCHAR(64),
  CEC_MATERIAL_SNIPPETS_JSON CLOB,
  CEC_KB_HITS_JSON  CLOB,
  CEC_RULE_HITS_JSON CLOB,
  CEC_MODEL_REASON  CLOB,
  CEC_CONCLUSION    VARCHAR(500),
  CEC_SM3_HASH      VARCHAR(80),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_EVIDENCE_ID)
);
COMMENT ON TABLE IM_AIT_EVIDENCE IS '智能工具-审核证据链';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_CONFLICT_ID IS '冲突ID';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_CONFLICT_TYPE IS '冲突类型';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_CONFLICT_SOURCE IS '冲突来源';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_CONFLICT_DESC IS '冲突描述';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_IMPACT_SCOPE IS '影响范围';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_RISK_LEVEL IS '风险级别';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_SUGGESTION IS '消解建议';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_STATUS IS '状态';
CREATE INDEX IDX_CFL_ASSET ON IM_AIT_CONFLICT (CEC_ASSET_ID);

-- 确权决策建议
CREATE TABLE IM_AIT_DECISION (
  CEC_DECISION_ID      VARCHAR(64) NOT NULL,
  CEC_APPLY_ID         VARCHAR(64),
  CEC_ASSET_ID         VARCHAR(64),
  CEC_PREDICTION       VARCHAR(50),
  CEC_SCORE            DOUBLE,
  CEC_FACTORS_JSON     CLOB,
  CEC_STRENGTH         VARCHAR(500),
  CEC_WEAKNESS         VARCHAR(500),
  CEC_SPLIT_PLAN       VARCHAR(2000),
  CEC_SPLIT_PLANS_JSON CLOB,
  CEC_REASON           VARCHAR(2000),
  CEC_SUPPLEMENT       VARCHAR(1000),
  CEC_PENDING_CONFLICTS VARCHAR(1000),
  CEC_RAG_ADVICE       CLOB,
  CEC_AI_PREDICTION    VARCHAR(50),
  CEC_RAG_CITATIONS    VARCHAR(1000),
  CEC_EVIDENCE_CHAIN   VARCHAR(80),
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      TIMESTAMP,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      TIMESTAMP,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_DECISION_ID)
);
COMMENT ON TABLE IM_AIT_DECISION IS '智能工具-确权决策建议';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_DECISION_ID IS '决策ID';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_PREDICTION IS '预测结论';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_SCORE IS '评分';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_FACTORS_JSON IS '因子JSON';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_STRENGTH IS '优势';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_WEAKNESS IS '不足';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_SPLIT_PLAN IS '三权分置建议';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_SPLIT_PLANS_JSON IS '权益分割多方案明细JSON';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_REASON IS '理由';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_SUPPLEMENT IS '补充建议';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_PENDING_CONFLICTS IS '待解冲突';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_RAG_ADVICE IS 'RAG法规建议';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_AI_PREDICTION IS 'AI预测结论';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_RAG_CITATIONS IS 'RAG法规引用';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_EVIDENCE_CHAIN IS '存证链';
CREATE INDEX IDX_DEC_APPLY ON IM_AIT_DECISION (CEC_APPLY_ID);

-- =====================================================================
-- F-03 数据授权管理 (dpr-authorize-service, 9103)
-- =====================================================================

-- 数据授权申请单表
CREATE TABLE IM_AUTH_APPLY (
  CEC_APPLY_ID              VARCHAR(64)  NOT NULL,
  CEC_APPLY_NO              VARCHAR(64),
  CEC_AUTH_MODE             VARCHAR(50),
  CEC_ASSET_ID              VARCHAR(64)  NOT NULL,
  CEC_ASSET_NAME            VARCHAR(255) NOT NULL,
  CEC_EQUITY_CARD_ID        VARCHAR(64),
  CEC_GRANTEE_ORG           VARCHAR(255),
  CEC_RIGHT_TYPE            VARCHAR(100),
  CEC_SCENARIO              VARCHAR(500),
  CEC_SCOPE                 VARCHAR(1000),
  CEC_VALID_DATE            TIMESTAMP,
  CEC_STATUS                VARCHAR(50),
  CEC_REJECT_REASON         VARCHAR(1000),
  CEC_CURRENT_NODE          INT,
  CEC_BATCH_LIST_ID         VARCHAR(64),
  CEC_NEED_CONFIDENTIALITY  SMALLINT,
  CEC_CONFIDENTIALITY_FILE  VARCHAR(500),
  CEC_BUSINESS_DOMAIN       VARCHAR(100),
  CEC_CROSS_REGION          SMALLINT,
  CEC_THIRD_PARTY_SOURCE    VARCHAR(255),
  CEC_THIRD_PARTY_LICENSE   VARCHAR(1000),
  CEC_SENSITIVE_TYPE        VARCHAR(100),
  CEC_INFO_AUTH_AGREEMENT   VARCHAR(500),
  CEC_APPLICANT_MANAGER     VARCHAR(100),
  CEC_CONTACT               VARCHAR(100),
  CEC_PROVINCE_CODE         VARCHAR(32),
  CEC_BUREAU_CODE           VARCHAR(32),
  CEC_CREATOR_ID            VARCHAR(64),
  CEC_CREATE_TIME           TIMESTAMP,
  CEC_UPDATER_ID            VARCHAR(64),
  CEC_UPDATE_TIME           TIMESTAMP,
  CEC_DEL_FLAG              INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_APPLY_ID)
);
COMMENT ON TABLE IM_AUTH_APPLY IS '数据授权申请单';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_APPLY_NO IS '申请编号';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_AUTH_MODE IS '授权模式(一事一议/批量)';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_ASSET_NAME IS '资产名称';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_EQUITY_CARD_ID IS '引用权益卡片(先确后授)';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_GRANTEE_ORG IS '被授权方';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_RIGHT_TYPE IS '产权类型';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_SCENARIO IS '应用场景';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_SCOPE IS '授权范围';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_VALID_DATE IS '有效期';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_STATUS IS '状态机状态';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_REJECT_REASON IS '驳回原因';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_CURRENT_NODE IS '当前节点';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_BATCH_LIST_ID IS '批量清单ID';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_NEED_CONFIDENTIALITY IS '是否需保密承诺函(附录E)';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_CONFIDENTIALITY_FILE IS '保密承诺函(附录E)';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_BUSINESS_DOMAIN IS '所属业务域(表5)';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_CROSS_REGION IS '是否跨区域/跨域(表5)';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_THIRD_PARTY_SOURCE IS '涉及第三方来源方式(表5)';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_THIRD_PARTY_LICENSE IS '第三方许可凭证或说明(表5)';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_SENSITIVE_TYPE IS '涉及个人隐私/商业秘密(表5)';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_INFO_AUTH_AGREEMENT IS '信息授权协议(表5)';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_APPLICANT_MANAGER IS '申请单位主管(表5)';
COMMENT ON COLUMN IM_AUTH_APPLY.CEC_CONTACT IS '联系方式(表5)';
CREATE INDEX IDX_AA_ASSET ON IM_AUTH_APPLY (CEC_ASSET_ID);
CREATE INDEX IDX_AA_STATUS ON IM_AUTH_APPLY (CEC_STATUS);

-- 表6 数据批量授权清单
CREATE TABLE IM_BATCH_AUTH_LIST (
  CEC_BATCH_LIST_ID VARCHAR(64)  NOT NULL,
  CEC_LIST_NO       VARCHAR(64),
  CEC_LIST_YEAR     VARCHAR(20),
  CEC_LIST_STATUS   VARCHAR(50),
  CEC_ITEM_COUNT    INT,
  CEC_REMARK        VARCHAR(1000),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_BATCH_LIST_ID)
);
COMMENT ON TABLE IM_BATCH_AUTH_LIST IS '批量授权清单(表6)';
COMMENT ON COLUMN IM_BATCH_AUTH_LIST.CEC_BATCH_LIST_ID IS '清单ID';
COMMENT ON COLUMN IM_BATCH_AUTH_LIST.CEC_LIST_NO IS '清单编号';
COMMENT ON COLUMN IM_BATCH_AUTH_LIST.CEC_LIST_YEAR IS '年度';
COMMENT ON COLUMN IM_BATCH_AUTH_LIST.CEC_LIST_STATUS IS '状态';
COMMENT ON COLUMN IM_BATCH_AUTH_LIST.CEC_ITEM_COUNT IS '条目数';
COMMENT ON COLUMN IM_BATCH_AUTH_LIST.CEC_REMARK IS '备注';

-- 授权域通用目录项(指引/场景/表单模板/协议模板库,按 category 复用)
CREATE TABLE IM_AUTH_CATALOG_ITEM (
  CEC_ITEM_ID       VARCHAR(64)  NOT NULL,
  CEC_CATEGORY      VARCHAR(50)  NOT NULL,
  CEC_NAME          VARCHAR(255) NOT NULL,
  CEC_ITEM_TYPE     VARCHAR(100),
  CEC_VERSION       VARCHAR(20),
  CEC_CONTENT       CLOB,
  CEC_STATUS        VARCHAR(50),
  CEC_PUBLISHER     VARCHAR(100),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ITEM_ID)
);
COMMENT ON TABLE IM_AUTH_CATALOG_ITEM IS '授权域通用目录项';
COMMENT ON COLUMN IM_AUTH_CATALOG_ITEM.CEC_ITEM_ID IS '目录项ID';
COMMENT ON COLUMN IM_AUTH_CATALOG_ITEM.CEC_CATEGORY IS '类别(GUIDANCE/SCENARIO/FORM_TEMPLATE/AGREEMENT_TEMPLATE)';
COMMENT ON COLUMN IM_AUTH_CATALOG_ITEM.CEC_NAME IS '名称';
COMMENT ON COLUMN IM_AUTH_CATALOG_ITEM.CEC_ITEM_TYPE IS '类型';
COMMENT ON COLUMN IM_AUTH_CATALOG_ITEM.CEC_VERSION IS '版本';
COMMENT ON COLUMN IM_AUTH_CATALOG_ITEM.CEC_CONTENT IS '内容';
COMMENT ON COLUMN IM_AUTH_CATALOG_ITEM.CEC_STATUS IS '状态';
COMMENT ON COLUMN IM_AUTH_CATALOG_ITEM.CEC_PUBLISHER IS '发布单位';
CREATE INDEX IDX_CAT_CATEGORY ON IM_AUTH_CATALOG_ITEM (CEC_CATEGORY);

-- 授权申请合规校验结果
CREATE TABLE IM_AUTH_COMPLIANCE (
  CEC_CHECK_ID      VARCHAR(64)  NOT NULL,
  CEC_APPLY_ID      VARCHAR(64),
  CEC_RISK_LEVEL    VARCHAR(20),
  CEC_CHECK_RESULT  VARCHAR(50),
  CEC_PROBLEM_DESC  VARCHAR(2000),
  CEC_CHECK_REPORT  CLOB,
  CEC_CHECK_TIME    TIMESTAMP,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CHECK_ID)
);
COMMENT ON TABLE IM_AUTH_COMPLIANCE IS '授权合规校验结果';
COMMENT ON COLUMN IM_AUTH_COMPLIANCE.CEC_CHECK_ID IS '校验ID';
COMMENT ON COLUMN IM_AUTH_COMPLIANCE.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_AUTH_COMPLIANCE.CEC_RISK_LEVEL IS '风险级别';
COMMENT ON COLUMN IM_AUTH_COMPLIANCE.CEC_CHECK_RESULT IS '校验结果';
COMMENT ON COLUMN IM_AUTH_COMPLIANCE.CEC_PROBLEM_DESC IS '问题描述';
COMMENT ON COLUMN IM_AUTH_COMPLIANCE.CEC_CHECK_REPORT IS '多维校验报告JSON';
COMMENT ON COLUMN IM_AUTH_COMPLIANCE.CEC_CHECK_TIME IS '校验时间';
CREATE INDEX IDX_AC_APPLY ON IM_AUTH_COMPLIANCE (CEC_APPLY_ID);

-- 数据运营授权协议(签章/审核/存档/下载)
CREATE TABLE IM_AUTH_AGREEMENT (
  CEC_AGREEMENT_ID    VARCHAR(64)  NOT NULL,
  CEC_AGREEMENT_NO    VARCHAR(64),
  CEC_APPLY_ID        VARCHAR(64),
  CEC_TEMPLATE_ID     VARCHAR(64),
  CEC_GRANTEE_ORG     VARCHAR(255),
  CEC_FILE_URL        VARCHAR(500),
  CEC_SEAL_STATUS     VARCHAR(50),
  CEC_SEAL_VERIFY     VARCHAR(100),
  CEC_GRANTOR_SIGNED  SMALLINT,
  CEC_GRANTOR_SIGN_TIME TIMESTAMP,
  CEC_GRANTEE_SIGNED  SMALLINT,
  CEC_GRANTEE_SIGN_TIME TIMESTAMP,
  CEC_REVIEW_STATUS   VARCHAR(50),
  CEC_ARCHIVE_STATUS  VARCHAR(50),
  CEC_AGREEMENT_TYPE  VARCHAR(100),
  CEC_DEPT_NAME       VARCHAR(255),
  CEC_ARCHIVE_TIME    TIMESTAMP,
  CEC_SIGN_TIME       TIMESTAMP,
  CEC_PROVINCE_CODE   VARCHAR(32),
  CEC_BUREAU_CODE     VARCHAR(32),
  CEC_CREATOR_ID      VARCHAR(64),
  CEC_CREATE_TIME     TIMESTAMP,
  CEC_UPDATER_ID      VARCHAR(64),
  CEC_UPDATE_TIME     TIMESTAMP,
  CEC_DEL_FLAG        INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_AGREEMENT_ID)
);
COMMENT ON TABLE IM_AUTH_AGREEMENT IS '数据运营授权协议';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_AGREEMENT_ID IS '协议ID';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_AGREEMENT_NO IS '协议编号';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_TEMPLATE_ID IS '模板ID';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_GRANTEE_ORG IS '被授权方';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_FILE_URL IS '协议文件';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_SEAL_STATUS IS '签章状态';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_SEAL_VERIFY IS '签章校验';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_GRANTOR_SIGNED IS '甲方已签';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_GRANTOR_SIGN_TIME IS '甲方签署时间';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_GRANTEE_SIGNED IS '乙方已签';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_GRANTEE_SIGN_TIME IS '乙方签署时间';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_REVIEW_STATUS IS '审核状态';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_ARCHIVE_STATUS IS '归档状态';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_AGREEMENT_TYPE IS '协议类型(存档检索)';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_DEPT_NAME IS '所属部门(存档检索)';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_ARCHIVE_TIME IS '归档时间';
COMMENT ON COLUMN IM_AUTH_AGREEMENT.CEC_SIGN_TIME IS '签署时间';
CREATE INDEX IDX_AG_APPLY ON IM_AUTH_AGREEMENT (CEC_APPLY_ID);

-- 授权权益证书表
CREATE TABLE IM_AUTH_CERT (
  CEC_CERT_ID        VARCHAR(64)  NOT NULL,
  CEC_CERT_NO        VARCHAR(64),
  CEC_APPLY_ID       VARCHAR(64),
  CEC_ASSET_ID       VARCHAR(64),
  CEC_GRANTEE_ORG    VARCHAR(255),
  CEC_RIGHT_TYPE     VARCHAR(100),
  CEC_SCOPE          VARCHAR(1000),
  CEC_VALID_DATE     TIMESTAMP,
  CEC_CERT_STATUS    VARCHAR(50),
  CEC_SUSPEND_REASON VARCHAR(1000),
  CEC_TEMPLATE_ID    VARCHAR(64),
  CEC_TEMPLATE_NAME  VARCHAR(255),
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    TIMESTAMP,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    TIMESTAMP,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CERT_ID)
);
COMMENT ON TABLE IM_AUTH_CERT IS '授权权益证书';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_CERT_ID IS '证书ID';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_CERT_NO IS '证书编号';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_GRANTEE_ORG IS '被授权方';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_RIGHT_TYPE IS '产权类型';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_SCOPE IS '授权范围';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_VALID_DATE IS '有效期';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_CERT_STATUS IS '证书状态(生效/已暂停/已撤销)';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_SUSPEND_REASON IS '暂停/熔断原因';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_TEMPLATE_ID IS '出证模板ID';
COMMENT ON COLUMN IM_AUTH_CERT.CEC_TEMPLATE_NAME IS '出证模板名称';
CREATE INDEX IDX_ACERT_ASSET ON IM_AUTH_CERT (CEC_ASSET_ID);

-- 授权权益证书模板(专项/批量)
CREATE TABLE IM_AUTH_CERT_TEMPLATE (
  CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL,
  CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL,
  CEC_TEMPLATE_VERSION VARCHAR(20),
  CEC_CERT_TYPE        VARCHAR(50),
  CEC_RIGHT_TYPE       VARCHAR(100),
  CEC_TEMPLATE_CONTENT CLOB,
  CEC_TEMPLATE_STATUS  VARCHAR(50),
  CEC_FILE_NAME        VARCHAR(300),
  CEC_FILE_DATA        CLOB,
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      TIMESTAMP,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      TIMESTAMP,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TEMPLATE_ID)
);
COMMENT ON TABLE IM_AUTH_CERT_TEMPLATE IS '授权权益证书模板';
COMMENT ON COLUMN IM_AUTH_CERT_TEMPLATE.CEC_TEMPLATE_ID IS '模板ID';
COMMENT ON COLUMN IM_AUTH_CERT_TEMPLATE.CEC_TEMPLATE_NAME IS '模板名称';
COMMENT ON COLUMN IM_AUTH_CERT_TEMPLATE.CEC_TEMPLATE_VERSION IS '版本';
COMMENT ON COLUMN IM_AUTH_CERT_TEMPLATE.CEC_CERT_TYPE IS '证书类型(专项/批量授权证书)';
COMMENT ON COLUMN IM_AUTH_CERT_TEMPLATE.CEC_RIGHT_TYPE IS '产权类型';
COMMENT ON COLUMN IM_AUTH_CERT_TEMPLATE.CEC_TEMPLATE_CONTENT IS '模板内容';
COMMENT ON COLUMN IM_AUTH_CERT_TEMPLATE.CEC_TEMPLATE_STATUS IS '状态';
COMMENT ON COLUMN IM_AUTH_CERT_TEMPLATE.CEC_FILE_NAME IS '套版文件名';
COMMENT ON COLUMN IM_AUTH_CERT_TEMPLATE.CEC_FILE_DATA IS '套版文件Base64';

-- 授权指引材料(可研 3.2.2.1.1.3.1.1:政策/流程图/常见问答/申请步骤 + 上传下载 + 历史版本)
CREATE TABLE IM_AUTH_GUIDANCE (
  CEC_GUIDANCE_ID   VARCHAR(64)  NOT NULL,
  CEC_TITLE         VARCHAR(255) NOT NULL,
  CEC_GUIDANCE_TYPE VARCHAR(100),
  CEC_VERSION       VARCHAR(20),
  CEC_PUBLISHER     VARCHAR(100),
  CEC_PUBLISH_DATE  TIMESTAMP,
  CEC_FILE_URL      VARCHAR(500),
  CEC_FILE_NAME     VARCHAR(300),
  CEC_FILE_DATA     CLOB,
  CEC_IS_LATEST     SMALLINT DEFAULT 1,
  CEC_CONTENT       CLOB,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_GUIDANCE_ID)
);
COMMENT ON TABLE IM_AUTH_GUIDANCE IS '授权指引材料';
COMMENT ON COLUMN IM_AUTH_GUIDANCE.CEC_GUIDANCE_ID IS '指引ID';
COMMENT ON COLUMN IM_AUTH_GUIDANCE.CEC_TITLE IS '标题';
COMMENT ON COLUMN IM_AUTH_GUIDANCE.CEC_GUIDANCE_TYPE IS '类型(政策文件/流程图/常见问答/申请步骤/材料样例)';
COMMENT ON COLUMN IM_AUTH_GUIDANCE.CEC_VERSION IS '版本';
COMMENT ON COLUMN IM_AUTH_GUIDANCE.CEC_PUBLISHER IS '发布人';
COMMENT ON COLUMN IM_AUTH_GUIDANCE.CEC_PUBLISH_DATE IS '发布日期';
COMMENT ON COLUMN IM_AUTH_GUIDANCE.CEC_FILE_URL IS '文件下载地址';
COMMENT ON COLUMN IM_AUTH_GUIDANCE.CEC_FILE_NAME IS '原件文件名';
COMMENT ON COLUMN IM_AUTH_GUIDANCE.CEC_FILE_DATA IS '原件Base64';
COMMENT ON COLUMN IM_AUTH_GUIDANCE.CEC_IS_LATEST IS '是否最新版本';
COMMENT ON COLUMN IM_AUTH_GUIDANCE.CEC_CONTENT IS '正文内容';
CREATE INDEX IDX_AUTHGUIDE_TITLE ON IM_AUTH_GUIDANCE (CEC_TITLE);

-- 授权申请表单模板(可研 3.2.2.1.1.3.1.2:按授权类型 独占/共享/委托 配置字段/流程/验证规则)
CREATE TABLE IM_AUTH_APPLY_TEMPLATE (
  CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL,
  CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL,
  CEC_AUTH_TYPE        VARCHAR(50),
  CEC_FIELDS_JSON      CLOB,
  CEC_FLOW_DESC        VARCHAR(2000),
  CEC_TEMPLATE_VERSION VARCHAR(20),
  CEC_TEMPLATE_STATUS  VARCHAR(50),
  CEC_REMARK           VARCHAR(1000),
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      TIMESTAMP,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      TIMESTAMP,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TEMPLATE_ID)
);
COMMENT ON TABLE IM_AUTH_APPLY_TEMPLATE IS '授权申请表单模板';
COMMENT ON COLUMN IM_AUTH_APPLY_TEMPLATE.CEC_TEMPLATE_ID IS '模板ID';
COMMENT ON COLUMN IM_AUTH_APPLY_TEMPLATE.CEC_TEMPLATE_NAME IS '模板名称';
COMMENT ON COLUMN IM_AUTH_APPLY_TEMPLATE.CEC_AUTH_TYPE IS '授权类型(独占/共享/委托)';
COMMENT ON COLUMN IM_AUTH_APPLY_TEMPLATE.CEC_FIELDS_JSON IS '字段配置JSON[{name,label,type,required,rule}]';
COMMENT ON COLUMN IM_AUTH_APPLY_TEMPLATE.CEC_FLOW_DESC IS '流程说明';
COMMENT ON COLUMN IM_AUTH_APPLY_TEMPLATE.CEC_TEMPLATE_VERSION IS '版本';
COMMENT ON COLUMN IM_AUTH_APPLY_TEMPLATE.CEC_TEMPLATE_STATUS IS '状态';
COMMENT ON COLUMN IM_AUTH_APPLY_TEMPLATE.CEC_REMARK IS '备注';
CREATE INDEX IDX_APPLYTPL_TYPE ON IM_AUTH_APPLY_TEMPLATE (CEC_AUTH_TYPE);

-- 授权应用场景配置(可研 3.2.2.1.1.3.1.3:用途场景 分类/描述 + 申请原因模板)
CREATE TABLE IM_AUTH_SCENARIO (
  CEC_SCENARIO_ID     VARCHAR(64)  NOT NULL,
  CEC_SCENARIO_NAME   VARCHAR(255) NOT NULL,
  CEC_CATEGORY        VARCHAR(100),
  CEC_DESCRIPTION     VARCHAR(1000),
  CEC_REASON_TEMPLATE VARCHAR(2000),
  CEC_SCENARIO_STATUS VARCHAR(50),
  CEC_PROVINCE_CODE   VARCHAR(32),
  CEC_BUREAU_CODE     VARCHAR(32),
  CEC_CREATOR_ID      VARCHAR(64),
  CEC_CREATE_TIME     TIMESTAMP,
  CEC_UPDATER_ID      VARCHAR(64),
  CEC_UPDATE_TIME     TIMESTAMP,
  CEC_DEL_FLAG        INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_SCENARIO_ID)
);
COMMENT ON TABLE IM_AUTH_SCENARIO IS '授权应用场景配置';
COMMENT ON COLUMN IM_AUTH_SCENARIO.CEC_SCENARIO_ID IS '场景ID';
COMMENT ON COLUMN IM_AUTH_SCENARIO.CEC_SCENARIO_NAME IS '场景名称';
COMMENT ON COLUMN IM_AUTH_SCENARIO.CEC_CATEGORY IS '场景分类';
COMMENT ON COLUMN IM_AUTH_SCENARIO.CEC_DESCRIPTION IS '场景描述';
COMMENT ON COLUMN IM_AUTH_SCENARIO.CEC_REASON_TEMPLATE IS '申请原因模板';
COMMENT ON COLUMN IM_AUTH_SCENARIO.CEC_SCENARIO_STATUS IS '状态';
CREATE INDEX IDX_SCENARIO_CAT ON IM_AUTH_SCENARIO (CEC_CATEGORY);

-- 授权申请材料(可研 3.2.2.1.1.3.1.4:上传相关材料,Base64 入库)
CREATE TABLE IM_AUTH_MATERIAL (
  CEC_MATERIAL_ID   VARCHAR(64)  NOT NULL,
  CEC_APPLY_ID      VARCHAR(64),
  CEC_MATERIAL_NAME VARCHAR(300),
  CEC_MATERIAL_TYPE VARCHAR(100),
  CEC_OWNER         VARCHAR(100),
  CEC_UPLOAD_TIME   TIMESTAMP,
  CEC_FILE_NAME     VARCHAR(300),
  CEC_FILE_DATA     CLOB,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_MATERIAL_ID)
);
COMMENT ON TABLE IM_AUTH_MATERIAL IS '授权申请材料';
COMMENT ON COLUMN IM_AUTH_MATERIAL.CEC_MATERIAL_ID IS '材料ID';
COMMENT ON COLUMN IM_AUTH_MATERIAL.CEC_APPLY_ID IS '关联申请ID';
COMMENT ON COLUMN IM_AUTH_MATERIAL.CEC_MATERIAL_NAME IS '材料名称';
COMMENT ON COLUMN IM_AUTH_MATERIAL.CEC_MATERIAL_TYPE IS '材料类型';
COMMENT ON COLUMN IM_AUTH_MATERIAL.CEC_OWNER IS '上传人';
COMMENT ON COLUMN IM_AUTH_MATERIAL.CEC_UPLOAD_TIME IS '上传时间';
COMMENT ON COLUMN IM_AUTH_MATERIAL.CEC_FILE_NAME IS '原件文件名';
COMMENT ON COLUMN IM_AUTH_MATERIAL.CEC_FILE_DATA IS '原件Base64';
CREATE INDEX IDX_AUTHMAT_APPLY ON IM_AUTH_MATERIAL (CEC_APPLY_ID);

-- 授权申请审批处理记录(可研 3.2.2.1.1.3.2.1:审批轨迹 from→to/责任人/审核意见/时间)
CREATE TABLE IM_AUTH_FLOW_LOG (
  CEC_LOG_ID      VARCHAR(64)  NOT NULL,
  CEC_APPLY_ID    VARCHAR(64),
  CEC_APPLY_NO    VARCHAR(64),
  CEC_FROM_STATUS VARCHAR(50),
  CEC_TO_STATUS   VARCHAR(50),
  CEC_NODE_NAME   VARCHAR(100),
  CEC_RESPONDER   VARCHAR(100),
  CEC_OPINION     VARCHAR(2000),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE VARCHAR(32),
  CEC_CREATOR_ID  VARCHAR(64),
  CEC_CREATE_TIME TIMESTAMP,
  CEC_UPDATER_ID  VARCHAR(64),
  CEC_UPDATE_TIME TIMESTAMP,
  CEC_DEL_FLAG    INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
);
COMMENT ON TABLE IM_AUTH_FLOW_LOG IS '授权申请审批处理记录';
COMMENT ON COLUMN IM_AUTH_FLOW_LOG.CEC_LOG_ID IS '日志ID';
COMMENT ON COLUMN IM_AUTH_FLOW_LOG.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_AUTH_FLOW_LOG.CEC_APPLY_NO IS '申请编号';
COMMENT ON COLUMN IM_AUTH_FLOW_LOG.CEC_FROM_STATUS IS '原状态';
COMMENT ON COLUMN IM_AUTH_FLOW_LOG.CEC_TO_STATUS IS '新状态';
COMMENT ON COLUMN IM_AUTH_FLOW_LOG.CEC_NODE_NAME IS '节点名称';
COMMENT ON COLUMN IM_AUTH_FLOW_LOG.CEC_RESPONDER IS '责任人';
COMMENT ON COLUMN IM_AUTH_FLOW_LOG.CEC_OPINION IS '审核意见';
CREATE INDEX IDX_AUTHFLOW_APPLY ON IM_AUTH_FLOW_LOG (CEC_APPLY_ID);

-- 授权协议模板库(可研 3.2.2.1.1.3.3.1:授权类型/使用目的分类 + 版本 + 内容 + 套版文件上传下载)
CREATE TABLE IM_AUTH_AGREEMENT_TEMPLATE (
  CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL,
  CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL,
  CEC_AUTH_TYPE        VARCHAR(50),
  CEC_PURPOSE          VARCHAR(100),
  CEC_TEMPLATE_CONTENT CLOB,
  CEC_TEMPLATE_VERSION VARCHAR(20),
  CEC_TEMPLATE_STATUS  VARCHAR(50),
  CEC_FILE_NAME        VARCHAR(300),
  CEC_FILE_DATA        CLOB,
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      TIMESTAMP,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      TIMESTAMP,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TEMPLATE_ID)
);
COMMENT ON TABLE IM_AUTH_AGREEMENT_TEMPLATE IS '授权协议模板库';
COMMENT ON COLUMN IM_AUTH_AGREEMENT_TEMPLATE.CEC_TEMPLATE_ID IS '模板ID';
COMMENT ON COLUMN IM_AUTH_AGREEMENT_TEMPLATE.CEC_TEMPLATE_NAME IS '模板名称';
COMMENT ON COLUMN IM_AUTH_AGREEMENT_TEMPLATE.CEC_AUTH_TYPE IS '授权类型';
COMMENT ON COLUMN IM_AUTH_AGREEMENT_TEMPLATE.CEC_PURPOSE IS '使用目的';
COMMENT ON COLUMN IM_AUTH_AGREEMENT_TEMPLATE.CEC_TEMPLATE_CONTENT IS '协议内容';
COMMENT ON COLUMN IM_AUTH_AGREEMENT_TEMPLATE.CEC_TEMPLATE_VERSION IS '版本';
COMMENT ON COLUMN IM_AUTH_AGREEMENT_TEMPLATE.CEC_TEMPLATE_STATUS IS '状态';
COMMENT ON COLUMN IM_AUTH_AGREEMENT_TEMPLATE.CEC_FILE_NAME IS '套版文件名';
COMMENT ON COLUMN IM_AUTH_AGREEMENT_TEMPLATE.CEC_FILE_DATA IS '套版文件Base64';
CREATE INDEX IDX_AGRTPL_TYPE ON IM_AUTH_AGREEMENT_TEMPLATE (CEC_AUTH_TYPE);

-- 授权签章上传记录(可研 3.2.2.1.1.3.3.2:上传行为 + 格式校验 + 签章有效性验证结果)
CREATE TABLE IM_AUTH_SEAL_UPLOAD_LOG (
  CEC_LOG_ID        VARCHAR(64)  NOT NULL,
  CEC_AGREEMENT_ID  VARCHAR(64),
  CEC_UPLOADER_ROLE VARCHAR(50),
  CEC_FILE_NAME     VARCHAR(300),
  CEC_FILE_DATA     CLOB,
  CEC_FORMAT_OK     SMALLINT,
  CEC_SEAL_VALID    SMALLINT,
  CEC_VERIFY_RESULT VARCHAR(500),
  CEC_UPLOAD_TIME   TIMESTAMP,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
);
COMMENT ON TABLE IM_AUTH_SEAL_UPLOAD_LOG IS '授权签章上传记录';
COMMENT ON COLUMN IM_AUTH_SEAL_UPLOAD_LOG.CEC_LOG_ID IS '记录ID';
COMMENT ON COLUMN IM_AUTH_SEAL_UPLOAD_LOG.CEC_AGREEMENT_ID IS '协议ID';
COMMENT ON COLUMN IM_AUTH_SEAL_UPLOAD_LOG.CEC_UPLOADER_ROLE IS '上传角色(授权方/被授权方)';
COMMENT ON COLUMN IM_AUTH_SEAL_UPLOAD_LOG.CEC_FILE_NAME IS '签章文件名';
COMMENT ON COLUMN IM_AUTH_SEAL_UPLOAD_LOG.CEC_FILE_DATA IS '签章文件Base64';
COMMENT ON COLUMN IM_AUTH_SEAL_UPLOAD_LOG.CEC_FORMAT_OK IS '格式校验是否通过';
COMMENT ON COLUMN IM_AUTH_SEAL_UPLOAD_LOG.CEC_SEAL_VALID IS '签章有效性是否通过';
COMMENT ON COLUMN IM_AUTH_SEAL_UPLOAD_LOG.CEC_VERIFY_RESULT IS '验证结果';
COMMENT ON COLUMN IM_AUTH_SEAL_UPLOAD_LOG.CEC_UPLOAD_TIME IS '上传时间';
CREATE INDEX IDX_SEALLOG_AGR ON IM_AUTH_SEAL_UPLOAD_LOG (CEC_AGREEMENT_ID);

-- 授权协议审核记录(可研 3.2.2.1.1.3.3.3:审核人/结论/意见/时间)
CREATE TABLE IM_AUTH_AGR_REVIEW_LOG (
  CEC_LOG_ID       VARCHAR(64)  NOT NULL,
  CEC_AGREEMENT_ID VARCHAR(64),
  CEC_AGREEMENT_NO VARCHAR(64),
  CEC_REVIEWER     VARCHAR(100),
  CEC_RESULT       VARCHAR(50),
  CEC_OPINION      VARCHAR(2000),
  CEC_REVIEW_TIME  TIMESTAMP,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE  VARCHAR(32),
  CEC_CREATOR_ID   VARCHAR(64),
  CEC_CREATE_TIME  TIMESTAMP,
  CEC_UPDATER_ID   VARCHAR(64),
  CEC_UPDATE_TIME  TIMESTAMP,
  CEC_DEL_FLAG     INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
);
COMMENT ON TABLE IM_AUTH_AGR_REVIEW_LOG IS '授权协议审核记录';
COMMENT ON COLUMN IM_AUTH_AGR_REVIEW_LOG.CEC_LOG_ID IS '记录ID';
COMMENT ON COLUMN IM_AUTH_AGR_REVIEW_LOG.CEC_AGREEMENT_ID IS '协议ID';
COMMENT ON COLUMN IM_AUTH_AGR_REVIEW_LOG.CEC_AGREEMENT_NO IS '协议编号';
COMMENT ON COLUMN IM_AUTH_AGR_REVIEW_LOG.CEC_REVIEWER IS '审核人';
COMMENT ON COLUMN IM_AUTH_AGR_REVIEW_LOG.CEC_RESULT IS '审核结论';
COMMENT ON COLUMN IM_AUTH_AGR_REVIEW_LOG.CEC_OPINION IS '审核意见';
COMMENT ON COLUMN IM_AUTH_AGR_REVIEW_LOG.CEC_REVIEW_TIME IS '审核时间';
CREATE INDEX IDX_AGRREVIEW_AGR ON IM_AUTH_AGR_REVIEW_LOG (CEC_AGREEMENT_ID);

-- 授权协议存档审计日志(可研 3.2.2.1.1.3.3.4:归档/查看/下载 访问留痕,可追溯)
CREATE TABLE IM_AUTH_ARCHIVE_LOG (
  CEC_LOG_ID       VARCHAR(64)  NOT NULL,
  CEC_AGREEMENT_ID VARCHAR(64),
  CEC_AGREEMENT_NO VARCHAR(64),
  CEC_ACTION       VARCHAR(50),
  CEC_OPERATOR     VARCHAR(100),
  CEC_OPERATE_TIME TIMESTAMP,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE  VARCHAR(32),
  CEC_CREATOR_ID   VARCHAR(64),
  CEC_CREATE_TIME  TIMESTAMP,
  CEC_UPDATER_ID   VARCHAR(64),
  CEC_UPDATE_TIME  TIMESTAMP,
  CEC_DEL_FLAG     INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
);
COMMENT ON TABLE IM_AUTH_ARCHIVE_LOG IS '授权协议存档审计日志';
COMMENT ON COLUMN IM_AUTH_ARCHIVE_LOG.CEC_LOG_ID IS '日志ID';
COMMENT ON COLUMN IM_AUTH_ARCHIVE_LOG.CEC_AGREEMENT_ID IS '协议ID';
COMMENT ON COLUMN IM_AUTH_ARCHIVE_LOG.CEC_AGREEMENT_NO IS '协议编号';
COMMENT ON COLUMN IM_AUTH_ARCHIVE_LOG.CEC_ACTION IS '操作(归档/查看/下载)';
COMMENT ON COLUMN IM_AUTH_ARCHIVE_LOG.CEC_OPERATOR IS '操作人';
COMMENT ON COLUMN IM_AUTH_ARCHIVE_LOG.CEC_OPERATE_TIME IS '操作时间';
CREATE INDEX IDX_ARCHLOG_AGR ON IM_AUTH_ARCHIVE_LOG (CEC_AGREEMENT_ID);

-- 违规追责记录(监测联动熔断暂停授权时建账,附录F 3.4.5)
CREATE TABLE IM_AUTH_ACCOUNTABILITY (
  CEC_ACCOUNT_ID        VARCHAR(64)  NOT NULL,
  CEC_CERT_ID           VARCHAR(64),
  CEC_ASSET_ID          VARCHAR(64),
  CEC_GRANTEE_ORG       VARCHAR(255),
  CEC_VIOLATION_TYPE    VARCHAR(100),
  CEC_SOURCE_ALERT_ID   VARCHAR(64),
  CEC_REASON            VARCHAR(1000),
  CEC_HANDLE_STATUS     VARCHAR(50),
  CEC_RESPONSIBLE_PARTY VARCHAR(255),
  CEC_HANDLE_FEEDBACK   VARCHAR(1000),
  CEC_HANDLE_TIME       TIMESTAMP,
  CEC_PROVINCE_CODE     VARCHAR(32),
  CEC_BUREAU_CODE       VARCHAR(32),
  CEC_CREATOR_ID        VARCHAR(64),
  CEC_CREATE_TIME       TIMESTAMP,
  CEC_UPDATER_ID        VARCHAR(64),
  CEC_UPDATE_TIME       TIMESTAMP,
  CEC_DEL_FLAG          INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ACCOUNT_ID)
);
COMMENT ON TABLE IM_AUTH_ACCOUNTABILITY IS '违规追责记录';
COMMENT ON COLUMN IM_AUTH_ACCOUNTABILITY.CEC_ACCOUNT_ID IS '追责ID';
COMMENT ON COLUMN IM_AUTH_ACCOUNTABILITY.CEC_CERT_ID IS '证书ID';
COMMENT ON COLUMN IM_AUTH_ACCOUNTABILITY.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_AUTH_ACCOUNTABILITY.CEC_GRANTEE_ORG IS '被授权方';
COMMENT ON COLUMN IM_AUTH_ACCOUNTABILITY.CEC_VIOLATION_TYPE IS '违规类型';
COMMENT ON COLUMN IM_AUTH_ACCOUNTABILITY.CEC_SOURCE_ALERT_ID IS '来源预警ID';
COMMENT ON COLUMN IM_AUTH_ACCOUNTABILITY.CEC_REASON IS '事由';
COMMENT ON COLUMN IM_AUTH_ACCOUNTABILITY.CEC_HANDLE_STATUS IS '处理状态';
COMMENT ON COLUMN IM_AUTH_ACCOUNTABILITY.CEC_RESPONSIBLE_PARTY IS '责任方';
COMMENT ON COLUMN IM_AUTH_ACCOUNTABILITY.CEC_HANDLE_FEEDBACK IS '处理反馈';
COMMENT ON COLUMN IM_AUTH_ACCOUNTABILITY.CEC_HANDLE_TIME IS '处理时间';
CREATE INDEX IDX_ACC_CERT ON IM_AUTH_ACCOUNTABILITY (CEC_CERT_ID);

-- 对外数据经营权授权备案(附录G / 附录F §3.4.6:仅经营权对外授权需备案)
CREATE TABLE IM_AUTH_FILING (
  CEC_FILING_ID     VARCHAR(64)  NOT NULL,
  CEC_FILING_NO     VARCHAR(64),
  CEC_AGREEMENT_ID  VARCHAR(64),
  CEC_APPLY_ID      VARCHAR(64),
  CEC_FILING_ORG    VARCHAR(255),
  CEC_GRANTEE_ORG   VARCHAR(255),
  CEC_RIGHT_TYPE    VARCHAR(100),
  CEC_FILING_STATUS VARCHAR(50),
  CEC_FILING_TIME   TIMESTAMP,
  CEC_REMARK        VARCHAR(1000),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_FILING_ID)
);
COMMENT ON TABLE IM_AUTH_FILING IS '对外经营权授权备案(附录G)';
COMMENT ON COLUMN IM_AUTH_FILING.CEC_FILING_ID IS '备案ID';
COMMENT ON COLUMN IM_AUTH_FILING.CEC_FILING_NO IS '备案编号';
COMMENT ON COLUMN IM_AUTH_FILING.CEC_AGREEMENT_ID IS '关联运营授权协议(附录D)';
COMMENT ON COLUMN IM_AUTH_FILING.CEC_APPLY_ID IS '关联授权申请';
COMMENT ON COLUMN IM_AUTH_FILING.CEC_FILING_ORG IS '备案单位(分子公司)';
COMMENT ON COLUMN IM_AUTH_FILING.CEC_GRANTEE_ORG IS '被授权方';
COMMENT ON COLUMN IM_AUTH_FILING.CEC_RIGHT_TYPE IS '产权类型(经营权)';
COMMENT ON COLUMN IM_AUTH_FILING.CEC_FILING_STATUS IS '备案状态(待备案/已备案)';
COMMENT ON COLUMN IM_AUTH_FILING.CEC_FILING_TIME IS '备案时间';
COMMENT ON COLUMN IM_AUTH_FILING.CEC_REMARK IS '备注';
CREATE INDEX IDX_FILING_STATUS ON IM_AUTH_FILING (CEC_FILING_STATUS);

-- 确权申请-表级数据清单(M02)
CREATE TABLE IM_CONFIRM_TABLE_ITEM (
  CEC_ITEM_ID       VARCHAR(64) NOT NULL,
  CEC_APPLY_ID      VARCHAR(64),
  CEC_INSTANCE_NAME VARCHAR(120),
  CEC_SCHEMA_NAME   VARCHAR(120),
  CEC_TABLE_CODE    VARCHAR(150),
  CEC_TABLE_NAME    VARCHAR(200),
  CEC_TABLE_COMMENT VARCHAR(500),
  CEC_SECRET_LEVEL  VARCHAR(20),
  CEC_SOURCE_TYPE   VARCHAR(50),
  CEC_SOURCE_SUBJECT VARCHAR(200),
  CEC_SOURCE_DESC   VARCHAR(500),
  CEC_G_FLAG        VARCHAR(4),
  CEC_G_SUBJECT     VARCHAR(300),
  CEC_H_FLAG        VARCHAR(4),
  CEC_H_SUBJECT     VARCHAR(300),
  CEC_I_FLAG        VARCHAR(4),
  CEC_I_SUBJECT     VARCHAR(300),
  CEC_J_FLAG        VARCHAR(4),
  CEC_J_SUBJECT     VARCHAR(300),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ITEM_ID)
);
COMMENT ON TABLE IM_CONFIRM_TABLE_ITEM IS '确权申请-表级数据清单(M02)';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_ITEM_ID IS '清单项ID';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_INSTANCE_NAME IS '实例名或TNS';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_SCHEMA_NAME IS 'schema/模式名称';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_TABLE_CODE IS '表代码';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_TABLE_NAME IS '表名称';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_TABLE_COMMENT IS '表注释';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_SECRET_LEVEL IS '密级(不涉密/核心商密/普通商密/工作秘密/敏感信息)';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_SOURCE_TYPE IS '来源判定(A-F)';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_SOURCE_SUBJECT IS '来源主体名称';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_SOURCE_DESC IS '来源说明';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_G_FLAG IS 'G行政监管(是/否)';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_G_SUBJECT IS 'G关联主体说明';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_H_FLAG IS 'H个人隐私(是/否)';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_H_SUBJECT IS 'H关联主体说明';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_I_FLAG IS 'I第三方商密(是/否)';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_I_SUBJECT IS 'I关联主体说明';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_J_FLAG IS 'J其他协议(是/否)';
COMMENT ON COLUMN IM_CONFIRM_TABLE_ITEM.CEC_J_SUBJECT IS 'J关联主体说明';
CREATE INDEX IDX_CTI_APPLY ON IM_CONFIRM_TABLE_ITEM (CEC_APPLY_ID);

-- 系统用户(内建认证+RBAC)
CREATE TABLE IM_SYS_USER (
  CEC_USER_ID       VARCHAR(64)  NOT NULL,
  CEC_USERNAME      VARCHAR(64)  NOT NULL,
  CEC_PASSWORD_HASH VARCHAR(128),
  CEC_REAL_NAME     VARCHAR(64),
  CEC_ROLE          VARCHAR(32),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_STATUS        VARCHAR(16)  DEFAULT '启用',
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT DEFAULT 0,
  PRIMARY KEY (CEC_USER_ID)
);
CREATE UNIQUE INDEX uk_username ON IM_SYS_USER (CEC_USERNAME);
COMMENT ON TABLE IM_SYS_USER IS '系统用户(内建认证+RBAC)';
COMMENT ON COLUMN IM_SYS_USER.CEC_USER_ID IS '用户ID';
COMMENT ON COLUMN IM_SYS_USER.CEC_USERNAME IS '登录名';
COMMENT ON COLUMN IM_SYS_USER.CEC_PASSWORD_HASH IS '密码SM3哈希';
COMMENT ON COLUMN IM_SYS_USER.CEC_REAL_NAME IS '姓名';
COMMENT ON COLUMN IM_SYS_USER.CEC_ROLE IS '角色(apply/review/admin/view/all)';
COMMENT ON COLUMN IM_SYS_USER.CEC_PROVINCE_CODE IS '省公司代码';
COMMENT ON COLUMN IM_SYS_USER.CEC_STATUS IS '状态';

-- 系统操作日志(系统管理:登录 + 用户管理类操作留痕)
CREATE TABLE IM_SYS_OPLOG (
  CEC_LOG_ID        VARCHAR(64)  NOT NULL,
  CEC_USER_ID       VARCHAR(64),
  CEC_USER_NAME     VARCHAR(64),
  CEC_ACTION        VARCHAR(50),
  CEC_TARGET        VARCHAR(255),
  CEC_DETAIL        VARCHAR(1000),
  CEC_IP            VARCHAR(64),
  CEC_RESULT        VARCHAR(20),
  CEC_CREATE_TIME   TIMESTAMP,
  PRIMARY KEY (CEC_LOG_ID)
);
COMMENT ON TABLE IM_SYS_OPLOG IS '系统操作日志';

-- =====================================================================
-- 完。60 张表。测试数据见 03_data_dm.sql
-- =====================================================================
