-- ============================================================================
-- 智能确权辅助工具(aitool) MySQL 库表脚本
-- 工具为独立模块:六张 IM_AIT_* 表自包含;与确权主流程仅通过 CEC_APPLY_ID 弱关联
-- (applyId 可为空,不建外键,不依赖主库任何表)。
-- 字符集 utf8mb4;与 dpr-confirm-service prod profile(MySQL)兼容。
-- 提取自 mysql/01_schema.sql(与 H2 dev 结构同步,含历次扩列:
--  复核标记/可信度/原文定位/AI预测/RAG引用/权益分割方案 等)。
-- ============================================================================

CREATE DATABASE IF NOT EXISTS prm DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE prm;

-- ① 材料:上传文件元数据+正文(SM3哈希/解析状态/进度/失败原因分类)
CREATE TABLE IF NOT EXISTS IM_AIT_MATERIAL (
  CEC_MATERIAL_ID   VARCHAR(64) NOT NULL COMMENT '材料ID',
  CEC_BATCH_NO      VARCHAR(64) COMMENT '批次号',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '关联申请',
  CEC_FILE_NAME     VARCHAR(500) COMMENT '文件名',
  CEC_FILE_TYPE     VARCHAR(20) COMMENT '文件类型',
  CEC_FILE_HASH     VARCHAR(64) COMMENT '文件指纹',
  CEC_SIZE_KB       BIGINT      COMMENT '大小KB',
  CEC_PARSE_STATUS  VARCHAR(20) COMMENT '解析状态',
  CEC_FAIL_REASON   VARCHAR(1000) COMMENT '失败原因',
  CEC_PROGRESS      INT DEFAULT 0 COMMENT '进度',
  CEC_STORAGE_PATH  VARCHAR(500) COMMENT '存储路径',
  CEC_CONTENT       TEXT        COMMENT '抽取正文',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_MATERIAL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-上传材料';

-- ② 解析结果:5要素抽取+印章交叉校验+复核标记+材料可信度
CREATE TABLE IF NOT EXISTS IM_AIT_PARSE_RESULT (
  CEC_PARSE_ID      VARCHAR(64) NOT NULL COMMENT '解析ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_RIGHT_SUBJECT VARCHAR(500) COMMENT '权利主体',
  CEC_RIGHT_OBJECT  VARCHAR(500) COMMENT '权利客体',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '产权类型',
  CEC_RIGHT_TERM    VARCHAR(100) COMMENT '权利期限',
  CEC_AUTH_SCOPE    VARCHAR(500) COMMENT '授权范围',
  CEC_DATA_SOURCE   VARCHAR(100) COMMENT '数据来源',
  CEC_SENSITIVE_TYPE VARCHAR(100) COMMENT '敏感类型',
  CEC_SEAL_VALID    VARCHAR(20) COMMENT '签章有效',
  CEC_SEAL_DESC     VARCHAR(500) COMMENT '签章说明',
  CEC_CONFIDENCE    DOUBLE      COMMENT '置信度',
  CEC_REVIEW_STATUS VARCHAR(50) COMMENT '复核标记(自动通过/需人工复核,阈值0.95)',
  CEC_TRUST_SCORE   INT         COMMENT '材料可信度评分0-100(印章交叉校验+置信度+要素完整性)',
  CEC_TRUST_LEVEL   VARCHAR(50) COMMENT '材料可信度评级(可信/存疑/不可信)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_PARSE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-解析要素';

-- ③ 表单比对:材料值vs申请表单值+差异类型+原文定位(offset/snippet)
CREATE TABLE IF NOT EXISTS IM_AIT_COMPARE (
  CEC_COMPARE_ID    VARCHAR(64) NOT NULL COMMENT '比对ID',
  CEC_PARSE_ID      VARCHAR(64) COMMENT '解析ID',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '申请ID',
  CEC_FIELD         VARCHAR(100) COMMENT '字段',
  CEC_MATERIAL_VALUE VARCHAR(1000) COMMENT '材料值',
  CEC_FORM_VALUE    VARCHAR(1000) COMMENT '表单值',
  CEC_DIFF_TYPE     VARCHAR(20) COMMENT '差异类型',
  CEC_SOURCE_OFFSET INT          COMMENT '材料值在原始正文的字符偏移(-1=未定位/图片)',
  CEC_SOURCE_SNIPPET VARCHAR(500) COMMENT '原始正文定位上下文片段',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_COMPARE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-材料表单比对';

-- ④ 权属主张:知识图谱节点(主体/类型/范围/排他/来源:历史确权|当前申请|法规政策|证明材料)
CREATE TABLE IF NOT EXISTS IM_AIT_KG_CLAIM (
  CEC_CLAIM_ID      VARCHAR(64) NOT NULL COMMENT '主张ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_SUBJECT       VARCHAR(255) COMMENT '主体',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '产权类型',
  CEC_AUTH_SCOPE    VARCHAR(500) COMMENT '授权范围',
  CEC_VALID_DATE    DATETIME    COMMENT '有效期',
  CEC_EXCLUSIVE     TINYINT(1)  COMMENT '是否独占',
  CEC_SOURCE_TYPE   VARCHAR(50) COMMENT '来源类型',
  CEC_REMARK        VARCHAR(1000) COMMENT '备注',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CLAIM_ID),
  KEY IDX_KG_ASSET (CEC_ASSET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-权属主张(KG)';

-- ⑤ 权属冲突:主体/范围/时效/历史记录四类+风险等级+处置建议
CREATE TABLE IF NOT EXISTS IM_AIT_CONFLICT (
  CEC_CONFLICT_ID   VARCHAR(64) NOT NULL COMMENT '冲突ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_CONFLICT_TYPE VARCHAR(50) COMMENT '冲突类型',
  CEC_CONFLICT_SOURCE VARCHAR(255) COMMENT '冲突来源',
  CEC_CONFLICT_DESC VARCHAR(2000) COMMENT '冲突描述',
  CEC_IMPACT_SCOPE  VARCHAR(1000) COMMENT '影响范围',
  CEC_RISK_LEVEL    VARCHAR(20) COMMENT '风险级别',
  CEC_SUGGESTION    VARCHAR(2000) COMMENT '消解建议',
  CEC_STATUS        VARCHAR(20) COMMENT '状态',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONFLICT_ID),
  KEY IDX_CFL_ASSET (CEC_ASSET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-权属冲突';

-- ⑥ 决策建议:4因子加权+预测结论+AI预测对照+RAG建议/引用+权益分割双方案+证据链
CREATE TABLE IF NOT EXISTS IM_AIT_DECISION (
  CEC_DECISION_ID   VARCHAR(64) NOT NULL COMMENT '决策ID',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '申请ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_PREDICTION    VARCHAR(50) COMMENT '预测结论',
  CEC_SCORE         DOUBLE      COMMENT '评分',
  CEC_FACTORS_JSON  TEXT        COMMENT '因子JSON',
  CEC_STRENGTH      VARCHAR(500) COMMENT '优势',
  CEC_WEAKNESS      VARCHAR(500) COMMENT '不足',
  CEC_SPLIT_PLAN    VARCHAR(2000) COMMENT '三权分置建议',
  CEC_SPLIT_PLANS_JSON TEXT       COMMENT '权益分割多方案明细JSON',
  CEC_REASON        VARCHAR(2000) COMMENT '理由',
  CEC_SUPPLEMENT    VARCHAR(1000) COMMENT '补充建议',
  CEC_PENDING_CONFLICTS VARCHAR(1000) COMMENT '待解冲突',
  CEC_RAG_ADVICE    TEXT        COMMENT 'RAG法规建议',
  CEC_AI_PREDICTION VARCHAR(50)  COMMENT 'AI预测结论',
  CEC_RAG_CITATIONS VARCHAR(1000) COMMENT 'RAG法规引用',
  CEC_EVIDENCE_CHAIN VARCHAR(80) COMMENT '存证链',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_DECISION_ID),
  KEY IDX_DEC_APPLY (CEC_APPLY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-确权决策建议';

