-- ============================================================================
-- 智能确权辅助工具(aitool) MySQL 库表脚本
-- 工具为独立模块:全部 IM_AIT_* 表自包含,与确权主流程仅通过 CEC_APPLY_ID 弱关联
-- (applyId 可为空,不建外键,不依赖主库任何表),可随工具独立建库部署。
-- 字符集 utf8mb4;与 dpr-confirm-service prod profile(MySQL)兼容。
-- 提取自 mysql/01_schema.sql(与 H2 dev / dm8 同步);含本次扩展的全部 22 张表
--  (材料解析/多粒度切片/清洗/要素画像/材料管理/知识库/冲突与规则/Agent审核/证据链/批量任务/运行日志)。
-- ============================================================================

CREATE DATABASE IF NOT EXISTS prm DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE prm;

CREATE TABLE IF NOT EXISTS IM_AIT_MATERIAL (
  CEC_MATERIAL_ID   VARCHAR(64) NOT NULL COMMENT '材料ID',
  CEC_BATCH_NO      VARCHAR(64) COMMENT '批次号',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '关联申请',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '关联资产',
  CEC_FILE_NAME     VARCHAR(500) COMMENT '文件名',
  CEC_FILE_TYPE     VARCHAR(20) COMMENT '文件类型',
  CEC_FILE_HASH     VARCHAR(64) COMMENT '文件指纹',
  CEC_SIZE_KB       BIGINT      COMMENT '大小KB',
  CEC_PARSE_STATUS  VARCHAR(20) COMMENT '解析状态',
  CEC_FAIL_REASON   VARCHAR(1000) COMMENT '失败原因',
  CEC_PROGRESS      INT DEFAULT 0 COMMENT '进度',
  CEC_STORAGE_PATH  VARCHAR(500) COMMENT '存储路径',
  CEC_CONTENT       TEXT        COMMENT '抽取正文',
  CEC_CATEGORY      VARCHAR(50) COMMENT '资料类型编码(CEC_DATA_TYPE):01元数据/02制度附件/03授权材料/04合同材料/05来源说明/06确权证明/07其他',
  CEC_DATA_TABLE_REF VARCHAR(255) COMMENT '所属数据表标识(归集关联键)',
  CEC_LAYOUT_JSON   TEXT        COMMENT '版面分析结果JSON(印章/表格/标题/分栏/页类型)',
  CEC_DUPLICATE_OF  VARCHAR(64) COMMENT '重复检测命中的原材料ID',
  CEC_PAGE_COUNT    INT         COMMENT '页数',
  CEC_OCR_USED      INT DEFAULT 0 COMMENT '是否经OCR(0否1是)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_MATERIAL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-上传材料';

CREATE TABLE IF NOT EXISTS IM_AIT_DOC_SEGMENT (
  CEC_SEGMENT_ID    VARCHAR(64) NOT NULL COMMENT '片段ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_GRANULARITY   VARCHAR(20) COMMENT '粒度(PAGE/PARAGRAPH/CELL/TABLE/TITLE)',
  CEC_PAGE_NO       INT         COMMENT '页码',
  CEC_SEG_INDEX     INT         COMMENT '片段序号',
  CEC_SHEET_NAME    VARCHAR(100) COMMENT '工作表名(Excel)',
  CEC_ROW_NUM       INT         COMMENT '行号(单元格粒度)',
  CEC_COL_NUM       INT         COMMENT '列号(单元格粒度)',
  CEC_CONTENT       TEXT        COMMENT '片段内容',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_SEGMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-多粒度解析片段';

CREATE TABLE IF NOT EXISTS IM_AIT_CLEAN_LOG (
  CEC_LOG_ID        VARCHAR(64) NOT NULL COMMENT '日志ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_BATCH_NO      VARCHAR(64) COMMENT '清洗批次',
  CEC_ROW_NO        INT         COMMENT '记录行号',
  CEC_FIELD         VARCHAR(64) COMMENT '模板字段',
  CEC_RAW_KEY       VARCHAR(128) COMMENT '原始字段名',
  CEC_ORIGINAL_VALUE VARCHAR(2000) COMMENT '原始值',
  CEC_RULE          VARCHAR(255) COMMENT '命中清洗规则',
  CEC_CLEANED_VALUE VARCHAR(2000) COMMENT '清洗后值',
  CEC_METHOD        VARCHAR(20) COMMENT '方式(规则/模型/规则+模型)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-清洗日志';

CREATE TABLE IF NOT EXISTS IM_AIT_AUDIT_BASE (
  CEC_AUDIT_ID      VARCHAR(64) NOT NULL COMMENT '底表ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_BATCH_NO      VARCHAR(64) COMMENT '清洗批次',
  CEC_ROW_NO        INT         COMMENT '记录行号',
  CEC_TEMPLATE_FIELD VARCHAR(64) COMMENT '统一模板字段',
  CEC_FIELD_LABEL   VARCHAR(64) COMMENT '字段中文名',
  CEC_RAW_VALUE     VARCHAR(2000) COMMENT '原始值',
  CEC_CLEAN_VALUE   VARCHAR(2000) COMMENT '清洗标准化后值',
  CEC_STATUS        VARCHAR(20) COMMENT '状态(正常/缺失/冲突/异常/重复)',
  CEC_ISSUE         VARCHAR(500) COMMENT '问题描述',
  CEC_SUGGESTION    VARCHAR(500) COMMENT '待补正建议',
  CEC_DATA_TABLE_REF VARCHAR(255) COMMENT '数据表关联索引',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_AUDIT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-统一审核底表';

CREATE TABLE IF NOT EXISTS IM_AIT_PROFILE (
  CEC_PROFILE_ID    VARCHAR(64) NOT NULL COMMENT '画像ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_DATA_TABLE_REF VARCHAR(255) COMMENT '数据表关联索引',
  CEC_LEVEL         VARCHAR(20) COMMENT '层级(表级/附件级)',
  CEC_SOURCE_METHOD VARCHAR(50) COMMENT '数据来源方式',
  CEC_SOURCE_METHOD_BY VARCHAR(20) COMMENT '来源方式判定方式(规则/模型)',
  CEC_DATA_FEATURES VARCHAR(500) COMMENT '数据特征(多值)',
  CEC_ELEMENTS_JSON TEXT COMMENT '结构化确权画像JSON',
  CEC_CONFIDENCE    DOUBLE COMMENT '置信度',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_PROFILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-确权画像';

CREATE TABLE IF NOT EXISTS IM_AIT_PROFILE_SUBJECT (
  CEC_SUBJECT_ID    VARCHAR(64) NOT NULL COMMENT '主体ID',
  CEC_PROFILE_ID    VARCHAR(64) COMMENT '画像ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_SUBJECT_ROLE  VARCHAR(40) COMMENT '主体角色(来源/授权/使用/加工/共享对象)',
  CEC_SUBJECT_NAME  VARCHAR(500) COMMENT '主体名称',
  CEC_METHOD        VARCHAR(20) COMMENT '识别方式(规则/模型)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_SUBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-关键主体';

CREATE TABLE IF NOT EXISTS IM_AIT_CONSTRAINT (
  CEC_CONSTRAINT_ID VARCHAR(64) NOT NULL COMMENT '约束ID',
  CEC_PROFILE_ID    VARCHAR(64) COMMENT '画像ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_CONSTRAINT_TYPE VARCHAR(40) COMMENT '约束类型(授权范围/使用边界/共享限制/保留期限/脱敏要求)',
  CEC_CONSTRAINT_VALUE VARCHAR(1000) COMMENT '约束内容',
  CEC_METHOD        VARCHAR(20) COMMENT '识别方式(规则/模型)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONSTRAINT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-约束信息';

CREATE TABLE IF NOT EXISTS IM_AIT_PARSE_RECORD (
  CEC_RECORD_ID     VARCHAR(64) NOT NULL COMMENT '记录ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_FILE_NAME     VARCHAR(500) COMMENT '文档名称',
  CEC_BATCH_NO      VARCHAR(64) COMMENT '批次',
  CEC_FIELD         VARCHAR(64) COMMENT '提取字段',
  CEC_FIELD_VALUE   VARCHAR(2000) COMMENT '提取值',
  CEC_CONFIDENCE    DOUBLE COMMENT '置信度',
  CEC_OPERATOR_ID   VARCHAR(64) COMMENT '操作人ID',
  CEC_OPERATOR_NAME VARCHAR(64) COMMENT '操作人',
  CEC_PARSE_TIME    DATETIME COMMENT '解析时间',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RECORD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-解析记录档';

CREATE TABLE IF NOT EXISTS IM_AIT_DOC_TEMPLATE (
  CEC_TEMPLATE_ID   VARCHAR(64) NOT NULL COMMENT '模板ID',
  CEC_TEMPLATE_TYPE VARCHAR(50) COMMENT '模板类型(确权书/授权函/权属证明等)',
  CEC_TEMPLATE_NAME VARCHAR(255) COMMENT '模板名称',
  CEC_VERSION       VARCHAR(20) COMMENT '版本',
  CEC_CONTENT       TEXT COMMENT '在线编辑正文',
  CEC_FILE_NAME     VARCHAR(300) COMMENT '附件名',
  CEC_FILE_DATA     TEXT COMMENT '附件Base64',
  CEC_IS_LATEST     TINYINT(1) DEFAULT 1 COMMENT '是否最新版',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TEMPLATE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-资料模板库';

CREATE TABLE IF NOT EXISTS IM_AIT_PARSE_CONFIG (
  CEC_CONFIG_ID     VARCHAR(64) NOT NULL COMMENT '配置ID',
  CEC_SCENE         VARCHAR(50) COMMENT '业务场景',
  CEC_FIELD_MAPPING_JSON TEXT COMMENT '字段映射规则JSON',
  CEC_EXTRACT_LOGIC_JSON TEXT COMMENT '提取逻辑配置JSON',
  CEC_CONFIDENCE_THRESHOLD DOUBLE COMMENT '置信度阈值',
  CEC_ENABLED       INT DEFAULT 1 COMMENT '启用',
  CEC_REMARK        VARCHAR(500) COMMENT '备注',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONFIG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-解析元数据配置';

CREATE TABLE IF NOT EXISTS IM_AIT_KB_DOC (
  CEC_DOC_ID        VARCHAR(64) NOT NULL COMMENT '文档ID',
  CEC_DOC_TYPE      VARCHAR(40) COMMENT '类型(法规/行业标准/内部制度/审核规则/典型案例)',
  CEC_DOMAIN        VARCHAR(40) COMMENT '知识域(数据安全/个人信息保护/网络安全/数据确权等)',
  CEC_TITLE         VARCHAR(300) COMMENT '标题',
  CEC_SOURCE        VARCHAR(300) COMMENT '来源',
  CEC_EFFECTIVE_DATE VARCHAR(20) COMMENT '生效日期',
  CEC_SCOPE         VARCHAR(500) COMMENT '适用范围',
  CEC_VERSION       VARCHAR(20) COMMENT '版本',
  CEC_IS_LATEST     TINYINT(1) DEFAULT 1 COMMENT '是否最新',
  CEC_STATUS        VARCHAR(20) COMMENT '状态(有效/失效)',
  CEC_CONTENT       TEXT COMMENT '全文',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_DOC_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-知识库文档';

CREATE TABLE IF NOT EXISTS IM_AIT_KB_CHUNK (
  CEC_CHUNK_ID      VARCHAR(64) NOT NULL COMMENT '切片ID',
  CEC_DOC_ID        VARCHAR(64) COMMENT '文档ID',
  CEC_DOC_TYPE      VARCHAR(40) COMMENT '类型',
  CEC_DOMAIN        VARCHAR(40) COMMENT '知识域',
  CEC_TITLE         VARCHAR(300) COMMENT '文档标题',
  CEC_CLAUSE_NO     VARCHAR(50) COMMENT '条款编号',
  CEC_TAGS          VARCHAR(500) COMMENT '标签',
  CEC_CONTENT       TEXT COMMENT '切片正文',
  CEC_VECTOR_JSON   TEXT COMMENT '向量JSON',
  CEC_VECTOR_DIM    INT COMMENT '向量维度',
  CEC_EFFECTIVE_DATE VARCHAR(20) COMMENT '生效日期',
  CEC_SCOPE         VARCHAR(500) COMMENT '适用范围',
  CEC_STATUS        VARCHAR(20) COMMENT '状态(有效/失效)',
  CEC_SEQ           INT COMMENT '序号',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CHUNK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-知识库切片';

-- 材料解析要素
CREATE TABLE IF NOT EXISTS IM_AIT_PARSE_RESULT (
  CEC_PARSE_ID      VARCHAR(64) NOT NULL COMMENT '解析ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_RIGHT_SUBJECT VARCHAR(500) COMMENT '权利主体',
  CEC_RIGHT_OBJECT  VARCHAR(500) COMMENT '权利客体',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '产权类型',
  CEC_RIGHT_TERM    VARCHAR(100) COMMENT '权利期限',
  CEC_AUTH_SCOPE    VARCHAR(500) COMMENT '授权范围',
  CEC_DATA_SOURCE   VARCHAR(100) COMMENT '数据来源',
  CEC_SENSITIVE_TYPE VARCHAR(100) COMMENT '敏感类型',
  CEC_SEAL_VALID    VARCHAR(20) COMMENT '签章有效',
  CEC_SEAL_DESC     VARCHAR(500) COMMENT '签章说明',
  CEC_CONFIDENCE    DOUBLE      COMMENT '置信度',
  CEC_REVIEW_STATUS VARCHAR(50) COMMENT '复核标记(自动通过/需人工复核,阈值0.95)',
  CEC_TRUST_SCORE   INT         COMMENT '材料可信度评分0-100(印章交叉校验+置信度+要素完整性)',
  CEC_TRUST_LEVEL   VARCHAR(50) COMMENT '材料可信度评级(可信/存疑/不可信)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_PARSE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-解析要素';

-- 材料与表单比对
CREATE TABLE IF NOT EXISTS IM_AIT_COMPARE (
  CEC_COMPARE_ID    VARCHAR(64) NOT NULL COMMENT '比对ID',
  CEC_PARSE_ID      VARCHAR(64) COMMENT '解析ID',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '申请ID',
  CEC_FIELD         VARCHAR(100) COMMENT '字段',
  CEC_MATERIAL_VALUE VARCHAR(1000) COMMENT '材料值',
  CEC_FORM_VALUE    VARCHAR(1000) COMMENT '表单值',
  CEC_DIFF_TYPE     VARCHAR(20) COMMENT '差异类型',
  CEC_SOURCE_OFFSET INT          COMMENT '材料值在原始正文的字符偏移(-1=未定位/图片)',
  CEC_SOURCE_SNIPPET VARCHAR(500) COMMENT '原始正文定位上下文片段',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_COMPARE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-材料表单比对';

-- 权属主张(知识图谱)
CREATE TABLE IF NOT EXISTS IM_AIT_KG_CLAIM (
  CEC_CLAIM_ID      VARCHAR(64) NOT NULL COMMENT '主张ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_SUBJECT       VARCHAR(255) COMMENT '主体',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '产权类型',
  CEC_AUTH_SCOPE    VARCHAR(500) COMMENT '授权范围',
  CEC_VALID_DATE    DATETIME    COMMENT '有效期',
  CEC_EXCLUSIVE     TINYINT(1)  COMMENT '是否独占',
  CEC_SOURCE_TYPE   VARCHAR(50) COMMENT '来源类型',
  CEC_REMARK        VARCHAR(1000) COMMENT '备注',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CLAIM_ID),
  KEY IDX_KG_ASSET (CEC_ASSET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-权属主张(KG)';

-- 权属冲突
CREATE TABLE IF NOT EXISTS IM_AIT_CONFLICT (
  CEC_CONFLICT_ID   VARCHAR(64) NOT NULL COMMENT '冲突ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_CONFLICT_TYPE VARCHAR(50) COMMENT '冲突类型',
  CEC_CONFLICT_SOURCE VARCHAR(255) COMMENT '冲突来源',
  CEC_CONFLICT_DESC VARCHAR(2000) COMMENT '冲突描述',
  CEC_IMPACT_SCOPE  VARCHAR(1000) COMMENT '影响范围',
  CEC_RISK_LEVEL    VARCHAR(20) COMMENT '风险级别',
  CEC_SUGGESTION    VARCHAR(2000) COMMENT '消解建议',
  CEC_STATUS        VARCHAR(20) COMMENT '状态',
  CEC_RELATED_RECORD_NO VARCHAR(255) COMMENT '关联历史确权记录编号',
  CEC_CONFLICT_FIELDS VARCHAR(255) COMMENT '冲突字段',
  CEC_CLAUSE_REF    VARCHAR(500) COMMENT '相关协议/条款引用',
  CEC_LEGAL_RISK    VARCHAR(40) COMMENT '法律风险等级',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONFLICT_ID),
  KEY IDX_CFL_ASSET (CEC_ASSET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-权属冲突';

CREATE TABLE IF NOT EXISTS IM_AIT_CONFLICT_RULE (
  CEC_RULE_ID       VARCHAR(64) NOT NULL COMMENT '规则ID',
  CEC_RULE_TYPE     VARCHAR(40) COMMENT '规则类型(主体冲突/权限重叠/期限交叉/历史记录冲突/类型冲突)',
  CEC_RULE_NAME     VARCHAR(100) COMMENT '规则名称',
  CEC_ENABLED       INT DEFAULT 1 COMMENT '启用',
  CEC_PRIORITY      INT DEFAULT 100 COMMENT '优先级',
  CEC_THRESHOLD     DOUBLE COMMENT '阈值',
  CEC_REMARK        VARCHAR(500) COMMENT '备注',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RULE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-冲突识别规则';

CREATE TABLE IF NOT EXISTS IM_AIT_AUDIT_RESULT (
  CEC_AUDIT_ID      VARCHAR(64) NOT NULL COMMENT '审核ID',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '申请ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_CHANNEL       VARCHAR(20) COMMENT '审核通道(快速通道/深度审核)',
  CEC_DATA_CLASS    VARCHAR(100) COMMENT '数据分类',
  CEC_DATA_GRADE    VARCHAR(40) COMMENT '数据级别',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '权利类型',
  CEC_AUTH_ADVICE   VARCHAR(40) COMMENT '授权建议',
  CEC_AUTH_LEVEL    VARCHAR(40) COMMENT '授权级别',
  CEC_RESTRICTIONS  VARCHAR(1000) COMMENT '限制条件',
  CEC_RISK_LEVEL    VARCHAR(20) COMMENT '风险等级',
  CEC_SUPPLEMENT    VARCHAR(1000) COMMENT '补正建议',
  CEC_REASON        VARCHAR(2000) COMMENT '结论理由',
  CEC_CITATIONS     VARCHAR(1000) COMMENT '命中依据',
  CEC_ACTION        VARCHAR(255) COMMENT '建议动作',
  CEC_SCORE         DOUBLE COMMENT '综合评分',
  CEC_STAGE_TRACE_JSON TEXT COMMENT '阶段轨迹JSON',
  CEC_TOOL_TRACE_JSON  TEXT COMMENT '工具调用链JSON',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_AUDIT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-Agent审核结果';

CREATE TABLE IF NOT EXISTS IM_AIT_TASK (
  CEC_TASK_ID       VARCHAR(64) NOT NULL COMMENT '任务ID',
  CEC_TASK_TYPE     VARCHAR(40) COMMENT '任务类型(BATCH_PARSE/BATCH_AUDIT)',
  CEC_TASK_NAME     VARCHAR(200) COMMENT '任务名',
  CEC_ITEMS_JSON    TEXT COMMENT '待处理项ID列表JSON',
  CEC_ITEM_STATE_JSON TEXT COMMENT '逐项状态JSON(断点续跑)',
  CEC_TOTAL         INT DEFAULT 0 COMMENT '总数',
  CEC_DONE          INT DEFAULT 0 COMMENT '完成数',
  CEC_FAILED        INT DEFAULT 0 COMMENT '失败数',
  CEC_STATUS        VARCHAR(20) COMMENT '状态(待运行/运行中/已完成/部分失败/已暂停)',
  CEC_CONCURRENCY   INT DEFAULT 4 COMMENT '并发上限',
  CEC_RETRY_MAX     INT DEFAULT 2 COMMENT '失败重试上限',
  CEC_CURSOR        INT DEFAULT 0 COMMENT '断点位',
  CEC_LAST_ERROR    VARCHAR(1000) COMMENT '最近错误',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TASK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-批量任务';

CREATE TABLE IF NOT EXISTS IM_AIT_RUN_LOG (
  CEC_LOG_ID        VARCHAR(64) NOT NULL COMMENT '日志ID',
  CEC_LOG_TYPE      VARCHAR(20) COMMENT '类型(审计/操作/模型调用/规则命中/告警)',
  CEC_SOURCE        VARCHAR(100) COMMENT '来源',
  CEC_ACTION        VARCHAR(100) COMMENT '动作',
  CEC_DETAIL        VARCHAR(2000) COMMENT '详情',
  CEC_MODEL         VARCHAR(64) COMMENT '模型',
  CEC_DURATION_MS   BIGINT COMMENT '耗时ms',
  CEC_RESULT        VARCHAR(20) COMMENT '结果',
  CEC_TASK_ID       VARCHAR(64) COMMENT '关联任务',
  CEC_LOG_TIME      DATETIME COMMENT '时间',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-统一运行日志';

CREATE TABLE IF NOT EXISTS IM_AIT_EVIDENCE (
  CEC_EVIDENCE_ID   VARCHAR(64) NOT NULL COMMENT '证据ID',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '申请ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_MATERIAL_SNIPPETS_JSON TEXT COMMENT '输入材料片段',
  CEC_KB_HITS_JSON  TEXT COMMENT '知识库命中片段',
  CEC_RULE_HITS_JSON TEXT COMMENT '规则命中项',
  CEC_MODEL_REASON  TEXT COMMENT '大模型判断理由',
  CEC_CONCLUSION    VARCHAR(500) COMMENT '最终结论',
  CEC_SM3_HASH      VARCHAR(80) COMMENT 'SM3留痕',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_EVIDENCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-审核证据链';

-- 确权决策建议
CREATE TABLE IF NOT EXISTS IM_AIT_DECISION (
  CEC_DECISION_ID   VARCHAR(64) NOT NULL COMMENT '决策ID',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '申请ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_PREDICTION    VARCHAR(50) COMMENT '预测结论',
  CEC_SCORE         DOUBLE      COMMENT '评分',
  CEC_FACTORS_JSON  TEXT        COMMENT '因子JSON',
  CEC_STRENGTH      VARCHAR(500) COMMENT '优势',
  CEC_WEAKNESS      VARCHAR(500) COMMENT '不足',
  CEC_SPLIT_PLAN    VARCHAR(2000) COMMENT '三权分置建议',
  CEC_SPLIT_PLANS_JSON TEXT       COMMENT '权益分割多方案明细JSON',
  CEC_REASON        VARCHAR(2000) COMMENT '理由',
  CEC_SUPPLEMENT    VARCHAR(1000) COMMENT '补充建议',
  CEC_PENDING_CONFLICTS VARCHAR(1000) COMMENT '待解冲突',
  CEC_RAG_ADVICE    TEXT        COMMENT 'RAG法规建议',
  CEC_AI_PREDICTION VARCHAR(50)  COMMENT 'AI预测结论',
  CEC_RAG_CITATIONS VARCHAR(1000) COMMENT 'RAG法规引用',
  CEC_EVIDENCE_CHAIN VARCHAR(80) COMMENT '存证链',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_DECISION_ID),
  KEY IDX_DEC_APPLY (CEC_APPLY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-确权决策建议';

-- 完。智能确权辅助工具 IM_AIT_* 全部 22 张表(MySQL)。

-- 1.1.1.1#4 结构化模板对比日志
CREATE TABLE IF NOT EXISTS IM_AIT_TPL_COMPARE (
  CEC_TPL_CMP_ID     VARCHAR(64) COMMENT '对比行ID',
  CEC_MATERIAL_ID    VARCHAR(64) COMMENT '材料ID',
  CEC_BATCH_NO       VARCHAR(64) COMMENT '对比批次',
  CEC_TEMPLATE_NAME  VARCHAR(255) COMMENT '模板名称',
  CEC_ROW_NO         INT COMMENT '行号',
  CEC_TPL_FIELD      VARCHAR(128) COMMENT '模板字段',
  CEC_TPL_VALUE      VARCHAR(2000) COMMENT '模板值',
  CEC_MATERIAL_VALUE VARCHAR(2000) COMMENT '材料抽取值',
  CEC_CONSISTENCY    VARCHAR(20) COMMENT '一致性',
  CEC_SOURCE_LOCATION VARCHAR(1000) COMMENT '材料中所在位置',
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    DATETIME,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    DATETIME,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TPL_CMP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-结构化模板对比日志';
