-- =====================================================================
-- 数据产权管理模块 (IM-DAM-DPR) · MySQL 库表 DDL
-- 数据资产管理平台 V3.6 · 中国南方电网
-- 由 H2(MySQL兼容模式) schema 转换:CLOB→TEXT, TIMESTAMP→DATETIME, BOOLEAN→TINYINT(1)
-- 共 60 张表(在原 41 张基础上,本轮新增 系统管理 IM_SYS_OPLOG + 智能确权辅助工具九大组功能点 18 张 IM_AIT_* 表:
--  多粒度切片/清洗底表与日志/要素画像与五类主体与五类约束/解析记录档/资料模板/解析配置/知识库文档与切片/
--  冲突规则/Agent审核结果/审核证据链/批量任务/统一运行日志;并对 IM_AIT_MATERIAL/IM_AIT_CONFLICT 扩列)
-- 字段前缀 CEC_ 沿用平台规范;CEC_DEL_FLAG 逻辑删除(0=正常,1=已删)
-- 执行:  mysql -u root -p < 01_schema.sql
-- =====================================================================

CREATE DATABASE IF NOT EXISTS prm_dpr
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;
USE prm_dpr;

SET NAMES utf8mb4;

-- =====================================================================
-- 公共 / 共享
-- =====================================================================

-- 区块链存证记录(国密SM3指纹 + 上链回执,确权制卡/授权发证/协议/变更/熔断节点留痕)
CREATE TABLE IF NOT EXISTS IM_DPR_EVIDENCE (
  CEC_EVIDENCE_ID   VARCHAR(64) NOT NULL COMMENT '存证ID',
  CEC_BIZ_TYPE      VARCHAR(50)   COMMENT '业务类型(确权制卡/授权发证/熔断处置...)',
  CEC_BIZ_ID        VARCHAR(64)   COMMENT '业务ID',
  CEC_SUMMARY       VARCHAR(500)  COMMENT '存证摘要',
  CEC_SM3_HASH      VARCHAR(64)   COMMENT 'SM3 指纹',
  CEC_CHAIN_TX_HASH VARCHAR(80)   COMMENT '链上交易哈希',
  CEC_BLOCK_HEIGHT  BIGINT        COMMENT '区块高度',
  CEC_ANCHOR_STATUS VARCHAR(20)   COMMENT '上链状态',
  CEC_EVIDENCE_TIME DATETIME      COMMENT '存证时间',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_EVIDENCE_ID),
  KEY IDX_EVID_BIZ (CEC_BIZ_TYPE, CEC_BIZ_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='区块链存证记录';

-- =====================================================================
-- F-01 产权信息管理 (dpr-ledger-service, 9101)
-- =====================================================================

-- 数据资产信息表(由数据资产管理平台目录同步,确权/树/概览的底座)
CREATE TABLE IF NOT EXISTS IM_DPM_DATA_ASSET_INFO (
  CEC_ASSET_ID         VARCHAR(64)  NOT NULL COMMENT '资产ID',
  CEC_ASSET_NAME       VARCHAR(255) NOT NULL COMMENT '资产名称',
  CEC_ASSET_TYPE       VARCHAR(100) COMMENT '资产类型',
  CEC_SOURCE_OF_ASSETS VARCHAR(255) COMMENT '资产来源',
  CEC_ASSET_STATUS     VARCHAR(50)  COMMENT '资产状态',
  CEC_ASSET_OWNER      VARCHAR(100) COMMENT '资产归属',
  CEC_SUBSIDIARY_NAME  VARCHAR(255) COMMENT '子公司',
  CEC_SYSTEM_NAME      VARCHAR(255) COMMENT '系统名称',
  CEC_SCHEMA_NAME      VARCHAR(255) COMMENT '模式名称',
  CEC_SECURITY_LEVEL   VARCHAR(50)  COMMENT '安全等级',
  CEC_RESP_DEPT        VARCHAR(255) COMMENT '责任部门',
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      DATETIME,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      DATETIME,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ASSET_ID),
  KEY IDX_ASSET_SUB (CEC_SUBSIDIARY_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据资产信息';

-- 产权档案表(一数一档)
CREATE TABLE IF NOT EXISTS IM_PROPERTY_ARCHIVE (
  CEC_ARCHIVE_ID     VARCHAR(64)  NOT NULL COMMENT '档案ID',
  CEC_ASSET_ID       VARCHAR(64)  NOT NULL COMMENT '资产ID',
  CEC_ASSET_NAME     VARCHAR(255) NOT NULL COMMENT '资产名称',
  CEC_RIGHT_TYPE     VARCHAR(255) COMMENT '产权类型(三权分置,可多值顿号拼接:持有权/加工使用权/产品经营权)',
  CEC_RIGHT_SUBJECT  VARCHAR(255) COMMENT '权利主体',
  CEC_RIGHT_OBJECT   VARCHAR(255) COMMENT '权利客体',
  CEC_ACQUIRE_MODE   VARCHAR(100) COMMENT '取得方式',
  CEC_USE_SCOPE      VARCHAR(1000) COMMENT '使用范围',
  CEC_RESP_DEPT      VARCHAR(255) COMMENT '责任部门',
  CEC_VALID_DATE     DATETIME     COMMENT '有效期',
  CEC_CONFIRM_STATUS VARCHAR(50)  COMMENT '确权状态(聚合:未确权/部分确权/已确权)',
  CEC_CONFIRM_DETAIL VARCHAR(255) COMMENT '按权确权明细(持有权:已确权;使用权:未确权;...)',
  CEC_AUTH_STATUS    VARCHAR(50)  COMMENT '授权状态',
  CEC_EQUITY_CARD_ID VARCHAR(64)  COMMENT '权益卡片ID',
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    DATETIME,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    DATETIME,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ARCHIVE_ID),
  KEY IDX_ARC_ASSET (CEC_ASSET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产权档案(一数一档)';

-- 产权变更记录表(由确权/授权审批流事件自动生成,防篡改证据链)
CREATE TABLE IF NOT EXISTS IM_PROPERTY_CHANGE_RECORD (
  CEC_CHANGE_ID     VARCHAR(64)  NOT NULL COMMENT '变更ID',
  CEC_ASSET_ID      VARCHAR(64)  NOT NULL COMMENT '资产ID',
  CEC_CHANGE_TYPE   VARCHAR(100) NOT NULL COMMENT '变更类型',
  CEC_FIELD_NAME    VARCHAR(100) COMMENT '变更字段',
  CEC_BEFORE_VALUE  VARCHAR(2000) COMMENT '变更前',
  CEC_AFTER_VALUE   VARCHAR(2000) COMMENT '变更后',
  CEC_CHANGE_REASON VARCHAR(1000) COMMENT '变更原因',
  CEC_SOURCE_FLOW   VARCHAR(100) COMMENT '来源流程',
  CEC_SOURCE_TICKET VARCHAR(64)  COMMENT '来源单号',
  CEC_OPERATOR_ID   VARCHAR(64)  COMMENT '操作人',
  CEC_CHANGE_TIME   DATETIME     COMMENT '变更时间',
  CEC_CHAIN_HASH    VARCHAR(128) COMMENT '上链哈希',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CHANGE_ID),
  KEY IDX_CHG_ASSET (CEC_ASSET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产权变更记录(防篡改留痕)';

-- 监测规则配置表
CREATE TABLE IF NOT EXISTS IM_MONITOR_RULE (
  CEC_RULE_ID        VARCHAR(64)  NOT NULL COMMENT '规则ID',
  CEC_RULE_NAME      VARCHAR(255) NOT NULL COMMENT '规则名称',
  CEC_RULE_CATEGORY  VARCHAR(100) COMMENT '规则类别',
  CEC_MONITOR_TARGET VARCHAR(255) COMMENT '监测对象',
  CEC_TRIGGER_COND   TEXT         COMMENT '触发条件',
  CEC_THRESHOLD      VARCHAR(500) COMMENT '阈值',
  CEC_PRIORITY       VARCHAR(20)  COMMENT '优先级',
  CEC_NOTIFY_TARGET  VARCHAR(500) COMMENT '通知对象',
  CEC_NOTIFY_CHANNEL VARCHAR(200) COMMENT '通知方式(站内信/邮件/短信/eLink,逗号分隔)',
  CEC_RULE_VERSION   VARCHAR(20)  COMMENT '版本',
  CEC_EFFECT_STATUS  VARCHAR(20)  COMMENT '生效状态',
  CEC_CIRCUIT_BREAK  INT DEFAULT 0 COMMENT '是否联动熔断',
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    DATETIME,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    DATETIME,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RULE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='监测规则配置';

-- 风险预警记录表
CREATE TABLE IF NOT EXISTS IM_ALERT_RECORD (
  CEC_ALERT_ID         VARCHAR(64)  NOT NULL COMMENT '预警ID',
  CEC_RULE_ID          VARCHAR(64)  COMMENT '规则ID',
  CEC_SOURCE           VARCHAR(50)  COMMENT '来源',
  CEC_ASSET_ID         VARCHAR(64)  COMMENT '资产ID',
  CEC_ALERT_LEVEL      VARCHAR(20)  NOT NULL COMMENT '级别(紧急/重要/普通)',
  CEC_TRIGGER_COND     VARCHAR(1000) COMMENT '触发条件',
  CEC_ABNORMAL_DESC    VARCHAR(2000) COMMENT '异常描述',
  CEC_ALERT_TIME       DATETIME     COMMENT '预警时间',
  CEC_DISPOSE_STATUS   VARCHAR(50)  NOT NULL COMMENT '处置状态(待处理/处理中/已关闭)',
  CEC_DISPOSE_FEEDBACK VARCHAR(2000) COMMENT '处置反馈',
  CEC_RESPONDER_ID     VARCHAR(64)  COMMENT '处置人',
  CEC_CLOSE_TIME       DATETIME     COMMENT '关闭时间',
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      DATETIME,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      DATETIME,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ALERT_ID),
  KEY IDX_ALERT_ASSET (CEC_ASSET_ID),
  KEY IDX_ALERT_STATUS (CEC_DISPOSE_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='风险预警记录';

-- 风险预警定向通知表(可研 -006 推送/通知责任人)
CREATE TABLE IF NOT EXISTS IM_ALERT_NOTIFICATION (
  CEC_NOTIFY_ID      VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '通知ID',
  CEC_ALERT_ID       VARCHAR(64)  COMMENT '关联预警ID',
  CEC_ASSET_ID       VARCHAR(64)  COMMENT '资产ID',
  CEC_RECIPIENT      VARCHAR(200) COMMENT '接收方(责任人/部门)',
  CEC_CHANNEL        VARCHAR(200) COMMENT '推送渠道(站内信/邮件/短信/eLink)',
  CEC_TITLE          VARCHAR(500) COMMENT '标题',
  CEC_CONTENT        VARCHAR(2000) COMMENT '内容',
  CEC_ALERT_LEVEL    VARCHAR(20)  COMMENT '级别',
  CEC_READ_STATUS    VARCHAR(20)  COMMENT '已读状态(未读/已读)',
  CEC_PUSH_TIME      DATETIME     COMMENT '推送时间',
  CEC_READ_TIME      DATETIME     COMMENT '已读时间',
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    DATETIME,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    DATETIME,
  CEC_DEL_FLAG       INT DEFAULT 0,
  KEY IDX_NOTIFY_RECIPIENT (CEC_RECIPIENT, CEC_READ_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='风险预警定向通知';

-- 合规检查结果表
CREATE TABLE IF NOT EXISTS IM_COMPLIANCE_RESULT (
  CEC_CHECK_ID       VARCHAR(64)  NOT NULL COMMENT '检查ID',
  CEC_ASSET_ID       VARCHAR(64)  COMMENT '资产ID',
  CEC_RULE_ID        VARCHAR(64)  COMMENT '规则ID',
  CEC_CHECK_RESULT   VARCHAR(50)  COMMENT '检查结果',
  CEC_PROBLEM_DESC   VARCHAR(2000) COMMENT '问题描述',
  CEC_SUGGESTION     VARCHAR(2000) COMMENT '整改建议',
  CEC_REPORT_URL     VARCHAR(500) COMMENT '报告地址',
  CEC_CHECK_TIME     DATETIME     COMMENT '检查时间',
  CEC_DISPOSE_STATUS VARCHAR(50)  COMMENT '处置状态',
  CEC_CHECK_DIM      VARCHAR(50)  COMMENT '检查维度(有效期/权限范围/申请材料/协议内容)',
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    DATETIME,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    DATETIME,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CHECK_ID),
  KEY IDX_CHK_ASSET (CEC_ASSET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合规检查结果';

-- =====================================================================
-- F-02 数据确权管理 (dpr-confirm-service, 9102)
-- =====================================================================

-- 数据确权申请单表
CREATE TABLE IF NOT EXISTS IM_CONFIRM_APPLY (
  CEC_APPLY_ID      VARCHAR(64)  NOT NULL COMMENT '申请ID',
  CEC_APPLY_NO      VARCHAR(64)  COMMENT '申请编号',
  CEC_ASSET_ID      VARCHAR(64)  NOT NULL COMMENT '资产ID',
  CEC_ASSET_NAME    VARCHAR(255) NOT NULL COMMENT '资产名称',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '产权类型',
  CEC_PURPOSE       VARCHAR(1000) COMMENT '确权用途',
  CEC_RIGHT_HOLDER  VARCHAR(255) COMMENT '权属主体',
  CEC_RESP_DEPT     VARCHAR(255) COMMENT '责任部门',
  CEC_VALID_DATE    DATETIME     COMMENT '有效期',
  CEC_STATUS        VARCHAR(50)  COMMENT '状态机状态',
  CEC_REJECT_REASON VARCHAR(1000) COMMENT '驳回原因',
  CEC_CURRENT_NODE  INT          COMMENT '当前节点(进度%)',
  CEC_INVOLVES_THIRD_PARTY TINYINT(1) COMMENT '是否涉第三方',
  CEC_THIRD_PARTY_INFO     VARCHAR(2000) COMMENT '第三方信息',
  CEC_PRIVACY_INFO         VARCHAR(2000) COMMENT '个人隐私关联主体说明',
  CEC_RECOGNITION_OPINION  VARCHAR(2000) COMMENT '认定意见',
  CEC_RE_CONFIRM    TINYINT(1)   COMMENT '是否重确权',
  CEC_SOURCE_REF    VARCHAR(255) COMMENT '来源引用',
  CEC_SOURCE_IDENT  VARCHAR(100) COMMENT '来源权益识别(A-F)',
  CEC_RELATION_IDENT VARCHAR(100) COMMENT '信息关联权益识别(G-J)',
  CEC_SYSTEM_OWNER  VARCHAR(100) COMMENT '系统负责人姓名(附录F表1)',
  CEC_CONTACT       VARCHAR(100) COMMENT '系统负责人联系方式(附录F表1)',
  CEC_AI_SNAPSHOT   TEXT         COMMENT '提交前AI校验结果快照(JSON),供人工预审完整复核·可追溯',
  CEC_REGISTER_TYPE VARCHAR(20)  COMMENT '登记类型(初始确权/确权变更,附录F表1)',
  CEC_CHANGE_TRIGGER VARCHAR(50) COMMENT '变更触发类型(数据新增/数据来源变更/管理要求变更/权益到期/其他,附录F权益变更四类)',
  CEC_APPLY_MODE    VARCHAR(20)  COMMENT '申请模式(常规/一事一议)',
  CEC_REGULATED     VARCHAR(20)  COMMENT '管制属性(管制业务/非管制)',
  CEC_SOURCE_SUBJECT VARCHAR(255) COMMENT '表2:来源主体名称',
  CEC_SOURCE_LIMIT  VARCHAR(1000) COMMENT '表2:来源权益限制摘要',
  CEC_RELATION_SUBJECT VARCHAR(1000) COMMENT '表2:信息识别关联主体说明',
  CEC_EQUITY_RISK   VARCHAR(1000) COMMENT '表2:权益风险说明',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_APPLY_ID),
  KEY IDX_CA_ASSET (CEC_ASSET_ID),
  KEY IDX_CA_STATUS (CEC_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据确权申请单';

-- 确权指引材料表
CREATE TABLE IF NOT EXISTS IM_CONFIRM_GUIDANCE (
  CEC_GUIDANCE_ID   VARCHAR(64)  NOT NULL COMMENT '指引ID',
  CEC_TITLE         VARCHAR(255) NOT NULL COMMENT '标题',
  CEC_GUIDANCE_TYPE VARCHAR(100) COMMENT '指引类型',
  CEC_VERSION       VARCHAR(20)  COMMENT '版本',
  CEC_PUBLISHER     VARCHAR(100) COMMENT '发布单位',
  CEC_PUBLISH_DATE  DATETIME     COMMENT '发布日期',
  CEC_FILE_URL      VARCHAR(500) COMMENT '附件地址',
  CEC_FILE_NAME     VARCHAR(300) COMMENT '原件文件名',
  CEC_FILE_DATA     LONGTEXT     COMMENT '原件Base64',
  CEC_IS_LATEST     TINYINT(1) DEFAULT 1 COMMENT '是否最新版本',
  CEC_CONTENT       TEXT         COMMENT '正文',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_GUIDANCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='确权指引材料';

-- 确权申请材料表(含校验结果)
CREATE TABLE IF NOT EXISTS IM_CONFIRM_MATERIAL (
  CEC_MATERIAL_ID   VARCHAR(64)  NOT NULL COMMENT '材料ID',
  CEC_APPLY_ID      VARCHAR(64)  NOT NULL COMMENT '申请ID',
  CEC_MATERIAL_NAME VARCHAR(255) NOT NULL COMMENT '材料名称',
  CEC_MATERIAL_TYPE VARCHAR(100) COMMENT '材料类型',
  CEC_FILE_URL      VARCHAR(500) COMMENT '文件地址',
  CEC_OWNER         VARCHAR(100) COMMENT '归属',
  CEC_UPLOAD_TIME   DATETIME     COMMENT '上传时间',
  CEC_CHECK_RESULT  VARCHAR(50)  COMMENT '校验结果',
  CEC_ABNORMAL_DESC VARCHAR(1000) COMMENT '异常描述',
  CEC_FILE_NAME     VARCHAR(300) COMMENT '原件文件名',
  CEC_FILE_DATA     LONGTEXT     COMMENT '原件Base64',
  CEC_SOURCE        VARCHAR(20)  COMMENT '材料来源(平台同步/用户上传)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_MATERIAL_ID),
  KEY IDX_CM_APPLY (CEC_APPLY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='确权申请材料';

-- 确权申请流转历史/进度通知(可研 -006 进度跟踪)
CREATE TABLE IF NOT EXISTS IM_CONFIRM_FLOW_LOG (
  CEC_LOG_ID         VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '日志ID',
  CEC_APPLY_ID       VARCHAR(64)  COMMENT '申请ID',
  CEC_APPLY_NO       VARCHAR(64)  COMMENT '申请编号',
  CEC_FROM_STATUS    VARCHAR(50)  COMMENT '原状态',
  CEC_TO_STATUS      VARCHAR(50)  COMMENT '新状态',
  CEC_NODE           INT          COMMENT '节点编号',
  CEC_NODE_NAME      VARCHAR(100) COMMENT '节点名称',
  CEC_RESPONDER      VARCHAR(100) COMMENT '责任人',
  CEC_OPINION        VARCHAR(2000) COMMENT '审批意见',
  CEC_NOTIFY_CONTENT VARCHAR(1000) COMMENT '进度通知文案',
  CEC_PUSH_CHANNEL   VARCHAR(50)  COMMENT '推送渠道',
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    DATETIME,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    DATETIME,
  CEC_DEL_FLAG       INT DEFAULT 0,
  KEY IDX_FLOW_APPLY (CEC_APPLY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='确权申请流转历史/进度通知';

-- 确权汇总表(表3 数据确权信息汇总表 / 表4 数据权益内部管理汇总表)
CREATE TABLE IF NOT EXISTS IM_CONFIRM_SUMMARY (
  CEC_SUMMARY_ID    VARCHAR(64)  NOT NULL COMMENT '汇总ID',
  CEC_APPLY_ID      VARCHAR(64)  COMMENT '申请ID',
  CEC_SUMMARY_TYPE  VARCHAR(100) COMMENT '汇总类型(表3/表4)',
  CEC_CONTENT       VARCHAR(2000) COMMENT '汇总内容',
  CEC_GENERATOR_ID  VARCHAR(64)  COMMENT '生成人',
  CEC_GENERATE_TIME DATETIME     COMMENT '生成时间',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_SUMMARY_ID),
  KEY IDX_SM_APPLY (CEC_APPLY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='确权汇总表(表3/表4)';

-- 权益卡片表
CREATE TABLE IF NOT EXISTS IM_EQUITY_CARD_INFO (
  CEC_CARD_ID       VARCHAR(64)  NOT NULL COMMENT '卡片ID',
  CEC_CARD_NO       VARCHAR(64)  COMMENT '卡片编号',
  CEC_APPLY_ID      VARCHAR(64)  COMMENT '申请ID',
  CEC_ASSET_ID      VARCHAR(64)  COMMENT '资产ID',
  CEC_ASSET_NAME    VARCHAR(255) COMMENT '资产名称',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '产权类型',
  CEC_RIGHT_OWNER   VARCHAR(255) COMMENT '权属主体',
  CEC_RIGHT_SOURCE  VARCHAR(255) COMMENT '权利来源',
  CEC_SCOPE         VARCHAR(100) COMMENT '确权范围(全字段/约定字段),授权边界依据',
  CEC_VALID_DATE    DATETIME     COMMENT '有效期',
  CEC_CARD_STATUS   VARCHAR(50)  COMMENT '卡片状态(正常/冻结/失效)',
  CEC_CONSOLIDATED_UNIT    VARCHAR(255) COMMENT '权益归口单位',
  CEC_VERSION       INT DEFAULT 1 COMMENT '卡片版本号(确权变更每取代一次+1,初始确权为1)',
  CEC_SUPERSEDED_NO VARCHAR(64)  COMMENT '前序被取代卡片号(确权变更时指向上一版正常卡,形成版本链;初始确权为空)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CARD_ID),
  KEY IDX_CARD_ASSET (CEC_ASSET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权益卡片';

-- 权益卡片变更历史(生成/冻结/解冻/注销/变更)
CREATE TABLE IF NOT EXISTS IM_EQUITY_CARD_LOG (
  CEC_LOG_ID        VARCHAR(64) NOT NULL COMMENT '日志ID',
  CEC_CARD_ID       VARCHAR(64) COMMENT '卡片ID',
  CEC_ACTION        VARCHAR(50) COMMENT '动作',
  CEC_FROM_STATUS   VARCHAR(50) COMMENT '原状态',
  CEC_TO_STATUS     VARCHAR(50) COMMENT '新状态',
  CEC_REASON        VARCHAR(500) COMMENT '原因',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID),
  KEY IDX_CL_CARD (CEC_CARD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权益卡片变更历史';

-- 确权权益证书表
CREATE TABLE IF NOT EXISTS IM_EQUITY_CERT (
  CEC_CERT_ID       VARCHAR(64)  NOT NULL COMMENT '证书ID',
  CEC_CERT_NO       VARCHAR(64)  COMMENT '证书编号',
  CEC_CARD_ID       VARCHAR(64)  COMMENT '卡片ID',
  CEC_ISSUE_UNIT    VARCHAR(255) COMMENT '发证单位',
  CEC_ISSUE_TIME    DATETIME     COMMENT '发证时间',
  CEC_CERT_STATUS   VARCHAR(50)  COMMENT '证书状态',
  CEC_TEMPLATE_ID   VARCHAR(64)  COMMENT '模板ID',
  CEC_TEMPLATE_NAME VARCHAR(255) COMMENT '模板名称',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CERT_ID),
  KEY IDX_QCERT_CARD (CEC_CARD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='确权权益证书';

-- 确权权益证书模板表
CREATE TABLE IF NOT EXISTS IM_EQUITY_CERT_TEMPLATE (
  CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL COMMENT '模板ID',
  CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL COMMENT '模板名称',
  CEC_TEMPLATE_VERSION VARCHAR(20)  COMMENT '版本',
  CEC_RIGHT_TYPE       VARCHAR(100) COMMENT '适用产权类型',
  CEC_TEMPLATE_CONTENT TEXT         COMMENT '模板内容',
  CEC_TEMPLATE_STATUS  VARCHAR(50)  COMMENT '状态',
  CEC_FILE_NAME        VARCHAR(255) COMMENT '套版文件名',
  CEC_FILE_DATA        LONGTEXT     COMMENT '套版文件Base64',
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      DATETIME,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      DATETIME,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TEMPLATE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='确权权益证书模板';

-- ---------- 智能确权辅助工具(采购集成,confirm 域承载) ----------

-- 上传材料
CREATE TABLE IF NOT EXISTS IM_AIT_MATERIAL (
  CEC_MATERIAL_ID   VARCHAR(64) NOT NULL COMMENT '材料ID',
  CEC_BATCH_NO      VARCHAR(64) COMMENT '批次号',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '关联申请',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '关联资产',
  CEC_FILE_NAME     VARCHAR(500) COMMENT '文件名',
  CEC_FILE_TYPE     VARCHAR(20) COMMENT '文件类型',
  CEC_FILE_HASH     VARCHAR(64) COMMENT '文件指纹',
  CEC_SIZE_KB       BIGINT      COMMENT '大小KB',
  CEC_PARSE_STATUS  VARCHAR(20) COMMENT '解析状态',
  CEC_FAIL_REASON   VARCHAR(1000) COMMENT '失败原因',
  CEC_PROGRESS      INT DEFAULT 0 COMMENT '进度',
  CEC_STORAGE_PATH  VARCHAR(500) COMMENT '存储路径',
  CEC_CONTENT       TEXT        COMMENT '抽取正文',
  CEC_CATEGORY      VARCHAR(50) COMMENT '材料类别(元数据/制度附件/授权材料/合同材料/来源说明/确权证明等)',
  CEC_DATA_TABLE_REF VARCHAR(255) COMMENT '所属数据表标识(归集关联键)',
  CEC_LAYOUT_JSON   TEXT        COMMENT '版面分析结果JSON(印章/表格/标题/分栏/页类型)',
  CEC_DUPLICATE_OF  VARCHAR(64) COMMENT '重复检测命中的原材料ID',
  CEC_PAGE_COUNT    INT         COMMENT '页数',
  CEC_OCR_USED      INT DEFAULT 0 COMMENT '是否经OCR(0否1是)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_MATERIAL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-上传材料';

CREATE TABLE IF NOT EXISTS IM_AIT_DOC_SEGMENT (
  CEC_SEGMENT_ID    VARCHAR(64) NOT NULL COMMENT '片段ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_GRANULARITY   VARCHAR(20) COMMENT '粒度(PAGE/PARAGRAPH/CELL/TABLE/TITLE)',
  CEC_PAGE_NO       INT         COMMENT '页码',
  CEC_SEG_INDEX     INT         COMMENT '片段序号',
  CEC_SHEET_NAME    VARCHAR(100) COMMENT '工作表名(Excel)',
  CEC_ROW_NUM       INT         COMMENT '行号(单元格粒度)',
  CEC_COL_NUM       INT         COMMENT '列号(单元格粒度)',
  CEC_CONTENT       TEXT        COMMENT '片段内容',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_SEGMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-多粒度解析片段';

CREATE TABLE IF NOT EXISTS IM_AIT_CLEAN_LOG (
  CEC_LOG_ID        VARCHAR(64) NOT NULL COMMENT '日志ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_BATCH_NO      VARCHAR(64) COMMENT '清洗批次',
  CEC_ROW_NO        INT         COMMENT '记录行号',
  CEC_FIELD         VARCHAR(64) COMMENT '模板字段',
  CEC_RAW_KEY       VARCHAR(128) COMMENT '原始字段名',
  CEC_ORIGINAL_VALUE VARCHAR(2000) COMMENT '原始值',
  CEC_RULE          VARCHAR(255) COMMENT '命中清洗规则',
  CEC_CLEANED_VALUE VARCHAR(2000) COMMENT '清洗后值',
  CEC_METHOD        VARCHAR(20) COMMENT '方式(规则/模型/规则+模型)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-清洗日志';

CREATE TABLE IF NOT EXISTS IM_AIT_AUDIT_BASE (
  CEC_AUDIT_ID      VARCHAR(64) NOT NULL COMMENT '底表ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_BATCH_NO      VARCHAR(64) COMMENT '清洗批次',
  CEC_ROW_NO        INT         COMMENT '记录行号',
  CEC_TEMPLATE_FIELD VARCHAR(64) COMMENT '统一模板字段',
  CEC_FIELD_LABEL   VARCHAR(64) COMMENT '字段中文名',
  CEC_RAW_VALUE     VARCHAR(2000) COMMENT '原始值',
  CEC_CLEAN_VALUE   VARCHAR(2000) COMMENT '清洗标准化后值',
  CEC_STATUS        VARCHAR(20) COMMENT '状态(正常/缺失/冲突/异常/重复)',
  CEC_ISSUE         VARCHAR(500) COMMENT '问题描述',
  CEC_SUGGESTION    VARCHAR(500) COMMENT '待补正建议',
  CEC_DATA_TABLE_REF VARCHAR(255) COMMENT '数据表关联索引',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_AUDIT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-统一审核底表';

CREATE TABLE IF NOT EXISTS IM_AIT_PROFILE (
  CEC_PROFILE_ID    VARCHAR(64) NOT NULL COMMENT '画像ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_DATA_TABLE_REF VARCHAR(255) COMMENT '数据表关联索引',
  CEC_LEVEL         VARCHAR(20) COMMENT '层级(表级/附件级)',
  CEC_SOURCE_METHOD VARCHAR(50) COMMENT '数据来源方式',
  CEC_SOURCE_METHOD_BY VARCHAR(20) COMMENT '来源方式判定方式(规则/模型)',
  CEC_DATA_FEATURES VARCHAR(500) COMMENT '数据特征(多值)',
  CEC_ELEMENTS_JSON TEXT COMMENT '结构化确权画像JSON',
  CEC_CONFIDENCE    DOUBLE COMMENT '置信度',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_PROFILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-确权画像';

CREATE TABLE IF NOT EXISTS IM_AIT_PROFILE_SUBJECT (
  CEC_SUBJECT_ID    VARCHAR(64) NOT NULL COMMENT '主体ID',
  CEC_PROFILE_ID    VARCHAR(64) COMMENT '画像ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_SUBJECT_ROLE  VARCHAR(40) COMMENT '主体角色(来源/授权/使用/加工/共享对象)',
  CEC_SUBJECT_NAME  VARCHAR(500) COMMENT '主体名称',
  CEC_METHOD        VARCHAR(20) COMMENT '识别方式(规则/模型)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_SUBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-关键主体';

CREATE TABLE IF NOT EXISTS IM_AIT_CONSTRAINT (
  CEC_CONSTRAINT_ID VARCHAR(64) NOT NULL COMMENT '约束ID',
  CEC_PROFILE_ID    VARCHAR(64) COMMENT '画像ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_CONSTRAINT_TYPE VARCHAR(40) COMMENT '约束类型(授权范围/使用边界/共享限制/保留期限/脱敏要求)',
  CEC_CONSTRAINT_VALUE VARCHAR(1000) COMMENT '约束内容',
  CEC_METHOD        VARCHAR(20) COMMENT '识别方式(规则/模型)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONSTRAINT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-约束信息';

CREATE TABLE IF NOT EXISTS IM_AIT_PARSE_RECORD (
  CEC_RECORD_ID     VARCHAR(64) NOT NULL COMMENT '记录ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_FILE_NAME     VARCHAR(500) COMMENT '文档名称',
  CEC_BATCH_NO      VARCHAR(64) COMMENT '批次',
  CEC_FIELD         VARCHAR(64) COMMENT '提取字段',
  CEC_FIELD_VALUE   VARCHAR(2000) COMMENT '提取值',
  CEC_CONFIDENCE    DOUBLE COMMENT '置信度',
  CEC_OPERATOR_ID   VARCHAR(64) COMMENT '操作人ID',
  CEC_OPERATOR_NAME VARCHAR(64) COMMENT '操作人',
  CEC_PARSE_TIME    DATETIME COMMENT '解析时间',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RECORD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-解析记录档';

CREATE TABLE IF NOT EXISTS IM_AIT_DOC_TEMPLATE (
  CEC_TEMPLATE_ID   VARCHAR(64) NOT NULL COMMENT '模板ID',
  CEC_TEMPLATE_TYPE VARCHAR(50) COMMENT '模板类型(确权书/授权函/权属证明等)',
  CEC_TEMPLATE_NAME VARCHAR(255) COMMENT '模板名称',
  CEC_VERSION       VARCHAR(20) COMMENT '版本',
  CEC_CONTENT       TEXT COMMENT '在线编辑正文',
  CEC_FILE_NAME     VARCHAR(300) COMMENT '附件名',
  CEC_FILE_DATA     TEXT COMMENT '附件Base64',
  CEC_IS_LATEST     TINYINT(1) DEFAULT 1 COMMENT '是否最新版',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TEMPLATE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-资料模板库';

CREATE TABLE IF NOT EXISTS IM_AIT_PARSE_CONFIG (
  CEC_CONFIG_ID     VARCHAR(64) NOT NULL COMMENT '配置ID',
  CEC_SCENE         VARCHAR(50) COMMENT '业务场景',
  CEC_FIELD_MAPPING_JSON TEXT COMMENT '字段映射规则JSON',
  CEC_EXTRACT_LOGIC_JSON TEXT COMMENT '提取逻辑配置JSON',
  CEC_CONFIDENCE_THRESHOLD DOUBLE COMMENT '置信度阈值',
  CEC_ENABLED       INT DEFAULT 1 COMMENT '启用',
  CEC_REMARK        VARCHAR(500) COMMENT '备注',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONFIG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-解析元数据配置';

CREATE TABLE IF NOT EXISTS IM_AIT_KB_DOC (
  CEC_DOC_ID        VARCHAR(64) NOT NULL COMMENT '文档ID',
  CEC_DOC_TYPE      VARCHAR(40) COMMENT '类型(法规/行业标准/内部制度/审核规则/典型案例)',
  CEC_DOMAIN        VARCHAR(40) COMMENT '知识域(数据安全/个人信息保护/网络安全/数据确权等)',
  CEC_TITLE         VARCHAR(300) COMMENT '标题',
  CEC_SOURCE        VARCHAR(300) COMMENT '来源',
  CEC_EFFECTIVE_DATE VARCHAR(20) COMMENT '生效日期',
  CEC_SCOPE         VARCHAR(500) COMMENT '适用范围',
  CEC_VERSION       VARCHAR(20) COMMENT '版本',
  CEC_IS_LATEST     TINYINT(1) DEFAULT 1 COMMENT '是否最新',
  CEC_STATUS        VARCHAR(20) COMMENT '状态(有效/失效)',
  CEC_CONTENT       TEXT COMMENT '全文',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_DOC_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-知识库文档';

CREATE TABLE IF NOT EXISTS IM_AIT_KB_CHUNK (
  CEC_CHUNK_ID      VARCHAR(64) NOT NULL COMMENT '切片ID',
  CEC_DOC_ID        VARCHAR(64) COMMENT '文档ID',
  CEC_DOC_TYPE      VARCHAR(40) COMMENT '类型',
  CEC_DOMAIN        VARCHAR(40) COMMENT '知识域',
  CEC_TITLE         VARCHAR(300) COMMENT '文档标题',
  CEC_CLAUSE_NO     VARCHAR(50) COMMENT '条款编号',
  CEC_TAGS          VARCHAR(500) COMMENT '标签',
  CEC_CONTENT       TEXT COMMENT '切片正文',
  CEC_VECTOR_JSON   TEXT COMMENT '向量JSON',
  CEC_VECTOR_DIM    INT COMMENT '向量维度',
  CEC_EFFECTIVE_DATE VARCHAR(20) COMMENT '生效日期',
  CEC_SCOPE         VARCHAR(500) COMMENT '适用范围',
  CEC_STATUS        VARCHAR(20) COMMENT '状态(有效/失效)',
  CEC_SEQ           INT COMMENT '序号',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CHUNK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-知识库切片';

-- 材料解析要素
CREATE TABLE IF NOT EXISTS IM_AIT_PARSE_RESULT (
  CEC_PARSE_ID      VARCHAR(64) NOT NULL COMMENT '解析ID',
  CEC_MATERIAL_ID   VARCHAR(64) COMMENT '材料ID',
  CEC_RIGHT_SUBJECT VARCHAR(500) COMMENT '权利主体',
  CEC_RIGHT_OBJECT  VARCHAR(500) COMMENT '权利客体',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '产权类型',
  CEC_RIGHT_TERM    VARCHAR(100) COMMENT '权利期限',
  CEC_AUTH_SCOPE    VARCHAR(500) COMMENT '授权范围',
  CEC_DATA_SOURCE   VARCHAR(100) COMMENT '数据来源',
  CEC_SENSITIVE_TYPE VARCHAR(100) COMMENT '敏感类型',
  CEC_SEAL_VALID    VARCHAR(20) COMMENT '签章有效',
  CEC_SEAL_DESC     VARCHAR(500) COMMENT '签章说明',
  CEC_CONFIDENCE    DOUBLE      COMMENT '置信度',
  CEC_REVIEW_STATUS VARCHAR(50) COMMENT '复核标记(自动通过/需人工复核,阈值0.95)',
  CEC_TRUST_SCORE   INT         COMMENT '材料可信度评分0-100(印章交叉校验+置信度+要素完整性)',
  CEC_TRUST_LEVEL   VARCHAR(50) COMMENT '材料可信度评级(可信/存疑/不可信)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_PARSE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-解析要素';

-- 材料与表单比对
CREATE TABLE IF NOT EXISTS IM_AIT_COMPARE (
  CEC_COMPARE_ID    VARCHAR(64) NOT NULL COMMENT '比对ID',
  CEC_PARSE_ID      VARCHAR(64) COMMENT '解析ID',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '申请ID',
  CEC_FIELD         VARCHAR(100) COMMENT '字段',
  CEC_MATERIAL_VALUE VARCHAR(1000) COMMENT '材料值',
  CEC_FORM_VALUE    VARCHAR(1000) COMMENT '表单值',
  CEC_DIFF_TYPE     VARCHAR(20) COMMENT '差异类型',
  CEC_SOURCE_OFFSET INT          COMMENT '材料值在原始正文的字符偏移(-1=未定位/图片)',
  CEC_SOURCE_SNIPPET VARCHAR(500) COMMENT '原始正文定位上下文片段',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_COMPARE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-材料表单比对';

-- 权属主张(知识图谱)
CREATE TABLE IF NOT EXISTS IM_AIT_KG_CLAIM (
  CEC_CLAIM_ID      VARCHAR(64) NOT NULL COMMENT '主张ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_SUBJECT       VARCHAR(255) COMMENT '主体',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '产权类型',
  CEC_AUTH_SCOPE    VARCHAR(500) COMMENT '授权范围',
  CEC_VALID_DATE    DATETIME    COMMENT '有效期',
  CEC_EXCLUSIVE     TINYINT(1)  COMMENT '是否独占',
  CEC_SOURCE_TYPE   VARCHAR(50) COMMENT '来源类型',
  CEC_REMARK        VARCHAR(1000) COMMENT '备注',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CLAIM_ID),
  KEY IDX_KG_ASSET (CEC_ASSET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-权属主张(KG)';

-- 权属冲突
CREATE TABLE IF NOT EXISTS IM_AIT_CONFLICT (
  CEC_CONFLICT_ID   VARCHAR(64) NOT NULL COMMENT '冲突ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_CONFLICT_TYPE VARCHAR(50) COMMENT '冲突类型',
  CEC_CONFLICT_SOURCE VARCHAR(255) COMMENT '冲突来源',
  CEC_CONFLICT_DESC VARCHAR(2000) COMMENT '冲突描述',
  CEC_IMPACT_SCOPE  VARCHAR(1000) COMMENT '影响范围',
  CEC_RISK_LEVEL    VARCHAR(20) COMMENT '风险级别',
  CEC_SUGGESTION    VARCHAR(2000) COMMENT '消解建议',
  CEC_STATUS        VARCHAR(20) COMMENT '状态',
  CEC_RELATED_RECORD_NO VARCHAR(255) COMMENT '关联历史确权记录编号',
  CEC_CONFLICT_FIELDS VARCHAR(255) COMMENT '冲突字段',
  CEC_CLAUSE_REF    VARCHAR(500) COMMENT '相关协议/条款引用',
  CEC_LEGAL_RISK    VARCHAR(40) COMMENT '法律风险等级',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONFLICT_ID),
  KEY IDX_CFL_ASSET (CEC_ASSET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-权属冲突';

CREATE TABLE IF NOT EXISTS IM_AIT_CONFLICT_RULE (
  CEC_RULE_ID       VARCHAR(64) NOT NULL COMMENT '规则ID',
  CEC_RULE_TYPE     VARCHAR(40) COMMENT '规则类型(主体冲突/权限重叠/期限交叉/历史记录冲突/类型冲突)',
  CEC_RULE_NAME     VARCHAR(100) COMMENT '规则名称',
  CEC_ENABLED       INT DEFAULT 1 COMMENT '启用',
  CEC_PRIORITY      INT DEFAULT 100 COMMENT '优先级',
  CEC_THRESHOLD     DOUBLE COMMENT '阈值',
  CEC_REMARK        VARCHAR(500) COMMENT '备注',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RULE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-冲突识别规则';

CREATE TABLE IF NOT EXISTS IM_AIT_AUDIT_RESULT (
  CEC_AUDIT_ID      VARCHAR(64) NOT NULL COMMENT '审核ID',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '申请ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_CHANNEL       VARCHAR(20) COMMENT '审核通道(快速通道/深度审核)',
  CEC_DATA_CLASS    VARCHAR(100) COMMENT '数据分类',
  CEC_DATA_GRADE    VARCHAR(40) COMMENT '数据级别',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '权利类型',
  CEC_AUTH_ADVICE   VARCHAR(40) COMMENT '授权建议',
  CEC_AUTH_LEVEL    VARCHAR(40) COMMENT '授权级别',
  CEC_RESTRICTIONS  VARCHAR(1000) COMMENT '限制条件',
  CEC_RISK_LEVEL    VARCHAR(20) COMMENT '风险等级',
  CEC_SUPPLEMENT    VARCHAR(1000) COMMENT '补正建议',
  CEC_REASON        VARCHAR(2000) COMMENT '结论理由',
  CEC_CITATIONS     VARCHAR(1000) COMMENT '命中依据',
  CEC_ACTION        VARCHAR(255) COMMENT '建议动作',
  CEC_SCORE         DOUBLE COMMENT '综合评分',
  CEC_STAGE_TRACE_JSON TEXT COMMENT '阶段轨迹JSON',
  CEC_TOOL_TRACE_JSON  TEXT COMMENT '工具调用链JSON',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_AUDIT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-Agent审核结果';

CREATE TABLE IF NOT EXISTS IM_AIT_TASK (
  CEC_TASK_ID       VARCHAR(64) NOT NULL COMMENT '任务ID',
  CEC_TASK_TYPE     VARCHAR(40) COMMENT '任务类型(BATCH_PARSE/BATCH_AUDIT)',
  CEC_TASK_NAME     VARCHAR(200) COMMENT '任务名',
  CEC_ITEMS_JSON    TEXT COMMENT '待处理项ID列表JSON',
  CEC_ITEM_STATE_JSON TEXT COMMENT '逐项状态JSON(断点续跑)',
  CEC_TOTAL         INT DEFAULT 0 COMMENT '总数',
  CEC_DONE          INT DEFAULT 0 COMMENT '完成数',
  CEC_FAILED        INT DEFAULT 0 COMMENT '失败数',
  CEC_STATUS        VARCHAR(20) COMMENT '状态(待运行/运行中/已完成/部分失败/已暂停)',
  CEC_CONCURRENCY   INT DEFAULT 4 COMMENT '并发上限',
  CEC_RETRY_MAX     INT DEFAULT 2 COMMENT '失败重试上限',
  CEC_CURSOR        INT DEFAULT 0 COMMENT '断点位',
  CEC_LAST_ERROR    VARCHAR(1000) COMMENT '最近错误',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TASK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-批量任务';

CREATE TABLE IF NOT EXISTS IM_AIT_RUN_LOG (
  CEC_LOG_ID        VARCHAR(64) NOT NULL COMMENT '日志ID',
  CEC_LOG_TYPE      VARCHAR(20) COMMENT '类型(审计/操作/模型调用/规则命中/告警)',
  CEC_SOURCE        VARCHAR(100) COMMENT '来源',
  CEC_ACTION        VARCHAR(100) COMMENT '动作',
  CEC_DETAIL        VARCHAR(2000) COMMENT '详情',
  CEC_MODEL         VARCHAR(64) COMMENT '模型',
  CEC_DURATION_MS   BIGINT COMMENT '耗时ms',
  CEC_RESULT        VARCHAR(20) COMMENT '结果',
  CEC_TASK_ID       VARCHAR(64) COMMENT '关联任务',
  CEC_LOG_TIME      DATETIME COMMENT '时间',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-统一运行日志';

CREATE TABLE IF NOT EXISTS IM_AIT_EVIDENCE (
  CEC_EVIDENCE_ID   VARCHAR(64) NOT NULL COMMENT '证据ID',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '申请ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_MATERIAL_SNIPPETS_JSON TEXT COMMENT '输入材料片段',
  CEC_KB_HITS_JSON  TEXT COMMENT '知识库命中片段',
  CEC_RULE_HITS_JSON TEXT COMMENT '规则命中项',
  CEC_MODEL_REASON  TEXT COMMENT '大模型判断理由',
  CEC_CONCLUSION    VARCHAR(500) COMMENT '最终结论',
  CEC_SM3_HASH      VARCHAR(80) COMMENT 'SM3留痕',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_EVIDENCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-审核证据链';

-- 确权决策建议
CREATE TABLE IF NOT EXISTS IM_AIT_DECISION (
  CEC_DECISION_ID   VARCHAR(64) NOT NULL COMMENT '决策ID',
  CEC_APPLY_ID      VARCHAR(64) COMMENT '申请ID',
  CEC_ASSET_ID      VARCHAR(64) COMMENT '资产ID',
  CEC_PREDICTION    VARCHAR(50) COMMENT '预测结论',
  CEC_SCORE         DOUBLE      COMMENT '评分',
  CEC_FACTORS_JSON  TEXT        COMMENT '因子JSON',
  CEC_STRENGTH      VARCHAR(500) COMMENT '优势',
  CEC_WEAKNESS      VARCHAR(500) COMMENT '不足',
  CEC_SPLIT_PLAN    VARCHAR(2000) COMMENT '三权分置建议',
  CEC_SPLIT_PLANS_JSON TEXT       COMMENT '权益分割多方案明细JSON',
  CEC_REASON        VARCHAR(2000) COMMENT '理由',
  CEC_SUPPLEMENT    VARCHAR(1000) COMMENT '补充建议',
  CEC_PENDING_CONFLICTS VARCHAR(1000) COMMENT '待解冲突',
  CEC_RAG_ADVICE    TEXT        COMMENT 'RAG法规建议',
  CEC_AI_PREDICTION VARCHAR(50)  COMMENT 'AI预测结论',
  CEC_RAG_CITATIONS VARCHAR(1000) COMMENT 'RAG法规引用',
  CEC_EVIDENCE_CHAIN VARCHAR(80) COMMENT '存证链',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_DECISION_ID),
  KEY IDX_DEC_APPLY (CEC_APPLY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-确权决策建议';

-- =====================================================================
-- F-03 数据授权管理 (dpr-authorize-service, 9103)
-- =====================================================================

-- 数据授权申请单表
CREATE TABLE IF NOT EXISTS IM_AUTH_APPLY (
  CEC_APPLY_ID      VARCHAR(64)  NOT NULL COMMENT '申请ID',
  CEC_APPLY_NO      VARCHAR(64)  COMMENT '申请编号',
  CEC_AUTH_MODE     VARCHAR(50)  COMMENT '授权模式(一事一议/批量)',
  CEC_ASSET_ID      VARCHAR(64)  NOT NULL COMMENT '资产ID',
  CEC_ASSET_NAME    VARCHAR(255) NOT NULL COMMENT '资产名称',
  CEC_EQUITY_CARD_ID VARCHAR(64) COMMENT '引用权益卡片(先确后授)',
  CEC_GRANTEE_ORG   VARCHAR(255) COMMENT '被授权方',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '产权类型',
  CEC_SCENARIO      VARCHAR(500) COMMENT '应用场景',
  CEC_SCOPE         VARCHAR(1000) COMMENT '授权范围',
  CEC_VALID_DATE    DATETIME     COMMENT '有效期',
  CEC_STATUS        VARCHAR(50)  COMMENT '状态机状态',
  CEC_REJECT_REASON VARCHAR(1000) COMMENT '驳回原因',
  CEC_CURRENT_NODE  INT          COMMENT '当前节点',
  CEC_BATCH_LIST_ID VARCHAR(64)  COMMENT '批量清单ID',
  CEC_NEED_CONFIDENTIALITY TINYINT(1) COMMENT '是否需保密承诺函(附录E)',
  CEC_CONFIDENTIALITY_FILE VARCHAR(500) COMMENT '保密承诺函(附录E)',
  CEC_BUSINESS_DOMAIN   VARCHAR(100) COMMENT '所属业务域(表5)',
  CEC_CROSS_REGION      TINYINT(1)   COMMENT '是否跨区域/跨域(表5)',
  CEC_THIRD_PARTY_SOURCE VARCHAR(255) COMMENT '涉及第三方来源方式(表5)',
  CEC_THIRD_PARTY_LICENSE VARCHAR(1000) COMMENT '第三方许可凭证或说明(表5)',
  CEC_SENSITIVE_TYPE    VARCHAR(100) COMMENT '涉及个人隐私/商业秘密(表5)',
  CEC_INFO_AUTH_AGREEMENT VARCHAR(500) COMMENT '信息授权协议(表5)',
  CEC_APPLICANT_MANAGER VARCHAR(100) COMMENT '申请单位主管(表5)',
  CEC_CONTACT           VARCHAR(100) COMMENT '联系方式(表5)',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_APPLY_ID),
  KEY IDX_AA_ASSET (CEC_ASSET_ID),
  KEY IDX_AA_STATUS (CEC_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据授权申请单';

-- 表6 数据批量授权清单
CREATE TABLE IF NOT EXISTS IM_BATCH_AUTH_LIST (
  CEC_BATCH_LIST_ID VARCHAR(64)  NOT NULL COMMENT '清单ID',
  CEC_LIST_NO       VARCHAR(64)  COMMENT '清单编号',
  CEC_LIST_YEAR     VARCHAR(20)  COMMENT '年度',
  CEC_LIST_STATUS   VARCHAR(50)  COMMENT '状态',
  CEC_ITEM_COUNT    INT          COMMENT '条目数',
  CEC_REMARK        VARCHAR(1000) COMMENT '备注',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_BATCH_LIST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='批量授权清单(表6)';

-- 授权域通用目录项(指引/场景/申请表单模板/协议模板库,按 category 复用)
CREATE TABLE IF NOT EXISTS IM_AUTH_CATALOG_ITEM (
  CEC_ITEM_ID       VARCHAR(64)  NOT NULL COMMENT '目录项ID',
  CEC_CATEGORY      VARCHAR(50)  NOT NULL COMMENT '类别(GUIDANCE/SCENARIO/FORM_TEMPLATE/AGREEMENT_TEMPLATE)',
  CEC_NAME          VARCHAR(255) NOT NULL COMMENT '名称',
  CEC_ITEM_TYPE     VARCHAR(100) COMMENT '类型',
  CEC_VERSION       VARCHAR(20)  COMMENT '版本',
  CEC_CONTENT       TEXT         COMMENT '内容',
  CEC_STATUS        VARCHAR(50)  COMMENT '状态',
  CEC_PUBLISHER     VARCHAR(100) COMMENT '发布单位',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ITEM_ID),
  KEY IDX_CAT_CATEGORY (CEC_CATEGORY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权域通用目录项';

-- 授权申请合规校验结果
CREATE TABLE IF NOT EXISTS IM_AUTH_COMPLIANCE (
  CEC_CHECK_ID      VARCHAR(64)  NOT NULL COMMENT '校验ID',
  CEC_APPLY_ID      VARCHAR(64)  COMMENT '申请ID',
  CEC_RISK_LEVEL    VARCHAR(20)  COMMENT '风险级别',
  CEC_CHECK_RESULT  VARCHAR(50)  COMMENT '校验结果',
  CEC_PROBLEM_DESC  VARCHAR(2000) COMMENT '问题描述',
  CEC_CHECK_REPORT  TEXT         COMMENT '多维校验报告JSON',
  CEC_CHECK_TIME    DATETIME     COMMENT '校验时间',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CHECK_ID),
  KEY IDX_AC_APPLY (CEC_APPLY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权合规校验结果';

-- 数据运营授权协议(签章/审核/存档/下载)
CREATE TABLE IF NOT EXISTS IM_AUTH_AGREEMENT (
  CEC_AGREEMENT_ID   VARCHAR(64)  NOT NULL COMMENT '协议ID',
  CEC_AGREEMENT_NO   VARCHAR(64)  COMMENT '协议编号',
  CEC_APPLY_ID       VARCHAR(64)  COMMENT '申请ID',
  CEC_TEMPLATE_ID    VARCHAR(64)  COMMENT '模板ID',
  CEC_GRANTEE_ORG    VARCHAR(255) COMMENT '被授权方',
  CEC_FILE_URL       VARCHAR(500) COMMENT '协议文件',
  CEC_SEAL_STATUS    VARCHAR(50)  COMMENT '签章状态',
  CEC_SEAL_VERIFY    VARCHAR(100) COMMENT '签章校验',
  CEC_GRANTOR_SIGNED TINYINT(1)   COMMENT '甲方已签',
  CEC_GRANTOR_SIGN_TIME DATETIME  COMMENT '甲方签署时间',
  CEC_GRANTEE_SIGNED TINYINT(1)   COMMENT '乙方已签',
  CEC_GRANTEE_SIGN_TIME DATETIME  COMMENT '乙方签署时间',
  CEC_REVIEW_STATUS  VARCHAR(50)  COMMENT '审核状态',
  CEC_ARCHIVE_STATUS VARCHAR(50)  COMMENT '归档状态',
  CEC_AGREEMENT_TYPE VARCHAR(100) COMMENT '协议类型(存档检索)',
  CEC_DEPT_NAME      VARCHAR(255) COMMENT '所属部门(存档检索)',
  CEC_ARCHIVE_TIME   DATETIME     COMMENT '归档时间',
  CEC_SIGN_TIME      DATETIME     COMMENT '签署时间',
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    DATETIME,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    DATETIME,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_AGREEMENT_ID),
  KEY IDX_AG_APPLY (CEC_APPLY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据运营授权协议';

-- 授权权益证书表
CREATE TABLE IF NOT EXISTS IM_AUTH_CERT (
  CEC_CERT_ID       VARCHAR(64)  NOT NULL COMMENT '证书ID',
  CEC_CERT_NO       VARCHAR(64)  COMMENT '证书编号',
  CEC_APPLY_ID      VARCHAR(64)  COMMENT '申请ID',
  CEC_ASSET_ID      VARCHAR(64)  COMMENT '资产ID',
  CEC_GRANTEE_ORG   VARCHAR(255) COMMENT '被授权方',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '产权类型',
  CEC_SCOPE         VARCHAR(1000) COMMENT '授权范围',
  CEC_VALID_DATE    DATETIME     COMMENT '有效期',
  CEC_CERT_STATUS   VARCHAR(50)  COMMENT '证书状态(生效/已暂停/已撤销)',
  CEC_SUSPEND_REASON VARCHAR(1000) COMMENT '暂停/熔断原因',
  CEC_TEMPLATE_ID    VARCHAR(64)  COMMENT '出证模板ID',
  CEC_TEMPLATE_NAME  VARCHAR(255) COMMENT '出证模板名称',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CERT_ID),
  KEY IDX_ACERT_ASSET (CEC_ASSET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权权益证书';

-- 授权权益证书模板(专项/批量)
CREATE TABLE IF NOT EXISTS IM_AUTH_CERT_TEMPLATE (
  CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL COMMENT '模板ID',
  CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL COMMENT '模板名称',
  CEC_TEMPLATE_VERSION VARCHAR(20)  COMMENT '版本',
  CEC_CERT_TYPE        VARCHAR(50)  COMMENT '证书类型(专项/批量授权证书)',
  CEC_RIGHT_TYPE       VARCHAR(100) COMMENT '产权类型',
  CEC_TEMPLATE_CONTENT TEXT         COMMENT '模板内容',
  CEC_TEMPLATE_STATUS  VARCHAR(50)  COMMENT '状态',
  CEC_FILE_NAME        VARCHAR(300) COMMENT '套版文件名',
  CEC_FILE_DATA        LONGTEXT     COMMENT '套版文件Base64',
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      DATETIME,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      DATETIME,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TEMPLATE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权权益证书模板';

-- 授权指引材料(可研 3.2.2.1.1.3.1.1:政策/流程图/常见问答/申请步骤 + 上传下载 + 历史版本)
CREATE TABLE IF NOT EXISTS IM_AUTH_GUIDANCE (
  CEC_GUIDANCE_ID   VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '指引ID',
  CEC_TITLE         VARCHAR(255) NOT NULL COMMENT '标题',
  CEC_GUIDANCE_TYPE VARCHAR(100) COMMENT '类型(政策文件/流程图/常见问答/申请步骤/材料样例)',
  CEC_VERSION       VARCHAR(20)  COMMENT '版本',
  CEC_PUBLISHER     VARCHAR(100) COMMENT '发布人',
  CEC_PUBLISH_DATE  DATETIME     COMMENT '发布日期',
  CEC_FILE_URL      VARCHAR(500) COMMENT '文件下载地址',
  CEC_FILE_NAME     VARCHAR(300) COMMENT '原件文件名',
  CEC_FILE_DATA     LONGTEXT     COMMENT '原件Base64',
  CEC_IS_LATEST     TINYINT(1) DEFAULT 1 COMMENT '是否最新版本',
  CEC_CONTENT       TEXT         COMMENT '正文内容',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  KEY IDX_AUTHGUIDE_TITLE (CEC_TITLE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权指引材料';

-- 授权申请表单模板(可研 3.2.2.1.1.3.1.2:按授权类型 独占/共享/委托 配置字段/流程/验证规则)
CREATE TABLE IF NOT EXISTS IM_AUTH_APPLY_TEMPLATE (
  CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '模板ID',
  CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL COMMENT '模板名称',
  CEC_AUTH_TYPE        VARCHAR(50)  COMMENT '授权类型(独占/共享/委托)',
  CEC_FIELDS_JSON      TEXT         COMMENT '字段配置JSON[{name,label,type,required,rule}]',
  CEC_FLOW_DESC        VARCHAR(2000) COMMENT '流程说明',
  CEC_TEMPLATE_VERSION VARCHAR(20)  COMMENT '版本',
  CEC_TEMPLATE_STATUS  VARCHAR(50)  COMMENT '状态',
  CEC_REMARK           VARCHAR(1000) COMMENT '备注',
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      DATETIME,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      DATETIME,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  KEY IDX_APPLYTPL_TYPE (CEC_AUTH_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权申请表单模板';

-- 授权应用场景配置(可研 3.2.2.1.1.3.1.3:用途场景 分类/描述 + 申请原因模板)
CREATE TABLE IF NOT EXISTS IM_AUTH_SCENARIO (
  CEC_SCENARIO_ID     VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '场景ID',
  CEC_SCENARIO_NAME   VARCHAR(255) NOT NULL COMMENT '场景名称',
  CEC_CATEGORY        VARCHAR(100) COMMENT '场景分类',
  CEC_DESCRIPTION     VARCHAR(1000) COMMENT '场景描述',
  CEC_REASON_TEMPLATE VARCHAR(2000) COMMENT '申请原因模板',
  CEC_SCENARIO_STATUS VARCHAR(50)  COMMENT '状态',
  CEC_PROVINCE_CODE   VARCHAR(32),
  CEC_BUREAU_CODE     VARCHAR(32),
  CEC_CREATOR_ID      VARCHAR(64),
  CEC_CREATE_TIME     DATETIME,
  CEC_UPDATER_ID      VARCHAR(64),
  CEC_UPDATE_TIME     DATETIME,
  CEC_DEL_FLAG        INT NOT NULL DEFAULT 0,
  KEY IDX_SCENARIO_CAT (CEC_CATEGORY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权应用场景配置';

-- 授权申请材料(可研 3.2.2.1.1.3.1.4:上传相关材料,Base64 入库)
CREATE TABLE IF NOT EXISTS IM_AUTH_MATERIAL (
  CEC_MATERIAL_ID   VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '材料ID',
  CEC_APPLY_ID      VARCHAR(64)  COMMENT '关联申请ID',
  CEC_MATERIAL_NAME VARCHAR(300) COMMENT '材料名称',
  CEC_MATERIAL_TYPE VARCHAR(100) COMMENT '材料类型',
  CEC_OWNER         VARCHAR(100) COMMENT '上传人',
  CEC_UPLOAD_TIME   DATETIME     COMMENT '上传时间',
  CEC_FILE_NAME     VARCHAR(300) COMMENT '原件文件名',
  CEC_FILE_DATA     LONGTEXT     COMMENT '原件Base64',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  KEY IDX_AUTHMAT_APPLY (CEC_APPLY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权申请材料';

-- 授权申请审批处理记录(可研 3.2.2.1.1.3.2.1:审批轨迹 from→to/责任人/审核意见/时间)
CREATE TABLE IF NOT EXISTS IM_AUTH_FLOW_LOG (
  CEC_LOG_ID      VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '日志ID',
  CEC_APPLY_ID    VARCHAR(64)  COMMENT '申请ID',
  CEC_APPLY_NO    VARCHAR(64)  COMMENT '申请编号',
  CEC_FROM_STATUS VARCHAR(50)  COMMENT '原状态',
  CEC_TO_STATUS   VARCHAR(50)  COMMENT '新状态',
  CEC_NODE_NAME   VARCHAR(100) COMMENT '节点名称',
  CEC_RESPONDER   VARCHAR(100) COMMENT '责任人',
  CEC_OPINION     VARCHAR(2000) COMMENT '审核意见',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE VARCHAR(32),
  CEC_CREATOR_ID  VARCHAR(64),
  CEC_CREATE_TIME DATETIME,
  CEC_UPDATER_ID  VARCHAR(64),
  CEC_UPDATE_TIME DATETIME,
  CEC_DEL_FLAG    INT NOT NULL DEFAULT 0,
  KEY IDX_AUTHFLOW_APPLY (CEC_APPLY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权申请审批处理记录';

-- 授权协议模板库(可研 3.2.2.1.1.3.3.1:授权类型/使用目的分类 + 版本 + 内容 + 套版文件上传下载)
CREATE TABLE IF NOT EXISTS IM_AUTH_AGREEMENT_TEMPLATE (
  CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '模板ID',
  CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL COMMENT '模板名称',
  CEC_AUTH_TYPE        VARCHAR(50)  COMMENT '授权类型',
  CEC_PURPOSE          VARCHAR(100) COMMENT '使用目的',
  CEC_TEMPLATE_CONTENT TEXT         COMMENT '协议内容',
  CEC_TEMPLATE_VERSION VARCHAR(20)  COMMENT '版本',
  CEC_TEMPLATE_STATUS  VARCHAR(50)  COMMENT '状态',
  CEC_FILE_NAME        VARCHAR(300) COMMENT '套版文件名',
  CEC_FILE_DATA        LONGTEXT     COMMENT '套版文件Base64',
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      DATETIME,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      DATETIME,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  KEY IDX_AGRTPL_TYPE (CEC_AUTH_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权协议模板库';

-- 授权签章上传记录(可研 3.2.2.1.1.3.3.2:上传行为 + 格式校验 + 签章有效性验证结果)
CREATE TABLE IF NOT EXISTS IM_AUTH_SEAL_UPLOAD_LOG (
  CEC_LOG_ID        VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '记录ID',
  CEC_AGREEMENT_ID  VARCHAR(64)  COMMENT '协议ID',
  CEC_UPLOADER_ROLE VARCHAR(50)  COMMENT '上传角色(授权方/被授权方)',
  CEC_FILE_NAME     VARCHAR(300) COMMENT '签章文件名',
  CEC_FILE_DATA     LONGTEXT     COMMENT '签章文件Base64',
  CEC_FORMAT_OK     TINYINT(1)   COMMENT '格式校验是否通过',
  CEC_SEAL_VALID    TINYINT(1)   COMMENT '签章有效性是否通过',
  CEC_VERIFY_RESULT VARCHAR(500) COMMENT '验证结果',
  CEC_UPLOAD_TIME   DATETIME     COMMENT '上传时间',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  KEY IDX_SEALLOG_AGR (CEC_AGREEMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权签章上传记录';

-- 授权协议审核记录(可研 3.2.2.1.1.3.3.3:审核人/结论/意见/时间)
CREATE TABLE IF NOT EXISTS IM_AUTH_AGR_REVIEW_LOG (
  CEC_LOG_ID       VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '记录ID',
  CEC_AGREEMENT_ID VARCHAR(64)  COMMENT '协议ID',
  CEC_AGREEMENT_NO VARCHAR(64)  COMMENT '协议编号',
  CEC_REVIEWER     VARCHAR(100) COMMENT '审核人',
  CEC_RESULT       VARCHAR(50)  COMMENT '审核结论',
  CEC_OPINION      VARCHAR(2000) COMMENT '审核意见',
  CEC_REVIEW_TIME  DATETIME     COMMENT '审核时间',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE  VARCHAR(32),
  CEC_CREATOR_ID   VARCHAR(64),
  CEC_CREATE_TIME  DATETIME,
  CEC_UPDATER_ID   VARCHAR(64),
  CEC_UPDATE_TIME  DATETIME,
  CEC_DEL_FLAG     INT NOT NULL DEFAULT 0,
  KEY IDX_AGRREVIEW_AGR (CEC_AGREEMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权协议审核记录';

-- 授权协议存档审计日志(可研 3.2.2.1.1.3.3.4:归档/查看/下载 访问留痕,可追溯)
CREATE TABLE IF NOT EXISTS IM_AUTH_ARCHIVE_LOG (
  CEC_LOG_ID       VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '日志ID',
  CEC_AGREEMENT_ID VARCHAR(64)  COMMENT '协议ID',
  CEC_AGREEMENT_NO VARCHAR(64)  COMMENT '协议编号',
  CEC_ACTION       VARCHAR(50)  COMMENT '操作(归档/查看/下载)',
  CEC_OPERATOR     VARCHAR(100) COMMENT '操作人',
  CEC_OPERATE_TIME DATETIME     COMMENT '操作时间',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE  VARCHAR(32),
  CEC_CREATOR_ID   VARCHAR(64),
  CEC_CREATE_TIME  DATETIME,
  CEC_UPDATER_ID   VARCHAR(64),
  CEC_UPDATE_TIME  DATETIME,
  CEC_DEL_FLAG     INT NOT NULL DEFAULT 0,
  KEY IDX_ARCHLOG_AGR (CEC_AGREEMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权协议存档审计日志';

-- 违规追责记录(监测联动熔断暂停授权时建账,附录F 3.4.5)
CREATE TABLE IF NOT EXISTS IM_AUTH_ACCOUNTABILITY (
  CEC_ACCOUNT_ID       VARCHAR(64)  NOT NULL COMMENT '追责ID',
  CEC_CERT_ID          VARCHAR(64)  COMMENT '证书ID',
  CEC_ASSET_ID         VARCHAR(64)  COMMENT '资产ID',
  CEC_GRANTEE_ORG      VARCHAR(255) COMMENT '被授权方',
  CEC_VIOLATION_TYPE   VARCHAR(100) COMMENT '违规类型',
  CEC_SOURCE_ALERT_ID  VARCHAR(64)  COMMENT '来源预警ID',
  CEC_REASON           VARCHAR(1000) COMMENT '事由',
  CEC_HANDLE_STATUS    VARCHAR(50)  COMMENT '处理状态',
  CEC_RESPONSIBLE_PARTY VARCHAR(255) COMMENT '责任方',
  CEC_HANDLE_FEEDBACK  VARCHAR(1000) COMMENT '处理反馈',
  CEC_HANDLE_TIME      DATETIME     COMMENT '处理时间',
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      DATETIME,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      DATETIME,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ACCOUNT_ID),
  KEY IDX_ACC_CERT (CEC_CERT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='违规追责记录';

-- 对外数据经营权授权备案(附录G / 附录F §3.4.6:仅经营权对外授权需备案)
CREATE TABLE IF NOT EXISTS IM_AUTH_FILING (
  CEC_FILING_ID     VARCHAR(64)  NOT NULL COMMENT '备案ID',
  CEC_FILING_NO     VARCHAR(64)  COMMENT '备案编号',
  CEC_AGREEMENT_ID  VARCHAR(64)  COMMENT '关联运营授权协议(附录D)',
  CEC_APPLY_ID      VARCHAR(64)  COMMENT '关联授权申请',
  CEC_FILING_ORG    VARCHAR(255) COMMENT '备案单位(分子公司)',
  CEC_GRANTEE_ORG   VARCHAR(255) COMMENT '被授权方',
  CEC_RIGHT_TYPE    VARCHAR(100) COMMENT '产权类型(经营权)',
  CEC_FILING_STATUS VARCHAR(50)  COMMENT '备案状态(待备案/已备案)',
  CEC_FILING_TIME   DATETIME     COMMENT '备案时间',
  CEC_REMARK        VARCHAR(1000) COMMENT '备注',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_FILING_ID),
  KEY IDX_FILING_STATUS (CEC_FILING_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='对外经营权授权备案(附录G)';

-- =====================================================================
-- 完。60 张表。测试数据见 02_data.sql
-- =====================================================================

-- 确权申请-表级数据清单(对齐《数据确权信息汇总表》/补录工单 M02)
CREATE TABLE IF NOT EXISTS IM_CONFIRM_TABLE_ITEM (
  CEC_ITEM_ID       VARCHAR(64) NOT NULL COMMENT '清单项ID',
  CEC_APPLY_ID      VARCHAR(64)  COMMENT '申请ID',
  CEC_INSTANCE_NAME VARCHAR(120) COMMENT '实例名或TNS',
  CEC_SCHEMA_NAME   VARCHAR(120) COMMENT 'schema/模式名称',
  CEC_TABLE_CODE    VARCHAR(150) COMMENT '表代码',
  CEC_TABLE_NAME    VARCHAR(200) COMMENT '表名称',
  CEC_TABLE_COMMENT VARCHAR(500) COMMENT '表注释',
  CEC_SECRET_LEVEL  VARCHAR(20)  COMMENT '密级(不涉密/核心商密/普通商密/工作秘密/敏感信息)',
  CEC_SOURCE_TYPE   VARCHAR(50)  COMMENT '来源判定(A-F)',
  CEC_SOURCE_SUBJECT VARCHAR(200) COMMENT '来源主体名称',
  CEC_SOURCE_DESC   VARCHAR(500) COMMENT '来源说明',
  CEC_G_FLAG        VARCHAR(4)   COMMENT 'G行政监管(是/否)',
  CEC_G_SUBJECT     VARCHAR(300) COMMENT 'G关联主体说明',
  CEC_H_FLAG        VARCHAR(4)   COMMENT 'H个人隐私(是/否)',
  CEC_H_SUBJECT     VARCHAR(300) COMMENT 'H关联主体说明',
  CEC_I_FLAG        VARCHAR(4)   COMMENT 'I第三方商密(是/否)',
  CEC_I_SUBJECT     VARCHAR(300) COMMENT 'I关联主体说明',
  CEC_J_FLAG        VARCHAR(4)   COMMENT 'J其他协议(是/否)',
  CEC_J_SUBJECT     VARCHAR(300) COMMENT 'J关联主体说明',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_ITEM_ID),
  KEY IDX_CTI_APPLY (CEC_APPLY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='确权申请-表级数据清单(M02)';

CREATE TABLE IF NOT EXISTS IM_SYS_USER (
  CEC_USER_ID       VARCHAR(64)  NOT NULL COMMENT '用户ID',
  CEC_USERNAME      VARCHAR(64)  NOT NULL COMMENT '登录名',
  CEC_PASSWORD_HASH VARCHAR(128) COMMENT '密码SM3哈希',
  CEC_REAL_NAME     VARCHAR(64)  COMMENT '姓名',
  CEC_ROLE          VARCHAR(32)  COMMENT '角色(apply/review/admin/view/all)',
  CEC_PROVINCE_CODE VARCHAR(32)  COMMENT '省公司代码',
  CEC_STATUS        VARCHAR(16)  DEFAULT '启用',
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT DEFAULT 0,
  PRIMARY KEY (CEC_USER_ID),
  UNIQUE KEY uk_username (CEC_USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户(内建认证+RBAC)';

CREATE TABLE IF NOT EXISTS IM_SYS_OPLOG (
  CEC_LOG_ID        VARCHAR(64)  NOT NULL COMMENT '日志ID',
  CEC_USER_ID       VARCHAR(64)  COMMENT '操作人ID',
  CEC_USER_NAME     VARCHAR(64)  COMMENT '操作人姓名',
  CEC_ACTION        VARCHAR(50)  COMMENT '动作(登录/新增用户/重置密码等)',
  CEC_TARGET        VARCHAR(255) COMMENT '操作对象',
  CEC_DETAIL        VARCHAR(1000) COMMENT '详情',
  CEC_IP            VARCHAR(64)  COMMENT '来源IP',
  CEC_RESULT        VARCHAR(20)  COMMENT '结果(成功/失败)',
  CEC_CREATE_TIME   DATETIME,
  PRIMARY KEY (CEC_LOG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统操作日志';

-- 1.1.1.1#4 结构化模板对比日志
CREATE TABLE IF NOT EXISTS IM_AIT_TPL_COMPARE (
  CEC_TPL_CMP_ID     VARCHAR(64) COMMENT '对比行ID',
  CEC_MATERIAL_ID    VARCHAR(64) COMMENT '材料ID',
  CEC_BATCH_NO       VARCHAR(64) COMMENT '对比批次',
  CEC_TEMPLATE_NAME  VARCHAR(255) COMMENT '模板名称',
  CEC_ROW_NO         INT COMMENT '行号',
  CEC_TPL_FIELD      VARCHAR(128) COMMENT '模板字段',
  CEC_TPL_VALUE      VARCHAR(2000) COMMENT '模板值',
  CEC_MATERIAL_VALUE VARCHAR(2000) COMMENT '材料抽取值',
  CEC_CONSISTENCY    VARCHAR(20) COMMENT '一致性',
  CEC_SOURCE_LOCATION VARCHAR(1000) COMMENT '材料中所在位置',
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    DATETIME,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    DATETIME,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TPL_CMP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工具-结构化模板对比日志';

-- 确权应交材料清单规则(可配置,单一真源:场景×触发条件 → 应交材料)
CREATE TABLE IF NOT EXISTS IM_CONFIRM_MATERIAL_RULE (
  CEC_RULE_ID       VARCHAR(64)  NOT NULL COMMENT '规则ID',
  CEC_SCENE         VARCHAR(50)  NOT NULL COMMENT '场景:确权/批量授权/一事一议授权',
  CEC_TRIGGER_TYPE  VARCHAR(20)  NOT NULL COMMENT '触发类型:ALWAYS/TABLE2/SOURCE/RELATION',
  CEC_TRIGGER_CODE  VARCHAR(8)            COMMENT '触发码 A-J',
  CEC_TRIGGER_LABEL VARCHAR(100)          COMMENT '触发码标签',
  CEC_MATERIAL_NAME VARCHAR(300) NOT NULL COMMENT '应交材料名称',
  CEC_REQUIRED      VARCHAR(20)           COMMENT '必填/视情况',
  CEC_EVIDENCE_TYPE VARCHAR(20)           COMMENT '表单/凭证/说明',
  CEC_DETAIL        VARCHAR(1000)         COMMENT '内容与要求明细',
  CEC_TEMPLATE_REF  VARCHAR(64)           COMMENT '关联模板ID',
  CEC_SORT_NO       INT                   COMMENT '排序',
  CEC_ENABLED       TINYINT(1) DEFAULT 1  COMMENT '是否启用',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RULE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='确权应交材料清单规则(可配置)';

-- 授权应交材料清单规则(可配置,单一真源:场景×触发条件 → 应交材料)
CREATE TABLE IF NOT EXISTS IM_AUTH_MATERIAL_RULE (
  CEC_RULE_ID       VARCHAR(64)  NOT NULL COMMENT '规则ID',
  CEC_SCENE         VARCHAR(50)  NOT NULL COMMENT '场景:批量/一事一议',
  CEC_TRIGGER_TYPE  VARCHAR(20)  NOT NULL COMMENT '触发类型:ALWAYS/THIRD_PARTY/SENSITIVE',
  CEC_MATERIAL_NAME VARCHAR(300) NOT NULL COMMENT '应交材料名称',
  CEC_REQUIRED      VARCHAR(20)           COMMENT '必填/视情况',
  CEC_EVIDENCE_TYPE VARCHAR(20)           COMMENT '表单/凭证/协议',
  CEC_DETAIL        VARCHAR(1000)         COMMENT '内容与要求明细',
  CEC_TEMPLATE_REF  VARCHAR(64)           COMMENT '关联模板ID',
  CEC_SORT_NO       INT                   COMMENT '排序',
  CEC_ENABLED       TINYINT(1) DEFAULT 1  COMMENT '是否启用',
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   DATETIME,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   DATETIME,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RULE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权应交材料清单规则(可配置)';
