-- =============================================================================
-- 增量迁移(MySQL)07:补齐 01_schema.sql 相对 H2 基线漂移的列/表。
-- 根因同 dm8/09(CEC_CHANGE_DIFF / CEC_GEO_SCOPE 等)。全新与存量库均须在 base 后执行本脚本。
-- 表用 CREATE TABLE IF NOT EXISTS(幂等);补列 ALTER ADD COLUMN 仅在列缺失时执行一次。
-- 基线:prm-backend/*/src/main/resources/db/h2/schema.sql
-- =============================================================================

-- A) 存量/全新库均须补的漂移列(ALTER ADD)。
-- IM_AUTH_AGREEMENT
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_BATCH_LIST_ID VARCHAR(64);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_DOC_STATUS VARCHAR(20);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_VALID_UNTIL DATETIME;
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_GEO_SCOPE VARCHAR(200);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_SECURITY_ENCRYPT VARCHAR(500);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_SECURITY_ACCESS VARCHAR(500);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_SECURITY_AUDIT VARCHAR(500);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_BENEFIT_ALLOCATION VARCHAR(1000);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_PENALTY_AMOUNT VARCHAR(50);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_DISPUTE_METHOD VARCHAR(200);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_SERVICE_DELIVERY VARCHAR(500);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_COPIES_COUNT INT;
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_CONFIDENTIALITY_FILE VARCHAR(500);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_DOC_SNAPSHOT TEXT;
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_TERMINATED BOOLEAN;
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_TERMINATE_REASON VARCHAR(500);
ALTER TABLE IM_AUTH_AGREEMENT ADD COLUMN CEC_TERMINATE_TIME DATETIME;

-- IM_AUTH_APPLY
ALTER TABLE IM_AUTH_APPLY ADD COLUMN CEC_SYSTEM_NAME VARCHAR(255);
ALTER TABLE IM_AUTH_APPLY ADD COLUMN CEC_PURPOSE_NOTE VARCHAR(500);
ALTER TABLE IM_AUTH_APPLY ADD COLUMN CEC_FORM_NO VARCHAR(64);
ALTER TABLE IM_AUTH_APPLY ADD COLUMN CEC_SCHEMA_NAME VARCHAR(255);
ALTER TABLE IM_AUTH_APPLY ADD COLUMN CEC_BENEFIT_ALLOC VARCHAR(1000);
ALTER TABLE IM_AUTH_APPLY ADD COLUMN CEC_SECURITY_REQ VARCHAR(1000);

-- IM_AUTH_FILING
ALTER TABLE IM_AUTH_FILING ADD COLUMN CEC_AGREEMENT_NO VARCHAR(64);
ALTER TABLE IM_AUTH_FILING ADD COLUMN CEC_VALID_DATE DATETIME;
ALTER TABLE IM_AUTH_FILING ADD COLUMN CEC_FILING_TYPE VARCHAR(30);
ALTER TABLE IM_AUTH_FILING ADD COLUMN CEC_PRODUCT_NAME VARCHAR(255);
ALTER TABLE IM_AUTH_FILING ADD COLUMN CEC_PRODUCT_INTRO VARCHAR(1000);
ALTER TABLE IM_AUTH_FILING ADD COLUMN CEC_APP_SCENARIO VARCHAR(500);
ALTER TABLE IM_AUTH_FILING ADD COLUMN CEC_SERVICE_TARGET VARCHAR(255);
ALTER TABLE IM_AUTH_FILING ADD COLUMN CEC_INVOLVED_TABLES VARCHAR(1000);

-- IM_AUTH_SCENARIO
ALTER TABLE IM_AUTH_SCENARIO ADD COLUMN CEC_RIGHT_TYPE VARCHAR(100);

-- IM_BATCH_AUTH_LIST
ALTER TABLE IM_BATCH_AUTH_LIST ADD COLUMN CEC_GEO_SCOPE VARCHAR(200);

-- IM_COMPLIANCE_RESULT
ALTER TABLE IM_COMPLIANCE_RESULT ADD COLUMN CEC_ASSET_NAME VARCHAR(255);

-- IM_CONFIRM_APPLY
ALTER TABLE IM_CONFIRM_APPLY ADD COLUMN CEC_SUBJECT_LEVEL VARCHAR(40);
ALTER TABLE IM_CONFIRM_APPLY ADD COLUMN CEC_BASELINE_REF VARCHAR(200);
ALTER TABLE IM_CONFIRM_APPLY ADD COLUMN CEC_CHANGE_VERSION INT;
ALTER TABLE IM_CONFIRM_APPLY ADD COLUMN CEC_CHANGE_SUMMARY VARCHAR(2000);
ALTER TABLE IM_CONFIRM_APPLY ADD COLUMN CEC_CHANGE_DIFF TEXT;

-- IM_CONFIRM_TABLE_ITEM
ALTER TABLE IM_CONFIRM_TABLE_ITEM ADD COLUMN CEC_RISK VARCHAR(500);
ALTER TABLE IM_CONFIRM_TABLE_ITEM ADD COLUMN CEC_SRC_ATT VARCHAR(300);
ALTER TABLE IM_CONFIRM_TABLE_ITEM ADD COLUMN CEC_G_ATT VARCHAR(300);
ALTER TABLE IM_CONFIRM_TABLE_ITEM ADD COLUMN CEC_H_ATT VARCHAR(300);
ALTER TABLE IM_CONFIRM_TABLE_ITEM ADD COLUMN CEC_I_ATT VARCHAR(300);
ALTER TABLE IM_CONFIRM_TABLE_ITEM ADD COLUMN CEC_J_ATT VARCHAR(300);
ALTER TABLE IM_CONFIRM_TABLE_ITEM ADD COLUMN CEC_SRC_MID VARCHAR(64);
ALTER TABLE IM_CONFIRM_TABLE_ITEM ADD COLUMN CEC_G_MID VARCHAR(64);
ALTER TABLE IM_CONFIRM_TABLE_ITEM ADD COLUMN CEC_H_MID VARCHAR(64);
ALTER TABLE IM_CONFIRM_TABLE_ITEM ADD COLUMN CEC_I_MID VARCHAR(64);
ALTER TABLE IM_CONFIRM_TABLE_ITEM ADD COLUMN CEC_J_MID VARCHAR(64);

-- IM_EQUITY_CARD_INFO
ALTER TABLE IM_EQUITY_CARD_INFO ADD COLUMN CEC_TABLE_CODE VARCHAR(128);
ALTER TABLE IM_EQUITY_CARD_INFO ADD COLUMN CEC_SCHEMA_NAME VARCHAR(128);
ALTER TABLE IM_EQUITY_CARD_INFO ADD COLUMN CEC_RIGHTS_CONTENT VARCHAR(1000);
ALTER TABLE IM_EQUITY_CARD_INFO ADD COLUMN CEC_RIGHTS_CREDENTIAL VARCHAR(1000);
ALTER TABLE IM_EQUITY_CARD_INFO ADD COLUMN CEC_ACQUIRE_MODE VARCHAR(40);
ALTER TABLE IM_EQUITY_CARD_INFO ADD COLUMN CEC_AUTH_UNIT VARCHAR(255);
ALTER TABLE IM_EQUITY_CARD_INFO ADD COLUMN CEC_CONFIRM_TIME DATETIME;

-- B) 基线缺失表(全新库 base schema 未含)。
CREATE TABLE IF NOT EXISTS SYS_ORGANIZATION (
  ID                     VARCHAR(60) NOT NULL,
  BIZ_ORG_ID             VARCHAR(32),
  BIZ_ORG_NAME           VARCHAR(200),
  BIZ_ORG_CODE           VARCHAR(60),
  SHORT_NAME             VARCHAR(200),
  PARENT_ID              VARCHAR(60),
  ORG_LEVEL              VARCHAR(32),
  ORG_TYPE               VARCHAR(32),
  CITY_CODE              VARCHAR(32),
  SORT_NO                VARCHAR(30),
  BASE_ORG_CODE          VARCHAR(120),
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS IM_CONFIRM_RECHECK_TASK (
  CEC_TASK_ID            VARCHAR(64)  NOT NULL,
  CEC_TASK_NO            VARCHAR(64),
  CEC_TASK_TYPE          VARCHAR(20),
  CEC_ASSET_ID           VARCHAR(64)  NOT NULL,
  CEC_ASSET_NAME         VARCHAR(255),
  CEC_SOURCE             VARCHAR(40),
  CEC_TRIGGER_TYPE       VARCHAR(100),
  CEC_REASON             VARCHAR(2000),
  CEC_DUE_DATE           DATETIME,
  CEC_STATUS             VARCHAR(20),
  CEC_APPLY_ID           VARCHAR(64),
  CEC_REF_NO             VARCHAR(64),
  CEC_HANDLER_ID         VARCHAR(64),
  CEC_HANDLER_NAME       VARCHAR(100),
  CEC_HANDLE_TIME        DATETIME,
  CEC_HANDLE_NOTE        VARCHAR(2000),
  CEC_PROVINCE_CODE      VARCHAR(32),
  CEC_BUREAU_CODE        VARCHAR(32),
  CEC_CREATOR_ID         VARCHAR(64),
  CEC_CREATE_TIME        DATETIME,
  CEC_UPDATER_ID         VARCHAR(64),
  CEC_UPDATE_TIME        DATETIME,
  CEC_DEL_FLAG           INT DEFAULT 0,
  PRIMARY KEY (CEC_TASK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS IM_SENSITIVE_VAULT (
  CEC_VAULT_ID           VARCHAR(64) NOT NULL,
  CEC_BIZ_TYPE           VARCHAR(50),
  CEC_BIZ_ID             VARCHAR(64),
  CEC_FIELD_NAME         VARCHAR(100),
  CEC_CIPHER_TEXT        TEXT,
  CEC_SM3_FINGERPRINT    VARCHAR(64),
  CEC_SM2_SIGNATURE      VARCHAR(160),
  CEC_CUSTODIAN          VARCHAR(255),
  CEC_PROVINCE_CODE      VARCHAR(32),
  CEC_BUREAU_CODE        VARCHAR(32),
  CEC_CREATOR_ID         VARCHAR(64),
  CEC_CREATE_TIME        DATETIME,
  CEC_UPDATER_ID         VARCHAR(64),
  CEC_UPDATE_TIME        DATETIME,
  CEC_DEL_FLAG           INT DEFAULT 0,
  PRIMARY KEY (CEC_VAULT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS IM_DPR_RISK (
  CEC_RISK_ID            VARCHAR(64)  NOT NULL,
  CEC_RISK_NO            VARCHAR(64),
  CEC_ASSET_ID           VARCHAR(64),
  CEC_RIGHT_TYPES        VARCHAR(255),
  CEC_RISK_TYPE          VARCHAR(100),
  CEC_RISK_CONTENT       VARCHAR(2000),
  CEC_RISK_LEVEL         VARCHAR(20),
  CEC_STRATEGY           VARCHAR(2000),
  CEC_ASSESSOR           VARCHAR(255),
  CEC_SOURCE_REF         VARCHAR(64),
  CEC_HANDLE_STATUS      VARCHAR(50),
  CEC_HANDLE_FEEDBACK    VARCHAR(2000),
  CEC_HANDLE_TIME        DATETIME,
  CEC_PROVINCE_CODE      VARCHAR(32),
  CEC_BUREAU_CODE        VARCHAR(32),
  CEC_CREATOR_ID         VARCHAR(64),
  CEC_CREATE_TIME        DATETIME,
  CEC_UPDATER_ID         VARCHAR(64),
  CEC_UPDATE_TIME        DATETIME,
  CEC_DEL_FLAG           INT DEFAULT 0,
  PRIMARY KEY (CEC_RISK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

