-- ============================================================================
-- 智能确权辅助工具(aitool) 达梦(DM8)库表脚本
-- 工具为独立模块:全部 IM_AIT_* 表自包含,与确权主流程仅通过 CEC_APPLY_ID 弱关联
-- (applyId 可为空,不建外键,不依赖主库任何表),可随工具独立建库部署。
-- 由 mysql/tool-mysql 的 MySQL 脚本转换为达梦语法:
--   ENGINE/CHARSET/COMMENT 内联/反引号 → 去除;列注释用 COMMENT ON COLUMN;
--   TINYINT(1)→INT;DATETIME→TIMESTAMP;TEXT→CLOB。
-- 与 dm8/02_schema_dm.sql 的 aitool 段同源;含本次扩展的全部 22 张表:
--   材料/多粒度切片/解析结果/表单比对/清洗底表与清洗日志/要素画像与五类主体与五类约束/
--   解析记录档/资料模板库/解析元数据配置/知识库文档与切片/权属主张与冲突与冲突规则/
--   Agent审核结果与审核证据链/批量任务/统一运行日志/决策建议。
-- 执行:  disql PRM_DPR/PRM_DPR2024!@localhost:5236 @01_aitool_schema_dm.sql
--   (库/表空间见 dm8/01_create_tablespace.sql;独立部署可先建库后执行本脚本)
-- ============================================================================

-- ---------- 智能确权辅助工具(采购集成,confirm 域承载) ----------

-- 上传材料
CREATE TABLE IM_AIT_MATERIAL (
  CEC_MATERIAL_ID   VARCHAR(64) NOT NULL,
  CEC_BATCH_NO      VARCHAR(64),
  CEC_APPLY_ID      VARCHAR(64),
  CEC_FILE_NAME     VARCHAR(500),
  CEC_FILE_TYPE     VARCHAR(20),
  CEC_FILE_HASH     VARCHAR(64),
  CEC_SIZE_KB       BIGINT,
  CEC_PARSE_STATUS  VARCHAR(20),
  CEC_FAIL_REASON   VARCHAR(1000),
  CEC_PROGRESS      INT DEFAULT 0,
  CEC_STORAGE_PATH  VARCHAR(500),
  CEC_CONTENT       CLOB,
  CEC_CATEGORY      VARCHAR(50),
  CEC_DATA_TABLE_REF VARCHAR(255),
  CEC_LAYOUT_JSON   CLOB,
  CEC_DUPLICATE_OF  VARCHAR(64),
  CEC_PAGE_COUNT    INT,
  CEC_OCR_USED      INT DEFAULT 0,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_MATERIAL_ID)
);
COMMENT ON TABLE IM_AIT_MATERIAL IS '智能工具-上传材料';

-- 智能确权辅助工具:多粒度解析片段(按页/段/表格单元)
CREATE TABLE IM_AIT_DOC_SEGMENT (
  CEC_SEGMENT_ID    VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_GRANULARITY   VARCHAR(20),
  CEC_PAGE_NO       INT,
  CEC_SEG_INDEX     INT,
  CEC_SHEET_NAME    VARCHAR(100),
  CEC_ROW_NUM       INT,
  CEC_COL_NUM       INT,
  CEC_CONTENT       CLOB,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_SEGMENT_ID)
);
COMMENT ON TABLE IM_AIT_DOC_SEGMENT IS '智能工具-多粒度解析片段';

-- 智能确权辅助工具:清洗日志(#6)
CREATE TABLE IM_AIT_CLEAN_LOG (
  CEC_LOG_ID        VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_BATCH_NO      VARCHAR(64),
  CEC_ROW_NO        INT,
  CEC_FIELD         VARCHAR(64),
  CEC_RAW_KEY       VARCHAR(128),
  CEC_ORIGINAL_VALUE VARCHAR(2000),
  CEC_RULE          VARCHAR(255),
  CEC_CLEANED_VALUE VARCHAR(2000),
  CEC_METHOD        VARCHAR(20),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
);
COMMENT ON TABLE IM_AIT_CLEAN_LOG IS '智能工具-清洗日志';

-- 智能确权辅助工具:统一审核底表(#4/#5)
CREATE TABLE IM_AIT_AUDIT_BASE (
  CEC_AUDIT_ID      VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_BATCH_NO      VARCHAR(64),
  CEC_ROW_NO        INT,
  CEC_TEMPLATE_FIELD VARCHAR(64),
  CEC_FIELD_LABEL   VARCHAR(64),
  CEC_RAW_VALUE     VARCHAR(2000),
  CEC_CLEAN_VALUE   VARCHAR(2000),
  CEC_STATUS        VARCHAR(20),
  CEC_ISSUE         VARCHAR(500),
  CEC_SUGGESTION    VARCHAR(500),
  CEC_DATA_TABLE_REF VARCHAR(255),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_AUDIT_ID)
);
COMMENT ON TABLE IM_AIT_AUDIT_BASE IS '智能工具-统一审核底表';

-- 智能确权辅助工具:结构化确权画像(#6)
CREATE TABLE IM_AIT_PROFILE (
  CEC_PROFILE_ID    VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_DATA_TABLE_REF VARCHAR(255),
  CEC_LEVEL         VARCHAR(20),
  CEC_SOURCE_METHOD VARCHAR(50),
  CEC_SOURCE_METHOD_BY VARCHAR(20),
  CEC_DATA_FEATURES VARCHAR(500),
  CEC_ELEMENTS_JSON CLOB,
  CEC_CONFIDENCE    DOUBLE,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_PROFILE_ID)
);
COMMENT ON TABLE IM_AIT_PROFILE IS '智能工具-确权画像';

-- 智能确权辅助工具:关键主体(#2)
CREATE TABLE IM_AIT_PROFILE_SUBJECT (
  CEC_SUBJECT_ID    VARCHAR(64) NOT NULL,
  CEC_PROFILE_ID    VARCHAR(64),
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_SUBJECT_ROLE  VARCHAR(40),
  CEC_SUBJECT_NAME  VARCHAR(500),
  CEC_METHOD        VARCHAR(20),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_SUBJECT_ID)
);
COMMENT ON TABLE IM_AIT_PROFILE_SUBJECT IS '智能工具-关键主体';

-- 智能确权辅助工具:约束信息(#5)
CREATE TABLE IM_AIT_CONSTRAINT (
  CEC_CONSTRAINT_ID VARCHAR(64) NOT NULL,
  CEC_PROFILE_ID    VARCHAR(64),
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_CONSTRAINT_TYPE VARCHAR(40),
  CEC_CONSTRAINT_VALUE VARCHAR(1000),
  CEC_METHOD        VARCHAR(20),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONSTRAINT_ID)
);
COMMENT ON TABLE IM_AIT_CONSTRAINT IS '智能工具-约束信息';

-- 智能确权辅助工具:解析记录档(1.4#1)
CREATE TABLE IM_AIT_PARSE_RECORD (
  CEC_RECORD_ID     VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_FILE_NAME     VARCHAR(500),
  CEC_BATCH_NO      VARCHAR(64),
  CEC_FIELD         VARCHAR(64),
  CEC_FIELD_VALUE   VARCHAR(2000),
  CEC_CONFIDENCE    DOUBLE,
  CEC_OPERATOR_ID   VARCHAR(64),
  CEC_OPERATOR_NAME VARCHAR(64),
  CEC_PARSE_TIME    TIMESTAMP,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RECORD_ID)
);
COMMENT ON TABLE IM_AIT_PARSE_RECORD IS '智能工具-解析记录档';

-- 智能确权辅助工具:资料模板库(1.4#3)
CREATE TABLE IM_AIT_DOC_TEMPLATE (
  CEC_TEMPLATE_ID   VARCHAR(64) NOT NULL,
  CEC_TEMPLATE_TYPE VARCHAR(50),
  CEC_TEMPLATE_NAME VARCHAR(255),
  CEC_VERSION       VARCHAR(20),
  CEC_CONTENT       CLOB,
  CEC_FILE_NAME     VARCHAR(300),
  CEC_FILE_DATA     CLOB,
  CEC_IS_LATEST     INT DEFAULT 1,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TEMPLATE_ID)
);
COMMENT ON TABLE IM_AIT_DOC_TEMPLATE IS '智能工具-资料模板库';

-- 智能确权辅助工具:解析元数据配置(1.4#4)
CREATE TABLE IM_AIT_PARSE_CONFIG (
  CEC_CONFIG_ID     VARCHAR(64) NOT NULL,
  CEC_SCENE         VARCHAR(50),
  CEC_FIELD_MAPPING_JSON CLOB,
  CEC_EXTRACT_LOGIC_JSON CLOB,
  CEC_CONFIDENCE_THRESHOLD DOUBLE,
  CEC_ENABLED       INT DEFAULT 1,
  CEC_REMARK        VARCHAR(500),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONFIG_ID)
);
COMMENT ON TABLE IM_AIT_PARSE_CONFIG IS '智能工具-解析元数据配置';

-- 智能确权辅助工具:产权知识库-文档(2.1#1/#6)
CREATE TABLE IM_AIT_KB_DOC (
  CEC_DOC_ID        VARCHAR(64) NOT NULL,
  CEC_DOC_TYPE      VARCHAR(40),
  CEC_DOMAIN        VARCHAR(40),
  CEC_TITLE         VARCHAR(300),
  CEC_SOURCE        VARCHAR(300),
  CEC_EFFECTIVE_DATE VARCHAR(20),
  CEC_SCOPE         VARCHAR(500),
  CEC_VERSION       VARCHAR(20),
  CEC_IS_LATEST     INT DEFAULT 1,
  CEC_STATUS        VARCHAR(20),
  CEC_CONTENT       CLOB,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_DOC_ID)
);
COMMENT ON TABLE IM_AIT_KB_DOC IS '智能工具-知识库文档';

-- 智能确权辅助工具:产权知识库-切片(2.1#2/#3)
CREATE TABLE IM_AIT_KB_CHUNK (
  CEC_CHUNK_ID      VARCHAR(64) NOT NULL,
  CEC_DOC_ID        VARCHAR(64),
  CEC_DOC_TYPE      VARCHAR(40),
  CEC_DOMAIN        VARCHAR(40),
  CEC_TITLE         VARCHAR(300),
  CEC_CLAUSE_NO     VARCHAR(50),
  CEC_TAGS          VARCHAR(500),
  CEC_CONTENT       CLOB,
  CEC_VECTOR_JSON   CLOB,
  CEC_VECTOR_DIM    INT,
  CEC_EFFECTIVE_DATE VARCHAR(20),
  CEC_SCOPE         VARCHAR(500),
  CEC_STATUS        VARCHAR(20),
  CEC_SEQ           INT,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CHUNK_ID)
);
COMMENT ON TABLE IM_AIT_KB_CHUNK IS '智能工具-知识库切片';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_MATERIAL_ID IS '材料ID';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_BATCH_NO IS '批次号';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_APPLY_ID IS '关联申请';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_FILE_NAME IS '文件名';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_FILE_TYPE IS '文件类型';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_FILE_HASH IS '文件指纹';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_SIZE_KB IS '大小KB';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_PARSE_STATUS IS '解析状态';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_FAIL_REASON IS '失败原因';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_PROGRESS IS '进度';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_STORAGE_PATH IS '存储路径';
COMMENT ON COLUMN IM_AIT_MATERIAL.CEC_CONTENT IS '抽取正文';

-- 材料解析要素
CREATE TABLE IM_AIT_PARSE_RESULT (
  CEC_PARSE_ID      VARCHAR(64) NOT NULL,
  CEC_MATERIAL_ID   VARCHAR(64),
  CEC_RIGHT_SUBJECT VARCHAR(500),
  CEC_RIGHT_OBJECT  VARCHAR(500),
  CEC_RIGHT_TYPE    VARCHAR(100),
  CEC_RIGHT_TERM    VARCHAR(100),
  CEC_AUTH_SCOPE    VARCHAR(500),
  CEC_DATA_SOURCE   VARCHAR(100),
  CEC_SENSITIVE_TYPE VARCHAR(100),
  CEC_SEAL_VALID    VARCHAR(20),
  CEC_SEAL_DESC     VARCHAR(500),
  CEC_CONFIDENCE    DOUBLE,
  CEC_REVIEW_STATUS VARCHAR(50),
  CEC_TRUST_SCORE   INT,
  CEC_TRUST_LEVEL   VARCHAR(50),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_PARSE_ID)
);
COMMENT ON TABLE IM_AIT_PARSE_RESULT IS '智能工具-解析要素';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_PARSE_ID IS '解析ID';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_MATERIAL_ID IS '材料ID';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_RIGHT_SUBJECT IS '权利主体';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_RIGHT_OBJECT IS '权利客体';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_RIGHT_TYPE IS '产权类型';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_RIGHT_TERM IS '权利期限';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_AUTH_SCOPE IS '授权范围';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_DATA_SOURCE IS '数据来源';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_SENSITIVE_TYPE IS '敏感类型';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_SEAL_VALID IS '签章有效';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_SEAL_DESC IS '签章说明';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_CONFIDENCE IS '置信度';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_REVIEW_STATUS IS '复核标记(自动通过/需人工复核,阈值0.95)';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_TRUST_SCORE IS '材料可信度评分0-100(印章交叉校验+置信度+要素完整性)';
COMMENT ON COLUMN IM_AIT_PARSE_RESULT.CEC_TRUST_LEVEL IS '材料可信度评级(可信/存疑/不可信)';

-- 材料与表单比对
CREATE TABLE IM_AIT_COMPARE (
  CEC_COMPARE_ID     VARCHAR(64) NOT NULL,
  CEC_PARSE_ID       VARCHAR(64),
  CEC_APPLY_ID       VARCHAR(64),
  CEC_FIELD          VARCHAR(100),
  CEC_MATERIAL_VALUE VARCHAR(1000),
  CEC_FORM_VALUE     VARCHAR(1000),
  CEC_DIFF_TYPE      VARCHAR(20),
  CEC_SOURCE_OFFSET  INT,
  CEC_SOURCE_SNIPPET VARCHAR(500),
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    TIMESTAMP,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    TIMESTAMP,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_COMPARE_ID)
);
COMMENT ON TABLE IM_AIT_COMPARE IS '智能工具-材料表单比对';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_COMPARE_ID IS '比对ID';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_PARSE_ID IS '解析ID';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_FIELD IS '字段';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_MATERIAL_VALUE IS '材料值';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_FORM_VALUE IS '表单值';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_DIFF_TYPE IS '差异类型';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_SOURCE_OFFSET IS '材料值在原始正文的字符偏移(-1=未定位/图片)';
COMMENT ON COLUMN IM_AIT_COMPARE.CEC_SOURCE_SNIPPET IS '原始正文定位上下文片段';

-- 权属主张(知识图谱)
CREATE TABLE IM_AIT_KG_CLAIM (
  CEC_CLAIM_ID      VARCHAR(64) NOT NULL,
  CEC_ASSET_ID      VARCHAR(64),
  CEC_SUBJECT       VARCHAR(255),
  CEC_RIGHT_TYPE    VARCHAR(100),
  CEC_AUTH_SCOPE    VARCHAR(500),
  CEC_VALID_DATE    TIMESTAMP,
  CEC_EXCLUSIVE     SMALLINT,
  CEC_SOURCE_TYPE   VARCHAR(50),
  CEC_REMARK        VARCHAR(1000),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CLAIM_ID)
);
COMMENT ON TABLE IM_AIT_KG_CLAIM IS '智能工具-权属主张(KG)';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_CLAIM_ID IS '主张ID';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_SUBJECT IS '主体';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_RIGHT_TYPE IS '产权类型';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_AUTH_SCOPE IS '授权范围';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_VALID_DATE IS '有效期';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_EXCLUSIVE IS '是否独占';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_SOURCE_TYPE IS '来源类型';
COMMENT ON COLUMN IM_AIT_KG_CLAIM.CEC_REMARK IS '备注';
CREATE INDEX IDX_KG_ASSET ON IM_AIT_KG_CLAIM (CEC_ASSET_ID);

-- 权属冲突
CREATE TABLE IM_AIT_CONFLICT (
  CEC_CONFLICT_ID    VARCHAR(64) NOT NULL,
  CEC_ASSET_ID       VARCHAR(64),
  CEC_CONFLICT_TYPE  VARCHAR(50),
  CEC_CONFLICT_SOURCE VARCHAR(255),
  CEC_CONFLICT_DESC  VARCHAR(2000),
  CEC_IMPACT_SCOPE   VARCHAR(1000),
  CEC_RISK_LEVEL     VARCHAR(20),
  CEC_SUGGESTION     VARCHAR(2000),
  CEC_STATUS         VARCHAR(20),
  CEC_RELATED_RECORD_NO VARCHAR(255),
  CEC_CONFLICT_FIELDS VARCHAR(255),
  CEC_CLAUSE_REF     VARCHAR(500),
  CEC_LEGAL_RISK     VARCHAR(40),
  CEC_PROVINCE_CODE  VARCHAR(32),
  CEC_BUREAU_CODE    VARCHAR(32),
  CEC_CREATOR_ID     VARCHAR(64),
  CEC_CREATE_TIME    TIMESTAMP,
  CEC_UPDATER_ID     VARCHAR(64),
  CEC_UPDATE_TIME    TIMESTAMP,
  CEC_DEL_FLAG       INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_CONFLICT_ID)
);
COMMENT ON TABLE IM_AIT_CONFLICT IS '智能工具-权属冲突';

-- 智能确权辅助工具:冲突识别规则配置
CREATE TABLE IM_AIT_CONFLICT_RULE (
  CEC_RULE_ID       VARCHAR(64) NOT NULL,
  CEC_RULE_TYPE     VARCHAR(40),
  CEC_RULE_NAME     VARCHAR(100),
  CEC_ENABLED       INT DEFAULT 1,
  CEC_PRIORITY      INT DEFAULT 100,
  CEC_THRESHOLD     DOUBLE,
  CEC_REMARK        VARCHAR(500),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_RULE_ID)
);
COMMENT ON TABLE IM_AIT_CONFLICT_RULE IS '智能工具-冲突识别规则';

-- 智能确权辅助工具:智能确权 Agent 审核结果(3.1)
CREATE TABLE IM_AIT_AUDIT_RESULT (
  CEC_AUDIT_ID      VARCHAR(64) NOT NULL,
  CEC_APPLY_ID      VARCHAR(64),
  CEC_ASSET_ID      VARCHAR(64),
  CEC_CHANNEL       VARCHAR(20),
  CEC_DATA_CLASS    VARCHAR(100),
  CEC_DATA_GRADE    VARCHAR(40),
  CEC_RIGHT_TYPE    VARCHAR(100),
  CEC_AUTH_ADVICE   VARCHAR(40),
  CEC_AUTH_LEVEL    VARCHAR(40),
  CEC_RESTRICTIONS  VARCHAR(1000),
  CEC_RISK_LEVEL    VARCHAR(20),
  CEC_SUPPLEMENT    VARCHAR(1000),
  CEC_REASON        VARCHAR(2000),
  CEC_CITATIONS     VARCHAR(1000),
  CEC_ACTION        VARCHAR(255),
  CEC_SCORE         DOUBLE,
  CEC_STAGE_TRACE_JSON CLOB,
  CEC_TOOL_TRACE_JSON  CLOB,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_AUDIT_ID)
);
COMMENT ON TABLE IM_AIT_AUDIT_RESULT IS '智能工具-Agent审核结果';

-- 智能确权辅助工具:批量任务(3.3#5/#4)
CREATE TABLE IM_AIT_TASK (
  CEC_TASK_ID       VARCHAR(64) NOT NULL,
  CEC_TASK_TYPE     VARCHAR(40),
  CEC_TASK_NAME     VARCHAR(200),
  CEC_ITEMS_JSON    CLOB,
  CEC_ITEM_STATE_JSON CLOB,
  CEC_TOTAL         INT DEFAULT 0,
  CEC_DONE          INT DEFAULT 0,
  CEC_FAILED        INT DEFAULT 0,
  CEC_STATUS        VARCHAR(20),
  CEC_CONCURRENCY   INT DEFAULT 4,
  CEC_RETRY_MAX     INT DEFAULT 2,
  CEC_CURSOR        INT DEFAULT 0,
  CEC_LAST_ERROR    VARCHAR(1000),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_TASK_ID)
);
COMMENT ON TABLE IM_AIT_TASK IS '智能工具-批量任务';

-- 智能确权辅助工具:统一运行日志(3.3#6)
CREATE TABLE IM_AIT_RUN_LOG (
  CEC_LOG_ID        VARCHAR(64) NOT NULL,
  CEC_LOG_TYPE      VARCHAR(20),
  CEC_SOURCE        VARCHAR(100),
  CEC_ACTION        VARCHAR(100),
  CEC_DETAIL        VARCHAR(2000),
  CEC_MODEL         VARCHAR(64),
  CEC_DURATION_MS   BIGINT,
  CEC_RESULT        VARCHAR(20),
  CEC_TASK_ID       VARCHAR(64),
  CEC_LOG_TIME      TIMESTAMP,
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_LOG_ID)
);
COMMENT ON TABLE IM_AIT_RUN_LOG IS '智能工具-统一运行日志';

-- 智能确权辅助工具:审核证据链档案(3.2#4)
CREATE TABLE IM_AIT_EVIDENCE (
  CEC_EVIDENCE_ID   VARCHAR(64) NOT NULL,
  CEC_APPLY_ID      VARCHAR(64),
  CEC_ASSET_ID      VARCHAR(64),
  CEC_MATERIAL_SNIPPETS_JSON CLOB,
  CEC_KB_HITS_JSON  CLOB,
  CEC_RULE_HITS_JSON CLOB,
  CEC_MODEL_REASON  CLOB,
  CEC_CONCLUSION    VARCHAR(500),
  CEC_SM3_HASH      VARCHAR(80),
  CEC_PROVINCE_CODE VARCHAR(32),
  CEC_BUREAU_CODE   VARCHAR(32),
  CEC_CREATOR_ID    VARCHAR(64),
  CEC_CREATE_TIME   TIMESTAMP,
  CEC_UPDATER_ID    VARCHAR(64),
  CEC_UPDATE_TIME   TIMESTAMP,
  CEC_DEL_FLAG      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_EVIDENCE_ID)
);
COMMENT ON TABLE IM_AIT_EVIDENCE IS '智能工具-审核证据链';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_CONFLICT_ID IS '冲突ID';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_CONFLICT_TYPE IS '冲突类型';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_CONFLICT_SOURCE IS '冲突来源';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_CONFLICT_DESC IS '冲突描述';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_IMPACT_SCOPE IS '影响范围';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_RISK_LEVEL IS '风险级别';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_SUGGESTION IS '消解建议';
COMMENT ON COLUMN IM_AIT_CONFLICT.CEC_STATUS IS '状态';
CREATE INDEX IDX_CFL_ASSET ON IM_AIT_CONFLICT (CEC_ASSET_ID);

-- 确权决策建议
CREATE TABLE IM_AIT_DECISION (
  CEC_DECISION_ID      VARCHAR(64) NOT NULL,
  CEC_APPLY_ID         VARCHAR(64),
  CEC_ASSET_ID         VARCHAR(64),
  CEC_PREDICTION       VARCHAR(50),
  CEC_SCORE            DOUBLE,
  CEC_FACTORS_JSON     CLOB,
  CEC_STRENGTH         VARCHAR(500),
  CEC_WEAKNESS         VARCHAR(500),
  CEC_SPLIT_PLAN       VARCHAR(2000),
  CEC_SPLIT_PLANS_JSON CLOB,
  CEC_REASON           VARCHAR(2000),
  CEC_SUPPLEMENT       VARCHAR(1000),
  CEC_PENDING_CONFLICTS VARCHAR(1000),
  CEC_RAG_ADVICE       CLOB,
  CEC_AI_PREDICTION    VARCHAR(50),
  CEC_RAG_CITATIONS    VARCHAR(1000),
  CEC_EVIDENCE_CHAIN   VARCHAR(80),
  CEC_PROVINCE_CODE    VARCHAR(32),
  CEC_BUREAU_CODE      VARCHAR(32),
  CEC_CREATOR_ID       VARCHAR(64),
  CEC_CREATE_TIME      TIMESTAMP,
  CEC_UPDATER_ID       VARCHAR(64),
  CEC_UPDATE_TIME      TIMESTAMP,
  CEC_DEL_FLAG         INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CEC_DECISION_ID)
);
COMMENT ON TABLE IM_AIT_DECISION IS '智能工具-确权决策建议';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_DECISION_ID IS '决策ID';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_APPLY_ID IS '申请ID';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_ASSET_ID IS '资产ID';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_PREDICTION IS '预测结论';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_SCORE IS '评分';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_FACTORS_JSON IS '因子JSON';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_STRENGTH IS '优势';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_WEAKNESS IS '不足';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_SPLIT_PLAN IS '三权分置建议';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_SPLIT_PLANS_JSON IS '权益分割多方案明细JSON';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_REASON IS '理由';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_SUPPLEMENT IS '补充建议';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_PENDING_CONFLICTS IS '待解冲突';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_RAG_ADVICE IS 'RAG法规建议';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_AI_PREDICTION IS 'AI预测结论';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_RAG_CITATIONS IS 'RAG法规引用';
COMMENT ON COLUMN IM_AIT_DECISION.CEC_EVIDENCE_CHAIN IS '存证链';
CREATE INDEX IDX_DEC_APPLY ON IM_AIT_DECISION (CEC_APPLY_ID);

-- 完。智能确权辅助工具 IM_AIT_* 全部表(达梦 DM8)。
