-- 产权档案表(开发/测试 H2,MySQL 兼容模式)。生产由达梦 DDL 脚本建表。
-- 敏感信息保险箱(SM4 加密 + SM3 指纹 + SM2 签名留痕,等保三级/国密)
CREATE TABLE IF NOT EXISTS IM_SENSITIVE_VAULT (
    CEC_VAULT_ID        VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_BIZ_TYPE        VARCHAR(50),
    CEC_BIZ_ID          VARCHAR(64),
    CEC_FIELD_NAME      VARCHAR(100),
    CEC_CIPHER_TEXT     CLOB,
    CEC_SM3_FINGERPRINT VARCHAR(64),
    CEC_SM2_SIGNATURE   VARCHAR(160),
    CEC_CUSTODIAN       VARCHAR(255),
    CEC_PROVINCE_CODE   VARCHAR(32),
    CEC_BUREAU_CODE     VARCHAR(32),
    CEC_CREATOR_ID      VARCHAR(64),
    CEC_CREATE_TIME     TIMESTAMP,
    CEC_UPDATER_ID      VARCHAR(64),
    CEC_UPDATE_TIME     TIMESTAMP,
    CEC_DEL_FLAG        INT DEFAULT 0
);

-- 区块链存证记录(国密SM3指纹 + 上链回执,全节点留痕,prm-common 共享)
CREATE TABLE IF NOT EXISTS IM_DPR_EVIDENCE (
    CEC_EVIDENCE_ID   VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_BIZ_TYPE      VARCHAR(50),
    CEC_BIZ_ID        VARCHAR(64),
    CEC_SUMMARY       VARCHAR(500),
    CEC_SM3_HASH      VARCHAR(64),
    CEC_CHAIN_TX_HASH VARCHAR(80),
    CEC_BLOCK_HEIGHT  BIGINT,
    CEC_ANCHOR_STATUS VARCHAR(20),
    CEC_EVIDENCE_TIME TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS IM_PROPERTY_ARCHIVE (
    CEC_ARCHIVE_ID     VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_ASSET_ID       VARCHAR(64)  NOT NULL,
    CEC_ASSET_NAME     VARCHAR(255) NOT NULL,
    CEC_RIGHT_TYPE     VARCHAR(255),
    CEC_RIGHT_SUBJECT  VARCHAR(255),
    CEC_RIGHT_OBJECT   VARCHAR(255),
    CEC_ACQUIRE_MODE   VARCHAR(100),
    CEC_USE_SCOPE      VARCHAR(1000),
    CEC_RESP_DEPT      VARCHAR(255),
    CEC_VALID_DATE     TIMESTAMP,
    CEC_CONFIRM_STATUS VARCHAR(50),
    CEC_CONFIRM_DETAIL VARCHAR(255),
    CEC_AUTH_STATUS    VARCHAR(50),
    CEC_EQUITY_CARD_ID VARCHAR(64),
    CEC_PROVINCE_CODE  VARCHAR(32),
    CEC_BUREAU_CODE    VARCHAR(32),
    CEC_CREATOR_ID     VARCHAR(64),
    CEC_CREATE_TIME    TIMESTAMP,
    CEC_UPDATER_ID     VARCHAR(64),
    CEC_UPDATE_TIME    TIMESTAMP,
    CEC_DEL_FLAG       INT DEFAULT 0
);

-- 数据资产信息表(由数据资产管理平台目录同步,确权/树/概览的底座)
CREATE TABLE IF NOT EXISTS IM_DPM_DATA_ASSET_INFO (
    CEC_ASSET_ID         VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_ASSET_NAME       VARCHAR(255) NOT NULL,
    CEC_ASSET_TYPE       VARCHAR(100),
    CEC_SOURCE_OF_ASSETS VARCHAR(255),
    CEC_ASSET_STATUS     VARCHAR(50),
    CEC_ASSET_OWNER      VARCHAR(100),
    CEC_SUBSIDIARY_NAME  VARCHAR(255),
    CEC_SYSTEM_NAME      VARCHAR(255),
    CEC_SCHEMA_NAME      VARCHAR(255),
    CEC_SECURITY_LEVEL   VARCHAR(50),
    CEC_RESP_DEPT        VARCHAR(255),
    CEC_PROVINCE_CODE    VARCHAR(32),
    CEC_BUREAU_CODE      VARCHAR(32),
    CEC_CREATOR_ID       VARCHAR(64),
    CEC_CREATE_TIME      TIMESTAMP,
    CEC_UPDATER_ID       VARCHAR(64),
    CEC_UPDATE_TIME      TIMESTAMP,
    CEC_DEL_FLAG         INT DEFAULT 0
);

-- 产权变更记录表(由确权/授权审批流事件自动生成,防篡改证据链)
CREATE TABLE IF NOT EXISTS IM_PROPERTY_CHANGE_RECORD (
    CEC_CHANGE_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_ASSET_ID       VARCHAR(64)  NOT NULL,
    CEC_CHANGE_TYPE    VARCHAR(100) NOT NULL,
    CEC_FIELD_NAME     VARCHAR(100),
    CEC_BEFORE_VALUE   VARCHAR(2000),
    CEC_AFTER_VALUE    VARCHAR(2000),
    CEC_CHANGE_REASON  VARCHAR(1000),
    CEC_SOURCE_FLOW    VARCHAR(100),
    CEC_SOURCE_TICKET  VARCHAR(64),
    CEC_OPERATOR_ID    VARCHAR(64),
    CEC_CHANGE_TIME    TIMESTAMP,
    CEC_CHAIN_HASH     VARCHAR(128),
    CEC_PROVINCE_CODE  VARCHAR(32),
    CEC_BUREAU_CODE    VARCHAR(32),
    CEC_CREATOR_ID     VARCHAR(64),
    CEC_CREATE_TIME    TIMESTAMP,
    CEC_UPDATER_ID     VARCHAR(64),
    CEC_UPDATE_TIME    TIMESTAMP,
    CEC_DEL_FLAG       INT DEFAULT 0
);

-- 监测规则配置表
CREATE TABLE IF NOT EXISTS IM_MONITOR_RULE (
    CEC_RULE_ID        VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_RULE_NAME      VARCHAR(255) NOT NULL,
    CEC_RULE_CATEGORY  VARCHAR(100),
    CEC_MONITOR_TARGET VARCHAR(255),
    CEC_TRIGGER_COND   CLOB,
    CEC_THRESHOLD      VARCHAR(500),
    CEC_PRIORITY       VARCHAR(20),
    CEC_NOTIFY_TARGET  VARCHAR(500),
    CEC_NOTIFY_CHANNEL VARCHAR(200),
    CEC_RULE_VERSION   VARCHAR(20),
    CEC_EFFECT_STATUS  VARCHAR(20),
    CEC_CIRCUIT_BREAK  INT DEFAULT 0,
    CEC_PROVINCE_CODE  VARCHAR(32),
    CEC_BUREAU_CODE    VARCHAR(32),
    CEC_CREATOR_ID     VARCHAR(64),
    CEC_CREATE_TIME    TIMESTAMP,
    CEC_UPDATER_ID     VARCHAR(64),
    CEC_UPDATE_TIME    TIMESTAMP,
    CEC_DEL_FLAG       INT DEFAULT 0
);

-- 风险预警记录表
CREATE TABLE IF NOT EXISTS IM_ALERT_RECORD (
    CEC_ALERT_ID         VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_RULE_ID          VARCHAR(64),
    CEC_SOURCE           VARCHAR(50),
    CEC_ASSET_ID         VARCHAR(64),
    CEC_ALERT_LEVEL      VARCHAR(20)  NOT NULL,
    CEC_TRIGGER_COND     VARCHAR(1000),
    CEC_ABNORMAL_DESC    VARCHAR(2000),
    CEC_ALERT_TIME       TIMESTAMP,
    CEC_DISPOSE_STATUS   VARCHAR(50)  NOT NULL,
    CEC_DISPOSE_FEEDBACK VARCHAR(2000),
    CEC_RESPONDER_ID     VARCHAR(64),
    CEC_CLOSE_TIME       TIMESTAMP,
    CEC_PROVINCE_CODE    VARCHAR(32),
    CEC_BUREAU_CODE      VARCHAR(32),
    CEC_CREATOR_ID       VARCHAR(64),
    CEC_CREATE_TIME      TIMESTAMP,
    CEC_UPDATER_ID       VARCHAR(64),
    CEC_UPDATE_TIME      TIMESTAMP,
    CEC_DEL_FLAG         INT DEFAULT 0
);

-- 风险预警定向通知表(可研 -006 推送/通知责任人)
CREATE TABLE IF NOT EXISTS IM_ALERT_NOTIFICATION (
    CEC_NOTIFY_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_ALERT_ID       VARCHAR(64),
    CEC_ASSET_ID       VARCHAR(64),
    CEC_RECIPIENT      VARCHAR(200),
    CEC_CHANNEL        VARCHAR(200),
    CEC_TITLE          VARCHAR(500),
    CEC_CONTENT        VARCHAR(2000),
    CEC_ALERT_LEVEL    VARCHAR(20),
    CEC_READ_STATUS    VARCHAR(20),
    CEC_PUSH_TIME      TIMESTAMP,
    CEC_READ_TIME      TIMESTAMP,
    CEC_PROVINCE_CODE  VARCHAR(32),
    CEC_BUREAU_CODE    VARCHAR(32),
    CEC_CREATOR_ID     VARCHAR(64),
    CEC_CREATE_TIME    TIMESTAMP,
    CEC_UPDATER_ID     VARCHAR(64),
    CEC_UPDATE_TIME    TIMESTAMP,
    CEC_DEL_FLAG       INT DEFAULT 0
);

-- 合规检查结果表
CREATE TABLE IF NOT EXISTS IM_COMPLIANCE_RESULT (
    CEC_CHECK_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_ASSET_ID       VARCHAR(64),
    CEC_RULE_ID        VARCHAR(64),
    CEC_CHECK_RESULT   VARCHAR(50),
    CEC_PROBLEM_DESC   VARCHAR(2000),
    CEC_SUGGESTION     VARCHAR(2000),
    CEC_REPORT_URL     VARCHAR(500),
    CEC_CHECK_TIME     TIMESTAMP,
    CEC_DISPOSE_STATUS VARCHAR(50),
    CEC_CHECK_DIM      VARCHAR(50),
    CEC_PROVINCE_CODE  VARCHAR(32),
    CEC_BUREAU_CODE    VARCHAR(32),
    CEC_CREATOR_ID     VARCHAR(64),
    CEC_CREATE_TIME    TIMESTAMP,
    CEC_UPDATER_ID     VARCHAR(64),
    CEC_UPDATE_TIME    TIMESTAMP,
    CEC_DEL_FLAG       INT DEFAULT 0
);

-- 数据权益风险表(附录F / 3.3.3 权益风险处置)
CREATE TABLE IF NOT EXISTS IM_DPR_RISK (
    CEC_RISK_ID        VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_RISK_NO        VARCHAR(64),
    CEC_ASSET_ID       VARCHAR(64),
    CEC_RIGHT_TYPES    VARCHAR(255),
    CEC_RISK_TYPE      VARCHAR(100),
    CEC_RISK_CONTENT   VARCHAR(2000),
    CEC_RISK_LEVEL     VARCHAR(20),
    CEC_STRATEGY       VARCHAR(2000),
    CEC_ASSESSOR       VARCHAR(255),
    CEC_SOURCE_REF     VARCHAR(64),
    CEC_HANDLE_STATUS  VARCHAR(50),
    CEC_HANDLE_FEEDBACK VARCHAR(2000),
    CEC_HANDLE_TIME    TIMESTAMP,
    CEC_PROVINCE_CODE  VARCHAR(32),
    CEC_BUREAU_CODE    VARCHAR(32),
    CEC_CREATOR_ID     VARCHAR(64),
    CEC_CREATE_TIME    TIMESTAMP,
    CEC_UPDATER_ID     VARCHAR(64),
    CEC_UPDATE_TIME    TIMESTAMP,
    CEC_DEL_FLAG       INT DEFAULT 0
);
