-- 数据授权申请单表
-- 区块链存证记录(国密SM3指纹 + 上链回执,全节点留痕,prm-common 共享)
CREATE TABLE IF NOT EXISTS IM_DPR_EVIDENCE (
    CEC_EVIDENCE_ID   VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_BIZ_TYPE      VARCHAR(50),
    CEC_BIZ_ID        VARCHAR(64),
    CEC_SUMMARY       VARCHAR(500),
    CEC_SM3_HASH      VARCHAR(64),
    CEC_CHAIN_TX_HASH VARCHAR(80),
    CEC_BLOCK_HEIGHT  BIGINT,
    CEC_ANCHOR_STATUS VARCHAR(20),
    CEC_EVIDENCE_TIME TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS IM_AUTH_APPLY (
    CEC_APPLY_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_APPLY_NO      VARCHAR(64),
    CEC_AUTH_MODE     VARCHAR(50),
    CEC_ASSET_ID      VARCHAR(64)  NOT NULL,
    CEC_ASSET_NAME    VARCHAR(255) NOT NULL,
    CEC_EQUITY_CARD_ID VARCHAR(64),
    CEC_GRANTEE_ORG   VARCHAR(255),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_SCENARIO      VARCHAR(500),
    CEC_SCOPE         VARCHAR(1000),
    CEC_VALID_DATE    TIMESTAMP,
    CEC_STATUS        VARCHAR(50),
    CEC_REJECT_REASON VARCHAR(1000),
    CEC_CURRENT_NODE  INT,
    CEC_BATCH_LIST_ID VARCHAR(64),
    CEC_NEED_CONFIDENTIALITY BOOLEAN,
    CEC_CONFIDENTIALITY_FILE VARCHAR(500),
    CEC_BUSINESS_DOMAIN   VARCHAR(100),
    CEC_CROSS_REGION      BOOLEAN,
    CEC_THIRD_PARTY_SOURCE VARCHAR(255),
    CEC_THIRD_PARTY_LICENSE VARCHAR(1000),
    CEC_SENSITIVE_TYPE    VARCHAR(100),
    CEC_SCHEMA_NAME       VARCHAR(255),
    CEC_BENEFIT_ALLOC     VARCHAR(1000),
    CEC_SECURITY_REQ      VARCHAR(1000),
    CEC_INFO_AUTH_AGREEMENT VARCHAR(500),
    CEC_APPLICANT_MANAGER VARCHAR(100),
    CEC_CONTACT           VARCHAR(100),
    CEC_AI_SNAPSHOT   CLOB,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 大模型校验操作留痕(南网"全流程留痕追溯",prm-common 跨域共享:确权 + 授权)
CREATE TABLE IF NOT EXISTS IM_DPR_AI_RUNLOG (
    CEC_LOG_ID        VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_BIZ_TYPE      VARCHAR(20),
    CEC_APPLY_ID      VARCHAR(64)  NOT NULL,
    CEC_CAPABILITY    VARCHAR(40),
    CEC_MODEL         VARCHAR(64),
    CEC_INPUT_SUMMARY VARCHAR(2000),
    CEC_OUTPUT        CLOB,
    CEC_DURATION_MS   BIGINT,
    CEC_SM3_HASH      VARCHAR(64),
    CEC_TRIGGER_USER  VARCHAR(64),
    CEC_EVIDENCE_ID   VARCHAR(64),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 对外数据经营权授权备案(附录G / 附录F §3.4.6)
CREATE TABLE IF NOT EXISTS IM_AUTH_FILING (
    CEC_FILING_ID     VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_FILING_NO     VARCHAR(64),
    CEC_AGREEMENT_ID  VARCHAR(64),
    CEC_APPLY_ID      VARCHAR(64),
    CEC_FILING_ORG    VARCHAR(255),
    CEC_GRANTEE_ORG   VARCHAR(255),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_AGREEMENT_NO  VARCHAR(64),
    CEC_VALID_DATE    TIMESTAMP,
    CEC_FILING_STATUS VARCHAR(50),
    CEC_FILING_TIME   TIMESTAMP,
    CEC_REMARK        VARCHAR(1000),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 表6 数据批量授权清单
CREATE TABLE IF NOT EXISTS IM_BATCH_AUTH_LIST (
    CEC_BATCH_LIST_ID VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_LIST_NO       VARCHAR(64),
    CEC_LIST_YEAR     VARCHAR(20),
    CEC_LIST_STATUS   VARCHAR(50),
    CEC_ITEM_COUNT    INT,
    CEC_REMARK        VARCHAR(1000),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 授权权益证书表
CREATE TABLE IF NOT EXISTS IM_AUTH_CERT (
    CEC_CERT_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_CERT_NO       VARCHAR(64),
    CEC_APPLY_ID      VARCHAR(64),
    CEC_ASSET_ID      VARCHAR(64),
    CEC_GRANTEE_ORG   VARCHAR(255),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_SCOPE         VARCHAR(1000),
    CEC_VALID_DATE    TIMESTAMP,
    CEC_CERT_STATUS   VARCHAR(50),
    CEC_SUSPEND_REASON VARCHAR(1000),
    CEC_TEMPLATE_ID    VARCHAR(64),
    CEC_TEMPLATE_NAME  VARCHAR(255),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 违规追责记录(监测联动熔断暂停授权时建账,附录F 3.4.5)
CREATE TABLE IF NOT EXISTS IM_AUTH_ACCOUNTABILITY (
    CEC_ACCOUNT_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_CERT_ID          VARCHAR(64),
    CEC_ASSET_ID         VARCHAR(64),
    CEC_GRANTEE_ORG      VARCHAR(255),
    CEC_VIOLATION_TYPE   VARCHAR(100),
    CEC_SOURCE_ALERT_ID  VARCHAR(64),
    CEC_REASON           VARCHAR(1000),
    CEC_HANDLE_STATUS    VARCHAR(50),
    CEC_RESPONSIBLE_PARTY VARCHAR(255),
    CEC_HANDLE_FEEDBACK  VARCHAR(1000),
    CEC_HANDLE_TIME      TIMESTAMP,
    CEC_PROVINCE_CODE    VARCHAR(32),
    CEC_BUREAU_CODE      VARCHAR(32),
    CEC_CREATOR_ID       VARCHAR(64),
    CEC_CREATE_TIME      TIMESTAMP,
    CEC_UPDATER_ID       VARCHAR(64),
    CEC_UPDATE_TIME      TIMESTAMP,
    CEC_DEL_FLAG         INT DEFAULT 0
);

-- 授权域通用目录项(指引/场景/申请表单模板/协议模板库)
CREATE TABLE IF NOT EXISTS IM_AUTH_CATALOG_ITEM (
    CEC_ITEM_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_CATEGORY      VARCHAR(50)  NOT NULL,
    CEC_NAME          VARCHAR(255) NOT NULL,
    CEC_ITEM_TYPE     VARCHAR(100),
    CEC_VERSION       VARCHAR(20),
    CEC_CONTENT       CLOB,
    CEC_STATUS        VARCHAR(50),
    CEC_PUBLISHER     VARCHAR(100),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 授权申请合规校验结果
CREATE TABLE IF NOT EXISTS IM_AUTH_COMPLIANCE (
    CEC_CHECK_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_APPLY_ID      VARCHAR(64),
    CEC_RISK_LEVEL    VARCHAR(20),
    CEC_CHECK_RESULT  VARCHAR(50),
    CEC_PROBLEM_DESC  VARCHAR(2000),
    CEC_CHECK_REPORT  CLOB,
    CEC_CHECK_TIME    TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 数据运营授权协议(签章/审核/存档/下载)
CREATE TABLE IF NOT EXISTS IM_AUTH_AGREEMENT (
    CEC_AGREEMENT_ID   VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_AGREEMENT_NO   VARCHAR(64),
    CEC_APPLY_ID       VARCHAR(64),
    CEC_TEMPLATE_ID    VARCHAR(64),
    CEC_GRANTEE_ORG    VARCHAR(255),
    CEC_FILE_URL       VARCHAR(500),
    CEC_SEAL_STATUS    VARCHAR(50),
    CEC_SEAL_VERIFY    VARCHAR(100),
    CEC_GRANTOR_SIGNED BOOLEAN,
    CEC_GRANTOR_SIGN_TIME TIMESTAMP,
    CEC_GRANTEE_SIGNED BOOLEAN,
    CEC_GRANTEE_SIGN_TIME TIMESTAMP,
    CEC_REVIEW_STATUS  VARCHAR(50),
    CEC_ARCHIVE_STATUS VARCHAR(50),
    CEC_AGREEMENT_TYPE VARCHAR(100),
    CEC_DEPT_NAME      VARCHAR(255),
    CEC_ARCHIVE_TIME   TIMESTAMP,
    CEC_SIGN_TIME      TIMESTAMP,
    CEC_PROVINCE_CODE  VARCHAR(32),
    CEC_BUREAU_CODE    VARCHAR(32),
    CEC_CREATOR_ID     VARCHAR(64),
    CEC_CREATE_TIME    TIMESTAMP,
    CEC_UPDATER_ID     VARCHAR(64),
    CEC_UPDATE_TIME    TIMESTAMP,
    CEC_DEL_FLAG       INT DEFAULT 0
);

-- 对外数据经营权授权备案(附录G)
CREATE TABLE IF NOT EXISTS IM_AUTH_FILING (
    CEC_FILING_ID     VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_FILING_NO     VARCHAR(64),
    CEC_AGREEMENT_ID  VARCHAR(64),
    CEC_APPLY_ID      VARCHAR(64),
    CEC_FILING_ORG    VARCHAR(255),
    CEC_GRANTEE_ORG   VARCHAR(255),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_AGREEMENT_NO  VARCHAR(64),
    CEC_VALID_DATE    TIMESTAMP,
    CEC_FILING_STATUS VARCHAR(50),
    CEC_FILING_TIME   TIMESTAMP,
    CEC_REMARK        VARCHAR(1000),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 授权权益证书模板(可研 3.2.2.1.1.3.4.2:专项/批量授权证书模板)
CREATE TABLE IF NOT EXISTS IM_AUTH_CERT_TEMPLATE (
    CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL,
    CEC_TEMPLATE_VERSION VARCHAR(20),
    CEC_CERT_TYPE        VARCHAR(50),
    CEC_RIGHT_TYPE       VARCHAR(100),
    CEC_TEMPLATE_CONTENT CLOB,
    CEC_TEMPLATE_STATUS  VARCHAR(50),
    CEC_FILE_NAME        VARCHAR(300),
    CEC_FILE_DATA        CLOB,
    CEC_PROVINCE_CODE    VARCHAR(32),
    CEC_BUREAU_CODE      VARCHAR(32),
    CEC_CREATOR_ID       VARCHAR(64),
    CEC_CREATE_TIME      TIMESTAMP,
    CEC_UPDATER_ID       VARCHAR(64),
    CEC_UPDATE_TIME      TIMESTAMP,
    CEC_DEL_FLAG         INT DEFAULT 0
);

-- 授权指引材料(可研 3.2.2.1.1.3.1.1:政策/流程图/常见问答/申请步骤 + 上传下载 + 历史版本)
CREATE TABLE IF NOT EXISTS IM_AUTH_GUIDANCE (
    CEC_GUIDANCE_ID   VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_TITLE         VARCHAR(255) NOT NULL,
    CEC_GUIDANCE_TYPE VARCHAR(100),
    CEC_VERSION       VARCHAR(20),
    CEC_PUBLISHER     VARCHAR(100),
    CEC_PUBLISH_DATE  TIMESTAMP,
    CEC_FILE_URL      VARCHAR(500),
    CEC_FILE_NAME     VARCHAR(300),
    CEC_FILE_DATA     CLOB,
    CEC_IS_LATEST     BOOLEAN DEFAULT TRUE,
    CEC_CONTENT       CLOB,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 授权申请表单模板(可研 3.2.2.1.1.3.1.2:按授权类型 独占/共享/委托 配置字段/流程/验证规则)
CREATE TABLE IF NOT EXISTS IM_AUTH_APPLY_TEMPLATE (
    CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL,
    CEC_AUTH_TYPE        VARCHAR(50),
    CEC_FIELDS_JSON      CLOB,
    CEC_FLOW_DESC        VARCHAR(2000),
    CEC_TEMPLATE_VERSION VARCHAR(20),
    CEC_TEMPLATE_STATUS  VARCHAR(50),
    CEC_REMARK           VARCHAR(1000),
    CEC_PROVINCE_CODE    VARCHAR(32),
    CEC_BUREAU_CODE      VARCHAR(32),
    CEC_CREATOR_ID       VARCHAR(64),
    CEC_CREATE_TIME      TIMESTAMP,
    CEC_UPDATER_ID       VARCHAR(64),
    CEC_UPDATE_TIME      TIMESTAMP,
    CEC_DEL_FLAG         INT DEFAULT 0
);

-- 授权应用场景配置(可研 3.2.2.1.1.3.1.3:用途场景 分类/描述 + 申请原因模板)
CREATE TABLE IF NOT EXISTS IM_AUTH_SCENARIO (
    CEC_SCENARIO_ID     VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_SCENARIO_NAME   VARCHAR(255) NOT NULL,
    CEC_CATEGORY        VARCHAR(100),
    CEC_DESCRIPTION     VARCHAR(1000),
    CEC_REASON_TEMPLATE VARCHAR(2000),
    CEC_SCENARIO_STATUS VARCHAR(50),
    CEC_PROVINCE_CODE   VARCHAR(32),
    CEC_BUREAU_CODE     VARCHAR(32),
    CEC_CREATOR_ID      VARCHAR(64),
    CEC_CREATE_TIME     TIMESTAMP,
    CEC_UPDATER_ID      VARCHAR(64),
    CEC_UPDATE_TIME     TIMESTAMP,
    CEC_DEL_FLAG        INT DEFAULT 0
);

-- 授权申请材料(可研 3.2.2.1.1.3.1.4:上传相关材料,Base64 入库)
CREATE TABLE IF NOT EXISTS IM_AUTH_MATERIAL (
    CEC_MATERIAL_ID   VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_APPLY_ID      VARCHAR(64),
    CEC_MATERIAL_NAME VARCHAR(300),
    CEC_MATERIAL_TYPE VARCHAR(100),
    CEC_OWNER         VARCHAR(100),
    CEC_UPLOAD_TIME   TIMESTAMP,
    CEC_FILE_NAME     VARCHAR(300),
    CEC_FILE_DATA     CLOB,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 授权申请审批处理记录(可研 3.2.2.1.1.3.2.1:审批轨迹 from→to/责任人/审核意见/时间)
CREATE TABLE IF NOT EXISTS IM_AUTH_FLOW_LOG (
    CEC_LOG_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_APPLY_ID    VARCHAR(64),
    CEC_APPLY_NO    VARCHAR(64),
    CEC_FROM_STATUS VARCHAR(50),
    CEC_TO_STATUS   VARCHAR(50),
    CEC_NODE_NAME   VARCHAR(100),
    CEC_RESPONDER   VARCHAR(100),
    CEC_OPINION     VARCHAR(2000),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE VARCHAR(32),
    CEC_CREATOR_ID  VARCHAR(64),
    CEC_CREATE_TIME TIMESTAMP,
    CEC_UPDATER_ID  VARCHAR(64),
    CEC_UPDATE_TIME TIMESTAMP,
    CEC_DEL_FLAG    INT DEFAULT 0
);

-- 授权协议模板库(可研 3.2.2.1.1.3.3.1:授权类型/使用目的分类 + 版本 + 内容 + 套版文件上传下载)
CREATE TABLE IF NOT EXISTS IM_AUTH_AGREEMENT_TEMPLATE (
    CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL,
    CEC_AUTH_TYPE        VARCHAR(50),
    CEC_PURPOSE          VARCHAR(100),
    CEC_TEMPLATE_CONTENT CLOB,
    CEC_TEMPLATE_VERSION VARCHAR(20),
    CEC_TEMPLATE_STATUS  VARCHAR(50),
    CEC_FILE_NAME        VARCHAR(300),
    CEC_FILE_DATA        CLOB,
    CEC_PROVINCE_CODE    VARCHAR(32),
    CEC_BUREAU_CODE      VARCHAR(32),
    CEC_CREATOR_ID       VARCHAR(64),
    CEC_CREATE_TIME      TIMESTAMP,
    CEC_UPDATER_ID       VARCHAR(64),
    CEC_UPDATE_TIME      TIMESTAMP,
    CEC_DEL_FLAG         INT DEFAULT 0
);

-- 授权签章上传记录(可研 3.2.2.1.1.3.3.2:上传行为 + 格式校验 + 签章有效性验证结果)
CREATE TABLE IF NOT EXISTS IM_AUTH_SEAL_UPLOAD_LOG (
    CEC_LOG_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_AGREEMENT_ID VARCHAR(64),
    CEC_UPLOADER_ROLE VARCHAR(50),
    CEC_FILE_NAME    VARCHAR(300),
    CEC_FILE_DATA    CLOB,
    CEC_FORMAT_OK    BOOLEAN,
    CEC_SEAL_VALID   BOOLEAN,
    CEC_VERIFY_RESULT VARCHAR(500),
    CEC_UPLOAD_TIME  TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE  VARCHAR(32),
    CEC_CREATOR_ID   VARCHAR(64),
    CEC_CREATE_TIME  TIMESTAMP,
    CEC_UPDATER_ID   VARCHAR(64),
    CEC_UPDATE_TIME  TIMESTAMP,
    CEC_DEL_FLAG     INT DEFAULT 0
);

-- 授权协议审核记录(可研 3.2.2.1.1.3.3.3:审核人/结论/意见/时间)
CREATE TABLE IF NOT EXISTS IM_AUTH_AGR_REVIEW_LOG (
    CEC_LOG_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_AGREEMENT_ID VARCHAR(64),
    CEC_AGREEMENT_NO VARCHAR(64),
    CEC_REVIEWER     VARCHAR(100),
    CEC_RESULT       VARCHAR(50),
    CEC_OPINION      VARCHAR(2000),
    CEC_REVIEW_TIME  TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE  VARCHAR(32),
    CEC_CREATOR_ID   VARCHAR(64),
    CEC_CREATE_TIME  TIMESTAMP,
    CEC_UPDATER_ID   VARCHAR(64),
    CEC_UPDATE_TIME  TIMESTAMP,
    CEC_DEL_FLAG     INT DEFAULT 0
);

-- 授权协议存档审计日志(可研 3.2.2.1.1.3.3.4:归档/查看/下载 访问留痕,可追溯)
CREATE TABLE IF NOT EXISTS IM_AUTH_ARCHIVE_LOG (
    CEC_LOG_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_AGREEMENT_ID VARCHAR(64),
    CEC_AGREEMENT_NO VARCHAR(64),
    CEC_ACTION       VARCHAR(50),
    CEC_OPERATOR     VARCHAR(100),
    CEC_OPERATE_TIME TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE  VARCHAR(32),
    CEC_CREATOR_ID   VARCHAR(64),
    CEC_CREATE_TIME  TIMESTAMP,
    CEC_UPDATER_ID   VARCHAR(64),
    CEC_UPDATE_TIME  TIMESTAMP,
    CEC_DEL_FLAG     INT DEFAULT 0
);

-- 授权应交材料清单规则(可配置,单一真源:场景×触发条件 → 应交材料)
CREATE TABLE IF NOT EXISTS IM_AUTH_MATERIAL_RULE (
    CEC_RULE_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_SCENE         VARCHAR(50)  NOT NULL,
    CEC_TRIGGER_TYPE  VARCHAR(20)  NOT NULL,
    CEC_MATERIAL_NAME VARCHAR(300) NOT NULL,
    CEC_REQUIRED      VARCHAR(20),
    CEC_EVIDENCE_TYPE VARCHAR(20),
    CEC_DETAIL        VARCHAR(1000),
    CEC_TEMPLATE_REF  VARCHAR(64),
    CEC_SORT_NO       INT,
    CEC_ENABLED       BOOLEAN DEFAULT TRUE,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 组织机构主数据(只读,镜像平台 DAMS.SYS_ORGANIZATION 的 PRM 消费子集;数据由平台/4A 同步,PRM 不写)
CREATE TABLE IF NOT EXISTS SYS_ORGANIZATION (
    ID            VARCHAR(60) NOT NULL PRIMARY KEY,
    BIZ_ORG_ID    VARCHAR(32),
    BIZ_ORG_NAME  VARCHAR(200),
    BIZ_ORG_CODE  VARCHAR(60),
    SHORT_NAME    VARCHAR(200),
    PARENT_ID     VARCHAR(60),
    ORG_LEVEL     VARCHAR(32),
    ORG_TYPE      VARCHAR(32),
    CITY_CODE     VARCHAR(32),
    SORT_NO       VARCHAR(30),
    BASE_ORG_CODE VARCHAR(120)
);
CREATE INDEX IF NOT EXISTS IDX_SYS_ORG_PARENT ON SYS_ORGANIZATION (PARENT_ID);
