-- 数据授权申请单表
-- 区块链存证记录(国密SM3指纹 + 上链回执,全节点留痕,prm-common 共享)
CREATE TABLE IF NOT EXISTS IM_DPR_EVIDENCE (
    CEC_EVIDENCE_ID   VARCHAR(64) NOT NULL PRIMARY KEY,
    CEC_BIZ_TYPE      VARCHAR(50),
    CEC_BIZ_ID        VARCHAR(64),
    CEC_SUMMARY       VARCHAR(500),
    CEC_SM3_HASH      VARCHAR(64),
    CEC_CHAIN_TX_HASH VARCHAR(80),
    CEC_BLOCK_HEIGHT  BIGINT,
    CEC_ANCHOR_STATUS VARCHAR(20),
    CEC_EVIDENCE_TIME TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS IM_AUTH_APPLY (
    CEC_APPLY_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_APPLY_NO      VARCHAR(64),
    CEC_AUTH_MODE     VARCHAR(50),
    CEC_ASSET_ID      VARCHAR(64)  NOT NULL,
    CEC_ASSET_NAME    VARCHAR(255) NOT NULL,
    CEC_EQUITY_CARD_ID VARCHAR(64),
    CEC_GRANTEE_ORG   VARCHAR(255),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_SCENARIO      VARCHAR(500),
    CEC_SCOPE         VARCHAR(1000),
    CEC_VALID_DATE    TIMESTAMP,
    CEC_STATUS        VARCHAR(50),
    CEC_REJECT_REASON VARCHAR(1000),
    CEC_CURRENT_NODE  INT,
    CEC_BATCH_LIST_ID VARCHAR(64),
    CEC_NEED_CONFIDENTIALITY BOOLEAN,
    CEC_CONFIDENTIALITY_FILE VARCHAR(500),
    CEC_BUSINESS_DOMAIN   VARCHAR(100),
    CEC_CROSS_REGION      BOOLEAN,
    CEC_THIRD_PARTY_SOURCE VARCHAR(255),
    CEC_THIRD_PARTY_LICENSE VARCHAR(1000),
    CEC_SENSITIVE_TYPE    VARCHAR(100),
    CEC_INFO_AUTH_AGREEMENT VARCHAR(500),
    CEC_APPLICANT_MANAGER VARCHAR(100),
    CEC_CONTACT           VARCHAR(100),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 对外数据经营权授权备案(附录G / 附录F §3.4.6)
CREATE TABLE IF NOT EXISTS IM_AUTH_FILING (
    CEC_FILING_ID     VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_FILING_NO     VARCHAR(64),
    CEC_AGREEMENT_ID  VARCHAR(64),
    CEC_APPLY_ID      VARCHAR(64),
    CEC_FILING_ORG    VARCHAR(255),
    CEC_GRANTEE_ORG   VARCHAR(255),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_FILING_STATUS VARCHAR(50),
    CEC_FILING_TIME   TIMESTAMP,
    CEC_REMARK        VARCHAR(1000),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 表6 数据批量授权清单
CREATE TABLE IF NOT EXISTS IM_BATCH_AUTH_LIST (
    CEC_BATCH_LIST_ID VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_LIST_NO       VARCHAR(64),
    CEC_LIST_YEAR     VARCHAR(20),
    CEC_LIST_STATUS   VARCHAR(50),
    CEC_ITEM_COUNT    INT,
    CEC_REMARK        VARCHAR(1000),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 授权权益证书表
CREATE TABLE IF NOT EXISTS IM_AUTH_CERT (
    CEC_CERT_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_CERT_NO       VARCHAR(64),
    CEC_APPLY_ID      VARCHAR(64),
    CEC_ASSET_ID      VARCHAR(64),
    CEC_GRANTEE_ORG   VARCHAR(255),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_SCOPE         VARCHAR(1000),
    CEC_VALID_DATE    TIMESTAMP,
    CEC_CERT_STATUS   VARCHAR(50),
    CEC_SUSPEND_REASON VARCHAR(1000),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 违规追责记录(监测联动熔断暂停授权时建账,附录F 3.4.5)
CREATE TABLE IF NOT EXISTS IM_AUTH_ACCOUNTABILITY (
    CEC_ACCOUNT_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_CERT_ID          VARCHAR(64),
    CEC_ASSET_ID         VARCHAR(64),
    CEC_GRANTEE_ORG      VARCHAR(255),
    CEC_VIOLATION_TYPE   VARCHAR(100),
    CEC_SOURCE_ALERT_ID  VARCHAR(64),
    CEC_REASON           VARCHAR(1000),
    CEC_HANDLE_STATUS    VARCHAR(50),
    CEC_RESPONSIBLE_PARTY VARCHAR(255),
    CEC_HANDLE_FEEDBACK  VARCHAR(1000),
    CEC_HANDLE_TIME      TIMESTAMP,
    CEC_PROVINCE_CODE    VARCHAR(32),
    CEC_BUREAU_CODE      VARCHAR(32),
    CEC_CREATOR_ID       VARCHAR(64),
    CEC_CREATE_TIME      TIMESTAMP,
    CEC_UPDATER_ID       VARCHAR(64),
    CEC_UPDATE_TIME      TIMESTAMP,
    CEC_DEL_FLAG         INT DEFAULT 0
);

-- 授权域通用目录项(指引/场景/申请表单模板/协议模板库)
CREATE TABLE IF NOT EXISTS IM_AUTH_CATALOG_ITEM (
    CEC_ITEM_ID       VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_CATEGORY      VARCHAR(50)  NOT NULL,
    CEC_NAME          VARCHAR(255) NOT NULL,
    CEC_ITEM_TYPE     VARCHAR(100),
    CEC_VERSION       VARCHAR(20),
    CEC_CONTENT       CLOB,
    CEC_STATUS        VARCHAR(50),
    CEC_PUBLISHER     VARCHAR(100),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 授权申请合规校验结果
CREATE TABLE IF NOT EXISTS IM_AUTH_COMPLIANCE (
    CEC_CHECK_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_APPLY_ID      VARCHAR(64),
    CEC_RISK_LEVEL    VARCHAR(20),
    CEC_CHECK_RESULT  VARCHAR(50),
    CEC_PROBLEM_DESC  VARCHAR(2000),
    CEC_CHECK_TIME    TIMESTAMP,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 数据运营授权协议(签章/审核/存档/下载)
CREATE TABLE IF NOT EXISTS IM_AUTH_AGREEMENT (
    CEC_AGREEMENT_ID   VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_AGREEMENT_NO   VARCHAR(64),
    CEC_APPLY_ID       VARCHAR(64),
    CEC_TEMPLATE_ID    VARCHAR(64),
    CEC_GRANTEE_ORG    VARCHAR(255),
    CEC_FILE_URL       VARCHAR(500),
    CEC_SEAL_STATUS    VARCHAR(50),
    CEC_SEAL_VERIFY    VARCHAR(100),
    CEC_GRANTOR_SIGNED BOOLEAN,
    CEC_GRANTOR_SIGN_TIME TIMESTAMP,
    CEC_GRANTEE_SIGNED BOOLEAN,
    CEC_GRANTEE_SIGN_TIME TIMESTAMP,
    CEC_REVIEW_STATUS  VARCHAR(50),
    CEC_ARCHIVE_STATUS VARCHAR(50),
    CEC_SIGN_TIME      TIMESTAMP,
    CEC_PROVINCE_CODE  VARCHAR(32),
    CEC_BUREAU_CODE    VARCHAR(32),
    CEC_CREATOR_ID     VARCHAR(64),
    CEC_CREATE_TIME    TIMESTAMP,
    CEC_UPDATER_ID     VARCHAR(64),
    CEC_UPDATE_TIME    TIMESTAMP,
    CEC_DEL_FLAG       INT DEFAULT 0
);

-- 对外数据经营权授权备案(附录G)
CREATE TABLE IF NOT EXISTS IM_AUTH_FILING (
    CEC_FILING_ID     VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_FILING_NO     VARCHAR(64),
    CEC_AGREEMENT_ID  VARCHAR(64),
    CEC_APPLY_ID      VARCHAR(64),
    CEC_FILING_ORG    VARCHAR(255),
    CEC_GRANTEE_ORG   VARCHAR(255),
    CEC_RIGHT_TYPE    VARCHAR(100),
    CEC_FILING_STATUS VARCHAR(50),
    CEC_FILING_TIME   TIMESTAMP,
    CEC_REMARK        VARCHAR(1000),
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 授权权益证书模板(可研 3.2.2.1.1.3.4.2:专项/批量授权证书模板)
CREATE TABLE IF NOT EXISTS IM_AUTH_CERT_TEMPLATE (
    CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL,
    CEC_TEMPLATE_VERSION VARCHAR(20),
    CEC_CERT_TYPE        VARCHAR(50),
    CEC_RIGHT_TYPE       VARCHAR(100),
    CEC_TEMPLATE_CONTENT CLOB,
    CEC_TEMPLATE_STATUS  VARCHAR(50),
    CEC_PROVINCE_CODE    VARCHAR(32),
    CEC_BUREAU_CODE      VARCHAR(32),
    CEC_CREATOR_ID       VARCHAR(64),
    CEC_CREATE_TIME      TIMESTAMP,
    CEC_UPDATER_ID       VARCHAR(64),
    CEC_UPDATE_TIME      TIMESTAMP,
    CEC_DEL_FLAG         INT DEFAULT 0
);

-- 授权指引材料(可研 3.2.2.1.1.3.1.1:政策/流程图/常见问答/申请步骤 + 上传下载 + 历史版本)
CREATE TABLE IF NOT EXISTS IM_AUTH_GUIDANCE (
    CEC_GUIDANCE_ID   VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_TITLE         VARCHAR(255) NOT NULL,
    CEC_GUIDANCE_TYPE VARCHAR(100),
    CEC_VERSION       VARCHAR(20),
    CEC_PUBLISHER     VARCHAR(100),
    CEC_PUBLISH_DATE  TIMESTAMP,
    CEC_FILE_URL      VARCHAR(500),
    CEC_FILE_NAME     VARCHAR(300),
    CEC_FILE_DATA     CLOB,
    CEC_IS_LATEST     BOOLEAN DEFAULT TRUE,
    CEC_CONTENT       CLOB,
    CEC_PROVINCE_CODE VARCHAR(32),
    CEC_BUREAU_CODE   VARCHAR(32),
    CEC_CREATOR_ID    VARCHAR(64),
    CEC_CREATE_TIME   TIMESTAMP,
    CEC_UPDATER_ID    VARCHAR(64),
    CEC_UPDATE_TIME   TIMESTAMP,
    CEC_DEL_FLAG      INT DEFAULT 0
);

-- 授权申请表单模板(可研 3.2.2.1.1.3.1.2:按授权类型 独占/共享/委托 配置字段/流程/验证规则)
CREATE TABLE IF NOT EXISTS IM_AUTH_APPLY_TEMPLATE (
    CEC_TEMPLATE_ID      VARCHAR(64)  NOT NULL PRIMARY KEY,
    CEC_TEMPLATE_NAME    VARCHAR(255) NOT NULL,
    CEC_AUTH_TYPE        VARCHAR(50),
    CEC_FIELDS_JSON      CLOB,
    CEC_FLOW_DESC        VARCHAR(2000),
    CEC_TEMPLATE_VERSION VARCHAR(20),
    CEC_TEMPLATE_STATUS  VARCHAR(50),
    CEC_REMARK           VARCHAR(1000),
    CEC_PROVINCE_CODE    VARCHAR(32),
    CEC_BUREAU_CODE      VARCHAR(32),
    CEC_CREATOR_ID       VARCHAR(64),
    CEC_CREATE_TIME      TIMESTAMP,
    CEC_UPDATER_ID       VARCHAR(64),
    CEC_UPDATE_TIME      TIMESTAMP,
    CEC_DEL_FLAG         INT DEFAULT 0
);
